// Code generated by skaff types DO NOT EDIT.

package types

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
)

var _ basetypes.ObjectTypable = RuletypesRenotifyType{}

type RuletypesRenotifyType struct {
	basetypes.ObjectType
}

func (t RuletypesRenotifyType) Equal(o attr.Type) bool {
	other, ok := o.(RuletypesRenotifyType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t RuletypesRenotifyType) String() string {
	return "RuletypesRenotifyType"
}

func (t RuletypesRenotifyType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	alertStatesAttribute, ok := attributes["alert_states"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`alert_states is missing from object`)

		return nil, diags
	}

	alertStatesVal, ok := alertStatesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`alert_states expected to be basetypes.ListValue, was: %T`, alertStatesAttribute))
	}

	enabledAttribute, ok := attributes["enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`enabled is missing from object`)

		return nil, diags
	}

	enabledVal, ok := enabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`enabled expected to be basetypes.BoolValue, was: %T`, enabledAttribute))
	}

	intervalAttribute, ok := attributes["interval"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`interval is missing from object`)

		return nil, diags
	}

	intervalVal, ok := intervalAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`interval expected to be basetypes.StringValue, was: %T`, intervalAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return RuletypesRenotifyValue{
		AlertStates: alertStatesVal,
		Enabled:     enabledVal,
		Interval:    intervalVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewRuletypesRenotifyValueNull() RuletypesRenotifyValue {
	return RuletypesRenotifyValue{
		state: attr.ValueStateNull,
	}
}

func NewRuletypesRenotifyValueUnknown() RuletypesRenotifyValue {
	return RuletypesRenotifyValue{
		state: attr.ValueStateUnknown,
	}
}

func NewRuletypesRenotifyValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (RuletypesRenotifyValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing RuletypesRenotifyValue Attribute Value",
				"While creating a RuletypesRenotifyValue value, a missing attribute value was detected. "+
					"A RuletypesRenotifyValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RuletypesRenotifyValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid RuletypesRenotifyValue Attribute Type",
				"While creating a RuletypesRenotifyValue value, an invalid attribute value was detected. "+
					"A RuletypesRenotifyValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RuletypesRenotifyValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("RuletypesRenotifyValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra RuletypesRenotifyValue Attribute Value",
				"While creating a RuletypesRenotifyValue value, an extra attribute value was detected. "+
					"A RuletypesRenotifyValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra RuletypesRenotifyValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewRuletypesRenotifyValueUnknown(), diags
	}

	alertStatesAttribute, ok := attributes["alert_states"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`alert_states is missing from object`)

		return NewRuletypesRenotifyValueUnknown(), diags
	}

	alertStatesVal, ok := alertStatesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`alert_states expected to be basetypes.ListValue, was: %T`, alertStatesAttribute))
	}

	enabledAttribute, ok := attributes["enabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`enabled is missing from object`)

		return NewRuletypesRenotifyValueUnknown(), diags
	}

	enabledVal, ok := enabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`enabled expected to be basetypes.BoolValue, was: %T`, enabledAttribute))
	}

	intervalAttribute, ok := attributes["interval"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`interval is missing from object`)

		return NewRuletypesRenotifyValueUnknown(), diags
	}

	intervalVal, ok := intervalAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`interval expected to be basetypes.StringValue, was: %T`, intervalAttribute))
	}

	if diags.HasError() {
		return NewRuletypesRenotifyValueUnknown(), diags
	}

	return RuletypesRenotifyValue{
		AlertStates: alertStatesVal,
		Enabled:     enabledVal,
		Interval:    intervalVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewRuletypesRenotifyValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) RuletypesRenotifyValue {
	object, diags := NewRuletypesRenotifyValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewRuletypesRenotifyValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t RuletypesRenotifyType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewRuletypesRenotifyValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewRuletypesRenotifyValueUnknown(), nil
	}

	if in.IsNull() {
		return NewRuletypesRenotifyValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewRuletypesRenotifyValueMust(RuletypesRenotifyValue{}.AttributeTypes(ctx), attributes), nil
}

func (t RuletypesRenotifyType) ValueType(ctx context.Context) attr.Value {
	return RuletypesRenotifyValue{}
}

var _ basetypes.ObjectValuable = RuletypesRenotifyValue{}

type RuletypesRenotifyValue struct {
	AlertStates basetypes.ListValue   `tfsdk:"alert_states"`
	Enabled     basetypes.BoolValue   `tfsdk:"enabled"`
	Interval    basetypes.StringValue `tfsdk:"interval"`
	state       attr.ValueState
}

func (v RuletypesRenotifyValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["alert_states"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["enabled"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["interval"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.AlertStates.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["alert_states"] = val

		val, err = v.Enabled.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["enabled"] = val

		val, err = v.Interval.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["interval"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v RuletypesRenotifyValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v RuletypesRenotifyValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v RuletypesRenotifyValue) String() string {
	return "RuletypesRenotifyValue"
}

func (v RuletypesRenotifyValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var alertStatesVal basetypes.ListValue
	switch {
	case v.AlertStates.IsUnknown():
		alertStatesVal = types.ListUnknown(types.StringType)
	case v.AlertStates.IsNull():
		alertStatesVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		alertStatesVal, d = types.ListValue(types.StringType, v.AlertStates.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"alert_states": basetypes.ListType{
				ElemType: types.StringType,
			},
			"enabled":  basetypes.BoolType{},
			"interval": basetypes.StringType{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"alert_states": basetypes.ListType{
			ElemType: types.StringType,
		},
		"enabled":  basetypes.BoolType{},
		"interval": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"alert_states": alertStatesVal,
			"enabled":      v.Enabled,
			"interval":     v.Interval,
		})

	return objVal, diags
}

func (v RuletypesRenotifyValue) Equal(o attr.Value) bool {
	other, ok := o.(RuletypesRenotifyValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AlertStates.Equal(other.AlertStates) {
		return false
	}

	if !v.Enabled.Equal(other.Enabled) {
		return false
	}

	if !v.Interval.Equal(other.Interval) {
		return false
	}

	return true
}

func (v RuletypesRenotifyValue) Type(ctx context.Context) attr.Type {
	return RuletypesRenotifyType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v RuletypesRenotifyValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"alert_states": basetypes.ListType{
			ElemType: types.StringType,
		},
		"enabled":  basetypes.BoolType{},
		"interval": basetypes.StringType{},
	}
}
