// Code generated by skaff types DO NOT EDIT.

package types

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
)

var _ basetypes.ObjectTypable = ConfigTelegramConfigType{}

type ConfigTelegramConfigType struct {
	basetypes.ObjectType
}

func (t ConfigTelegramConfigType) Equal(o attr.Type) bool {
	other, ok := o.(ConfigTelegramConfigType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ConfigTelegramConfigType) String() string {
	return "ConfigTelegramConfigType"
}

func (t ConfigTelegramConfigType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	apiUrlAttribute, ok := attributes["api_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`api_url is missing from object`)

		return nil, diags
	}

	apiUrlVal, ok := apiUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`api_url expected to be basetypes.StringValue, was: %T`, apiUrlAttribute))
	}

	chatAttribute, ok := attributes["chat"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`chat is missing from object`)

		return nil, diags
	}

	chatVal, ok := chatAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`chat expected to be basetypes.Int64Value, was: %T`, chatAttribute))
	}

	chatFileAttribute, ok := attributes["chat_file"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`chat_file is missing from object`)

		return nil, diags
	}

	chatFileVal, ok := chatFileAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`chat_file expected to be basetypes.StringValue, was: %T`, chatFileAttribute))
	}

	disableNotificationsAttribute, ok := attributes["disable_notifications"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`disable_notifications is missing from object`)

		return nil, diags
	}

	disableNotificationsVal, ok := disableNotificationsAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`disable_notifications expected to be basetypes.BoolValue, was: %T`, disableNotificationsAttribute))
	}

	httpConfigAttribute, ok := attributes["http_config"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`http_config is missing from object`)

		return nil, diags
	}

	httpConfigVal, ok := httpConfigAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`http_config expected to be basetypes.ObjectValue, was: %T`, httpConfigAttribute))
	}

	messageAttribute, ok := attributes["message"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`message is missing from object`)

		return nil, diags
	}

	messageVal, ok := messageAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`message expected to be basetypes.StringValue, was: %T`, messageAttribute))
	}

	messageThreadIdAttribute, ok := attributes["message_thread_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`message_thread_id is missing from object`)

		return nil, diags
	}

	messageThreadIdVal, ok := messageThreadIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`message_thread_id expected to be basetypes.Int64Value, was: %T`, messageThreadIdAttribute))
	}

	parseModeAttribute, ok := attributes["parse_mode"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`parse_mode is missing from object`)

		return nil, diags
	}

	parseModeVal, ok := parseModeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`parse_mode expected to be basetypes.StringValue, was: %T`, parseModeAttribute))
	}

	sendResolvedAttribute, ok := attributes["send_resolved"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`send_resolved is missing from object`)

		return nil, diags
	}

	sendResolvedVal, ok := sendResolvedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`send_resolved expected to be basetypes.BoolValue, was: %T`, sendResolvedAttribute))
	}

	tokenAttribute, ok := attributes["token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`token is missing from object`)

		return nil, diags
	}

	tokenVal, ok := tokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`token expected to be basetypes.StringValue, was: %T`, tokenAttribute))
	}

	tokenFileAttribute, ok := attributes["token_file"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`token_file is missing from object`)

		return nil, diags
	}

	tokenFileVal, ok := tokenFileAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`token_file expected to be basetypes.StringValue, was: %T`, tokenFileAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ConfigTelegramConfigValue{
		ApiUrl:               apiUrlVal,
		Chat:                 chatVal,
		ChatFile:             chatFileVal,
		DisableNotifications: disableNotificationsVal,
		HttpConfig:           httpConfigVal,
		Message:              messageVal,
		MessageThreadId:      messageThreadIdVal,
		ParseMode:            parseModeVal,
		SendResolved:         sendResolvedVal,
		Token:                tokenVal,
		TokenFile:            tokenFileVal,
		state:                attr.ValueStateKnown,
	}, diags
}

func NewConfigTelegramConfigValueNull() ConfigTelegramConfigValue {
	return ConfigTelegramConfigValue{
		state: attr.ValueStateNull,
	}
}

func NewConfigTelegramConfigValueUnknown() ConfigTelegramConfigValue {
	return ConfigTelegramConfigValue{
		state: attr.ValueStateUnknown,
	}
}

func NewConfigTelegramConfigValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ConfigTelegramConfigValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ConfigTelegramConfigValue Attribute Value",
				"While creating a ConfigTelegramConfigValue value, a missing attribute value was detected. "+
					"A ConfigTelegramConfigValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigTelegramConfigValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ConfigTelegramConfigValue Attribute Type",
				"While creating a ConfigTelegramConfigValue value, an invalid attribute value was detected. "+
					"A ConfigTelegramConfigValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigTelegramConfigValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ConfigTelegramConfigValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ConfigTelegramConfigValue Attribute Value",
				"While creating a ConfigTelegramConfigValue value, an extra attribute value was detected. "+
					"A ConfigTelegramConfigValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ConfigTelegramConfigValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewConfigTelegramConfigValueUnknown(), diags
	}

	apiUrlAttribute, ok := attributes["api_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`api_url is missing from object`)

		return NewConfigTelegramConfigValueUnknown(), diags
	}

	apiUrlVal, ok := apiUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`api_url expected to be basetypes.StringValue, was: %T`, apiUrlAttribute))
	}

	chatAttribute, ok := attributes["chat"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`chat is missing from object`)

		return NewConfigTelegramConfigValueUnknown(), diags
	}

	chatVal, ok := chatAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`chat expected to be basetypes.Int64Value, was: %T`, chatAttribute))
	}

	chatFileAttribute, ok := attributes["chat_file"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`chat_file is missing from object`)

		return NewConfigTelegramConfigValueUnknown(), diags
	}

	chatFileVal, ok := chatFileAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`chat_file expected to be basetypes.StringValue, was: %T`, chatFileAttribute))
	}

	disableNotificationsAttribute, ok := attributes["disable_notifications"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`disable_notifications is missing from object`)

		return NewConfigTelegramConfigValueUnknown(), diags
	}

	disableNotificationsVal, ok := disableNotificationsAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`disable_notifications expected to be basetypes.BoolValue, was: %T`, disableNotificationsAttribute))
	}

	httpConfigAttribute, ok := attributes["http_config"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`http_config is missing from object`)

		return NewConfigTelegramConfigValueUnknown(), diags
	}

	httpConfigVal, ok := httpConfigAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`http_config expected to be basetypes.ObjectValue, was: %T`, httpConfigAttribute))
	}

	messageAttribute, ok := attributes["message"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`message is missing from object`)

		return NewConfigTelegramConfigValueUnknown(), diags
	}

	messageVal, ok := messageAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`message expected to be basetypes.StringValue, was: %T`, messageAttribute))
	}

	messageThreadIdAttribute, ok := attributes["message_thread_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`message_thread_id is missing from object`)

		return NewConfigTelegramConfigValueUnknown(), diags
	}

	messageThreadIdVal, ok := messageThreadIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`message_thread_id expected to be basetypes.Int64Value, was: %T`, messageThreadIdAttribute))
	}

	parseModeAttribute, ok := attributes["parse_mode"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`parse_mode is missing from object`)

		return NewConfigTelegramConfigValueUnknown(), diags
	}

	parseModeVal, ok := parseModeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`parse_mode expected to be basetypes.StringValue, was: %T`, parseModeAttribute))
	}

	sendResolvedAttribute, ok := attributes["send_resolved"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`send_resolved is missing from object`)

		return NewConfigTelegramConfigValueUnknown(), diags
	}

	sendResolvedVal, ok := sendResolvedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`send_resolved expected to be basetypes.BoolValue, was: %T`, sendResolvedAttribute))
	}

	tokenAttribute, ok := attributes["token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`token is missing from object`)

		return NewConfigTelegramConfigValueUnknown(), diags
	}

	tokenVal, ok := tokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`token expected to be basetypes.StringValue, was: %T`, tokenAttribute))
	}

	tokenFileAttribute, ok := attributes["token_file"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`token_file is missing from object`)

		return NewConfigTelegramConfigValueUnknown(), diags
	}

	tokenFileVal, ok := tokenFileAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`token_file expected to be basetypes.StringValue, was: %T`, tokenFileAttribute))
	}

	if diags.HasError() {
		return NewConfigTelegramConfigValueUnknown(), diags
	}

	return ConfigTelegramConfigValue{
		ApiUrl:               apiUrlVal,
		Chat:                 chatVal,
		ChatFile:             chatFileVal,
		DisableNotifications: disableNotificationsVal,
		HttpConfig:           httpConfigVal,
		Message:              messageVal,
		MessageThreadId:      messageThreadIdVal,
		ParseMode:            parseModeVal,
		SendResolved:         sendResolvedVal,
		Token:                tokenVal,
		TokenFile:            tokenFileVal,
		state:                attr.ValueStateKnown,
	}, diags
}

func NewConfigTelegramConfigValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ConfigTelegramConfigValue {
	object, diags := NewConfigTelegramConfigValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewConfigTelegramConfigValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ConfigTelegramConfigType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewConfigTelegramConfigValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewConfigTelegramConfigValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigTelegramConfigValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewConfigTelegramConfigValueMust(ConfigTelegramConfigValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ConfigTelegramConfigType) ValueType(ctx context.Context) attr.Value {
	return ConfigTelegramConfigValue{}
}

var _ basetypes.ObjectValuable = ConfigTelegramConfigValue{}

type ConfigTelegramConfigValue struct {
	ApiUrl               basetypes.StringValue `tfsdk:"api_url"`
	Chat                 basetypes.Int64Value  `tfsdk:"chat"`
	ChatFile             basetypes.StringValue `tfsdk:"chat_file"`
	DisableNotifications basetypes.BoolValue   `tfsdk:"disable_notifications"`
	HttpConfig           basetypes.ObjectValue `tfsdk:"http_config"`
	Message              basetypes.StringValue `tfsdk:"message"`
	MessageThreadId      basetypes.Int64Value  `tfsdk:"message_thread_id"`
	ParseMode            basetypes.StringValue `tfsdk:"parse_mode"`
	SendResolved         basetypes.BoolValue   `tfsdk:"send_resolved"`
	Token                basetypes.StringValue `tfsdk:"token"`
	TokenFile            basetypes.StringValue `tfsdk:"token_file"`
	state                attr.ValueState
}

func (v ConfigTelegramConfigValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 11)

	var val tftypes.Value
	var err error

	attrTypes["api_url"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["chat"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["chat_file"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["disable_notifications"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["http_config"] = basetypes.ObjectType{
		AttrTypes: ConfigHttpclientConfigValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["message"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["message_thread_id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["parse_mode"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["send_resolved"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["token"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["token_file"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 11)

		val, err = v.ApiUrl.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["api_url"] = val

		val, err = v.Chat.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["chat"] = val

		val, err = v.ChatFile.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["chat_file"] = val

		val, err = v.DisableNotifications.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["disable_notifications"] = val

		val, err = v.HttpConfig.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["http_config"] = val

		val, err = v.Message.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["message"] = val

		val, err = v.MessageThreadId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["message_thread_id"] = val

		val, err = v.ParseMode.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["parse_mode"] = val

		val, err = v.SendResolved.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["send_resolved"] = val

		val, err = v.Token.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["token"] = val

		val, err = v.TokenFile.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["token_file"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ConfigTelegramConfigValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ConfigTelegramConfigValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ConfigTelegramConfigValue) String() string {
	return "ConfigTelegramConfigValue"
}

func (v ConfigTelegramConfigValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var httpConfig basetypes.ObjectValue

	if v.HttpConfig.IsNull() {
		httpConfig = types.ObjectNull(
			ConfigHttpclientConfigValue{}.AttributeTypes(ctx),
		)
	}

	if v.HttpConfig.IsUnknown() {
		httpConfig = types.ObjectUnknown(
			ConfigHttpclientConfigValue{}.AttributeTypes(ctx),
		)
	}

	if !v.HttpConfig.IsNull() && !v.HttpConfig.IsUnknown() {
		httpConfig = types.ObjectValueMust(
			ConfigHttpclientConfigValue{}.AttributeTypes(ctx),
			v.HttpConfig.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"api_url":               basetypes.StringType{},
		"chat":                  basetypes.Int64Type{},
		"chat_file":             basetypes.StringType{},
		"disable_notifications": basetypes.BoolType{},
		"http_config": basetypes.ObjectType{
			AttrTypes: ConfigHttpclientConfigValue{}.AttributeTypes(ctx),
		},
		"message":           basetypes.StringType{},
		"message_thread_id": basetypes.Int64Type{},
		"parse_mode":        basetypes.StringType{},
		"send_resolved":     basetypes.BoolType{},
		"token":             basetypes.StringType{},
		"token_file":        basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"api_url":               v.ApiUrl,
			"chat":                  v.Chat,
			"chat_file":             v.ChatFile,
			"disable_notifications": v.DisableNotifications,
			"http_config":           httpConfig,
			"message":               v.Message,
			"message_thread_id":     v.MessageThreadId,
			"parse_mode":            v.ParseMode,
			"send_resolved":         v.SendResolved,
			"token":                 v.Token,
			"token_file":            v.TokenFile,
		})

	return objVal, diags
}

func (v ConfigTelegramConfigValue) Equal(o attr.Value) bool {
	other, ok := o.(ConfigTelegramConfigValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ApiUrl.Equal(other.ApiUrl) {
		return false
	}

	if !v.Chat.Equal(other.Chat) {
		return false
	}

	if !v.ChatFile.Equal(other.ChatFile) {
		return false
	}

	if !v.DisableNotifications.Equal(other.DisableNotifications) {
		return false
	}

	if !v.HttpConfig.Equal(other.HttpConfig) {
		return false
	}

	if !v.Message.Equal(other.Message) {
		return false
	}

	if !v.MessageThreadId.Equal(other.MessageThreadId) {
		return false
	}

	if !v.ParseMode.Equal(other.ParseMode) {
		return false
	}

	if !v.SendResolved.Equal(other.SendResolved) {
		return false
	}

	if !v.Token.Equal(other.Token) {
		return false
	}

	if !v.TokenFile.Equal(other.TokenFile) {
		return false
	}

	return true
}

func (v ConfigTelegramConfigValue) Type(ctx context.Context) attr.Type {
	return ConfigTelegramConfigType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ConfigTelegramConfigValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"api_url":               basetypes.StringType{},
		"chat":                  basetypes.Int64Type{},
		"chat_file":             basetypes.StringType{},
		"disable_notifications": basetypes.BoolType{},
		"http_config": basetypes.ObjectType{
			AttrTypes: ConfigHttpclientConfigValue{}.AttributeTypes(ctx),
		},
		"message":           basetypes.StringType{},
		"message_thread_id": basetypes.Int64Type{},
		"parse_mode":        basetypes.StringType{},
		"send_resolved":     basetypes.BoolType{},
		"token":             basetypes.StringType{},
		"token_file":        basetypes.StringType{},
	}
}
