// Code generated by skaff types DO NOT EDIT.

package types

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
)

var _ basetypes.ObjectTypable = ConfigOpsGenieConfigResponderType{}

type ConfigOpsGenieConfigResponderType struct {
	basetypes.ObjectType
}

func (t ConfigOpsGenieConfigResponderType) Equal(o attr.Type) bool {
	other, ok := o.(ConfigOpsGenieConfigResponderType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ConfigOpsGenieConfigResponderType) String() string {
	return "ConfigOpsGenieConfigResponderType"
}

func (t ConfigOpsGenieConfigResponderType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	type_Attribute, ok := attributes["type_"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type_ is missing from object`)

		return nil, diags
	}

	type_Val, ok := type_Attribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type_ expected to be basetypes.StringValue, was: %T`, type_Attribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return nil, diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ConfigOpsGenieConfigResponderValue{
		Id:       idVal,
		Name:     nameVal,
		Type_:    type_Val,
		Username: usernameVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewConfigOpsGenieConfigResponderValueNull() ConfigOpsGenieConfigResponderValue {
	return ConfigOpsGenieConfigResponderValue{
		state: attr.ValueStateNull,
	}
}

func NewConfigOpsGenieConfigResponderValueUnknown() ConfigOpsGenieConfigResponderValue {
	return ConfigOpsGenieConfigResponderValue{
		state: attr.ValueStateUnknown,
	}
}

func NewConfigOpsGenieConfigResponderValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ConfigOpsGenieConfigResponderValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ConfigOpsGenieConfigResponderValue Attribute Value",
				"While creating a ConfigOpsGenieConfigResponderValue value, a missing attribute value was detected. "+
					"A ConfigOpsGenieConfigResponderValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigOpsGenieConfigResponderValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ConfigOpsGenieConfigResponderValue Attribute Type",
				"While creating a ConfigOpsGenieConfigResponderValue value, an invalid attribute value was detected. "+
					"A ConfigOpsGenieConfigResponderValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigOpsGenieConfigResponderValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ConfigOpsGenieConfigResponderValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ConfigOpsGenieConfigResponderValue Attribute Value",
				"While creating a ConfigOpsGenieConfigResponderValue value, an extra attribute value was detected. "+
					"A ConfigOpsGenieConfigResponderValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ConfigOpsGenieConfigResponderValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewConfigOpsGenieConfigResponderValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewConfigOpsGenieConfigResponderValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewConfigOpsGenieConfigResponderValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	type_Attribute, ok := attributes["type_"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type_ is missing from object`)

		return NewConfigOpsGenieConfigResponderValueUnknown(), diags
	}

	type_Val, ok := type_Attribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type_ expected to be basetypes.StringValue, was: %T`, type_Attribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return NewConfigOpsGenieConfigResponderValueUnknown(), diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	if diags.HasError() {
		return NewConfigOpsGenieConfigResponderValueUnknown(), diags
	}

	return ConfigOpsGenieConfigResponderValue{
		Id:       idVal,
		Name:     nameVal,
		Type_:    type_Val,
		Username: usernameVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewConfigOpsGenieConfigResponderValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ConfigOpsGenieConfigResponderValue {
	object, diags := NewConfigOpsGenieConfigResponderValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewConfigOpsGenieConfigResponderValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ConfigOpsGenieConfigResponderType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewConfigOpsGenieConfigResponderValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewConfigOpsGenieConfigResponderValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigOpsGenieConfigResponderValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewConfigOpsGenieConfigResponderValueMust(ConfigOpsGenieConfigResponderValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ConfigOpsGenieConfigResponderType) ValueType(ctx context.Context) attr.Value {
	return ConfigOpsGenieConfigResponderValue{}
}

var _ basetypes.ObjectValuable = ConfigOpsGenieConfigResponderValue{}

type ConfigOpsGenieConfigResponderValue struct {
	Id       basetypes.StringValue `tfsdk:"id"`
	Name     basetypes.StringValue `tfsdk:"name"`
	Type_    basetypes.StringValue `tfsdk:"type_"`
	Username basetypes.StringValue `tfsdk:"username"`
	state    attr.ValueState
}

func (v ConfigOpsGenieConfigResponderValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type_"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["username"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Type_.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type_"] = val

		val, err = v.Username.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["username"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ConfigOpsGenieConfigResponderValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ConfigOpsGenieConfigResponderValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ConfigOpsGenieConfigResponderValue) String() string {
	return "ConfigOpsGenieConfigResponderValue"
}

func (v ConfigOpsGenieConfigResponderValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":       basetypes.StringType{},
		"name":     basetypes.StringType{},
		"type_":    basetypes.StringType{},
		"username": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":       v.Id,
			"name":     v.Name,
			"type_":    v.Type_,
			"username": v.Username,
		})

	return objVal, diags
}

func (v ConfigOpsGenieConfigResponderValue) Equal(o attr.Value) bool {
	other, ok := o.(ConfigOpsGenieConfigResponderValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Type_.Equal(other.Type_) {
		return false
	}

	if !v.Username.Equal(other.Username) {
		return false
	}

	return true
}

func (v ConfigOpsGenieConfigResponderValue) Type(ctx context.Context) attr.Type {
	return ConfigOpsGenieConfigResponderType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ConfigOpsGenieConfigResponderValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":       basetypes.StringType{},
		"name":     basetypes.StringType{},
		"type_":    basetypes.StringType{},
		"username": basetypes.StringType{},
	}
}
