// Code generated by skaff types DO NOT EDIT.

package types

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
)

var _ basetypes.ObjectTypable = ErrorsResponseretryjsonType{}

type ErrorsResponseretryjsonType struct {
	basetypes.ObjectType
}

func (t ErrorsResponseretryjsonType) Equal(o attr.Type) bool {
	other, ok := o.(ErrorsResponseretryjsonType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ErrorsResponseretryjsonType) String() string {
	return "ErrorsResponseretryjsonType"
}

func (t ErrorsResponseretryjsonType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	delayAttribute, ok := attributes["delay"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`delay is missing from object`)

		return nil, diags
	}

	delayVal, ok := delayAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`delay expected to be basetypes.Int64Value, was: %T`, delayAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ErrorsResponseretryjsonValue{
		Delay: delayVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewErrorsResponseretryjsonValueNull() ErrorsResponseretryjsonValue {
	return ErrorsResponseretryjsonValue{
		state: attr.ValueStateNull,
	}
}

func NewErrorsResponseretryjsonValueUnknown() ErrorsResponseretryjsonValue {
	return ErrorsResponseretryjsonValue{
		state: attr.ValueStateUnknown,
	}
}

func NewErrorsResponseretryjsonValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ErrorsResponseretryjsonValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ErrorsResponseretryjsonValue Attribute Value",
				"While creating a ErrorsResponseretryjsonValue value, a missing attribute value was detected. "+
					"A ErrorsResponseretryjsonValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ErrorsResponseretryjsonValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ErrorsResponseretryjsonValue Attribute Type",
				"While creating a ErrorsResponseretryjsonValue value, an invalid attribute value was detected. "+
					"A ErrorsResponseretryjsonValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ErrorsResponseretryjsonValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ErrorsResponseretryjsonValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ErrorsResponseretryjsonValue Attribute Value",
				"While creating a ErrorsResponseretryjsonValue value, an extra attribute value was detected. "+
					"A ErrorsResponseretryjsonValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ErrorsResponseretryjsonValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewErrorsResponseretryjsonValueUnknown(), diags
	}

	delayAttribute, ok := attributes["delay"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`delay is missing from object`)

		return NewErrorsResponseretryjsonValueUnknown(), diags
	}

	delayVal, ok := delayAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`delay expected to be basetypes.Int64Value, was: %T`, delayAttribute))
	}

	if diags.HasError() {
		return NewErrorsResponseretryjsonValueUnknown(), diags
	}

	return ErrorsResponseretryjsonValue{
		Delay: delayVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewErrorsResponseretryjsonValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ErrorsResponseretryjsonValue {
	object, diags := NewErrorsResponseretryjsonValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewErrorsResponseretryjsonValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ErrorsResponseretryjsonType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewErrorsResponseretryjsonValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewErrorsResponseretryjsonValueUnknown(), nil
	}

	if in.IsNull() {
		return NewErrorsResponseretryjsonValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewErrorsResponseretryjsonValueMust(ErrorsResponseretryjsonValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ErrorsResponseretryjsonType) ValueType(ctx context.Context) attr.Value {
	return ErrorsResponseretryjsonValue{}
}

var _ basetypes.ObjectValuable = ErrorsResponseretryjsonValue{}

type ErrorsResponseretryjsonValue struct {
	Delay basetypes.Int64Value `tfsdk:"delay"`
	state attr.ValueState
}

func (v ErrorsResponseretryjsonValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["delay"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Delay.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["delay"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ErrorsResponseretryjsonValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ErrorsResponseretryjsonValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ErrorsResponseretryjsonValue) String() string {
	return "ErrorsResponseretryjsonValue"
}

func (v ErrorsResponseretryjsonValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"delay": basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"delay": v.Delay,
		})

	return objVal, diags
}

func (v ErrorsResponseretryjsonValue) Equal(o attr.Value) bool {
	other, ok := o.(ErrorsResponseretryjsonValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Delay.Equal(other.Delay) {
		return false
	}

	return true
}

func (v ErrorsResponseretryjsonValue) Type(ctx context.Context) attr.Type {
	return ErrorsResponseretryjsonType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ErrorsResponseretryjsonValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"delay": basetypes.Int64Type{},
	}
}
