// Code generated by skaff types DO NOT EDIT.

package types

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
)

var _ basetypes.ObjectTypable = ConfigSlackFieldType{}

type ConfigSlackFieldType struct {
	basetypes.ObjectType
}

func (t ConfigSlackFieldType) Equal(o attr.Type) bool {
	other, ok := o.(ConfigSlackFieldType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ConfigSlackFieldType) String() string {
	return "ConfigSlackFieldType"
}

func (t ConfigSlackFieldType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	shortAttribute, ok := attributes["short"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`short is missing from object`)

		return nil, diags
	}

	shortVal, ok := shortAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`short expected to be basetypes.BoolValue, was: %T`, shortAttribute))
	}

	titleAttribute, ok := attributes["title"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`title is missing from object`)

		return nil, diags
	}

	titleVal, ok := titleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`title expected to be basetypes.StringValue, was: %T`, titleAttribute))
	}

	valueAttribute, ok := attributes["value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`value is missing from object`)

		return nil, diags
	}

	valueVal, ok := valueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`value expected to be basetypes.StringValue, was: %T`, valueAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ConfigSlackFieldValue{
		Short: shortVal,
		Title: titleVal,
		Value: valueVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewConfigSlackFieldValueNull() ConfigSlackFieldValue {
	return ConfigSlackFieldValue{
		state: attr.ValueStateNull,
	}
}

func NewConfigSlackFieldValueUnknown() ConfigSlackFieldValue {
	return ConfigSlackFieldValue{
		state: attr.ValueStateUnknown,
	}
}

func NewConfigSlackFieldValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ConfigSlackFieldValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ConfigSlackFieldValue Attribute Value",
				"While creating a ConfigSlackFieldValue value, a missing attribute value was detected. "+
					"A ConfigSlackFieldValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigSlackFieldValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ConfigSlackFieldValue Attribute Type",
				"While creating a ConfigSlackFieldValue value, an invalid attribute value was detected. "+
					"A ConfigSlackFieldValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigSlackFieldValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ConfigSlackFieldValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ConfigSlackFieldValue Attribute Value",
				"While creating a ConfigSlackFieldValue value, an extra attribute value was detected. "+
					"A ConfigSlackFieldValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ConfigSlackFieldValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewConfigSlackFieldValueUnknown(), diags
	}

	shortAttribute, ok := attributes["short"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`short is missing from object`)

		return NewConfigSlackFieldValueUnknown(), diags
	}

	shortVal, ok := shortAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`short expected to be basetypes.BoolValue, was: %T`, shortAttribute))
	}

	titleAttribute, ok := attributes["title"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`title is missing from object`)

		return NewConfigSlackFieldValueUnknown(), diags
	}

	titleVal, ok := titleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`title expected to be basetypes.StringValue, was: %T`, titleAttribute))
	}

	valueAttribute, ok := attributes["value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`value is missing from object`)

		return NewConfigSlackFieldValueUnknown(), diags
	}

	valueVal, ok := valueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`value expected to be basetypes.StringValue, was: %T`, valueAttribute))
	}

	if diags.HasError() {
		return NewConfigSlackFieldValueUnknown(), diags
	}

	return ConfigSlackFieldValue{
		Short: shortVal,
		Title: titleVal,
		Value: valueVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewConfigSlackFieldValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ConfigSlackFieldValue {
	object, diags := NewConfigSlackFieldValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewConfigSlackFieldValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ConfigSlackFieldType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewConfigSlackFieldValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewConfigSlackFieldValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigSlackFieldValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewConfigSlackFieldValueMust(ConfigSlackFieldValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ConfigSlackFieldType) ValueType(ctx context.Context) attr.Value {
	return ConfigSlackFieldValue{}
}

var _ basetypes.ObjectValuable = ConfigSlackFieldValue{}

type ConfigSlackFieldValue struct {
	Short basetypes.BoolValue   `tfsdk:"short"`
	Title basetypes.StringValue `tfsdk:"title"`
	Value basetypes.StringValue `tfsdk:"value"`
	state attr.ValueState
}

func (v ConfigSlackFieldValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["short"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["title"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["value"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Short.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["short"] = val

		val, err = v.Title.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["title"] = val

		val, err = v.Value.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["value"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ConfigSlackFieldValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ConfigSlackFieldValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ConfigSlackFieldValue) String() string {
	return "ConfigSlackFieldValue"
}

func (v ConfigSlackFieldValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"short": basetypes.BoolType{},
		"title": basetypes.StringType{},
		"value": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"short": v.Short,
			"title": v.Title,
			"value": v.Value,
		})

	return objVal, diags
}

func (v ConfigSlackFieldValue) Equal(o attr.Value) bool {
	other, ok := o.(ConfigSlackFieldValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Short.Equal(other.Short) {
		return false
	}

	if !v.Title.Equal(other.Title) {
		return false
	}

	if !v.Value.Equal(other.Value) {
		return false
	}

	return true
}

func (v ConfigSlackFieldValue) Type(ctx context.Context) attr.Type {
	return ConfigSlackFieldType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ConfigSlackFieldValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"short": basetypes.BoolType{},
		"title": basetypes.StringType{},
		"value": basetypes.StringType{},
	}
}
