// Code generated by skaff types DO NOT EDIT.

package types

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
)

var _ basetypes.ObjectTypable = ConfigTlsconfigType{}

type ConfigTlsconfigType struct {
	basetypes.ObjectType
}

func (t ConfigTlsconfigType) Equal(o attr.Type) bool {
	other, ok := o.(ConfigTlsconfigType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ConfigTlsconfigType) String() string {
	return "ConfigTlsconfigType"
}

func (t ConfigTlsconfigType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	caAttribute, ok := attributes["ca"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ca is missing from object`)

		return nil, diags
	}

	caVal, ok := caAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ca expected to be basetypes.StringValue, was: %T`, caAttribute))
	}

	caFileAttribute, ok := attributes["ca_file"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ca_file is missing from object`)

		return nil, diags
	}

	caFileVal, ok := caFileAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ca_file expected to be basetypes.StringValue, was: %T`, caFileAttribute))
	}

	caRefAttribute, ok := attributes["ca_ref"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ca_ref is missing from object`)

		return nil, diags
	}

	caRefVal, ok := caRefAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ca_ref expected to be basetypes.StringValue, was: %T`, caRefAttribute))
	}

	certAttribute, ok := attributes["cert"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cert is missing from object`)

		return nil, diags
	}

	certVal, ok := certAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cert expected to be basetypes.StringValue, was: %T`, certAttribute))
	}

	certFileAttribute, ok := attributes["cert_file"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cert_file is missing from object`)

		return nil, diags
	}

	certFileVal, ok := certFileAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cert_file expected to be basetypes.StringValue, was: %T`, certFileAttribute))
	}

	certRefAttribute, ok := attributes["cert_ref"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cert_ref is missing from object`)

		return nil, diags
	}

	certRefVal, ok := certRefAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cert_ref expected to be basetypes.StringValue, was: %T`, certRefAttribute))
	}

	insecureSkipVerifyAttribute, ok := attributes["insecure_skip_verify"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`insecure_skip_verify is missing from object`)

		return nil, diags
	}

	insecureSkipVerifyVal, ok := insecureSkipVerifyAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`insecure_skip_verify expected to be basetypes.BoolValue, was: %T`, insecureSkipVerifyAttribute))
	}

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return nil, diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	keyFileAttribute, ok := attributes["key_file"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key_file is missing from object`)

		return nil, diags
	}

	keyFileVal, ok := keyFileAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key_file expected to be basetypes.StringValue, was: %T`, keyFileAttribute))
	}

	keyRefAttribute, ok := attributes["key_ref"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key_ref is missing from object`)

		return nil, diags
	}

	keyRefVal, ok := keyRefAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key_ref expected to be basetypes.StringValue, was: %T`, keyRefAttribute))
	}

	maxVersionAttribute, ok := attributes["max_version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`max_version is missing from object`)

		return nil, diags
	}

	maxVersionVal, ok := maxVersionAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`max_version expected to be basetypes.Int64Value, was: %T`, maxVersionAttribute))
	}

	minVersionAttribute, ok := attributes["min_version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`min_version is missing from object`)

		return nil, diags
	}

	minVersionVal, ok := minVersionAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`min_version expected to be basetypes.Int64Value, was: %T`, minVersionAttribute))
	}

	serverNameAttribute, ok := attributes["server_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`server_name is missing from object`)

		return nil, diags
	}

	serverNameVal, ok := serverNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`server_name expected to be basetypes.StringValue, was: %T`, serverNameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ConfigTlsconfigValue{
		Ca:                 caVal,
		CaFile:             caFileVal,
		CaRef:              caRefVal,
		Cert:               certVal,
		CertFile:           certFileVal,
		CertRef:            certRefVal,
		InsecureSkipVerify: insecureSkipVerifyVal,
		Key:                keyVal,
		KeyFile:            keyFileVal,
		KeyRef:             keyRefVal,
		MaxVersion:         maxVersionVal,
		MinVersion:         minVersionVal,
		ServerName:         serverNameVal,
		state:              attr.ValueStateKnown,
	}, diags
}

func NewConfigTlsconfigValueNull() ConfigTlsconfigValue {
	return ConfigTlsconfigValue{
		state: attr.ValueStateNull,
	}
}

func NewConfigTlsconfigValueUnknown() ConfigTlsconfigValue {
	return ConfigTlsconfigValue{
		state: attr.ValueStateUnknown,
	}
}

func NewConfigTlsconfigValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ConfigTlsconfigValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ConfigTlsconfigValue Attribute Value",
				"While creating a ConfigTlsconfigValue value, a missing attribute value was detected. "+
					"A ConfigTlsconfigValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigTlsconfigValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ConfigTlsconfigValue Attribute Type",
				"While creating a ConfigTlsconfigValue value, an invalid attribute value was detected. "+
					"A ConfigTlsconfigValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigTlsconfigValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ConfigTlsconfigValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ConfigTlsconfigValue Attribute Value",
				"While creating a ConfigTlsconfigValue value, an extra attribute value was detected. "+
					"A ConfigTlsconfigValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ConfigTlsconfigValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewConfigTlsconfigValueUnknown(), diags
	}

	caAttribute, ok := attributes["ca"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ca is missing from object`)

		return NewConfigTlsconfigValueUnknown(), diags
	}

	caVal, ok := caAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ca expected to be basetypes.StringValue, was: %T`, caAttribute))
	}

	caFileAttribute, ok := attributes["ca_file"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ca_file is missing from object`)

		return NewConfigTlsconfigValueUnknown(), diags
	}

	caFileVal, ok := caFileAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ca_file expected to be basetypes.StringValue, was: %T`, caFileAttribute))
	}

	caRefAttribute, ok := attributes["ca_ref"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ca_ref is missing from object`)

		return NewConfigTlsconfigValueUnknown(), diags
	}

	caRefVal, ok := caRefAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ca_ref expected to be basetypes.StringValue, was: %T`, caRefAttribute))
	}

	certAttribute, ok := attributes["cert"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cert is missing from object`)

		return NewConfigTlsconfigValueUnknown(), diags
	}

	certVal, ok := certAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cert expected to be basetypes.StringValue, was: %T`, certAttribute))
	}

	certFileAttribute, ok := attributes["cert_file"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cert_file is missing from object`)

		return NewConfigTlsconfigValueUnknown(), diags
	}

	certFileVal, ok := certFileAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cert_file expected to be basetypes.StringValue, was: %T`, certFileAttribute))
	}

	certRefAttribute, ok := attributes["cert_ref"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cert_ref is missing from object`)

		return NewConfigTlsconfigValueUnknown(), diags
	}

	certRefVal, ok := certRefAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cert_ref expected to be basetypes.StringValue, was: %T`, certRefAttribute))
	}

	insecureSkipVerifyAttribute, ok := attributes["insecure_skip_verify"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`insecure_skip_verify is missing from object`)

		return NewConfigTlsconfigValueUnknown(), diags
	}

	insecureSkipVerifyVal, ok := insecureSkipVerifyAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`insecure_skip_verify expected to be basetypes.BoolValue, was: %T`, insecureSkipVerifyAttribute))
	}

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return NewConfigTlsconfigValueUnknown(), diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	keyFileAttribute, ok := attributes["key_file"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key_file is missing from object`)

		return NewConfigTlsconfigValueUnknown(), diags
	}

	keyFileVal, ok := keyFileAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key_file expected to be basetypes.StringValue, was: %T`, keyFileAttribute))
	}

	keyRefAttribute, ok := attributes["key_ref"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key_ref is missing from object`)

		return NewConfigTlsconfigValueUnknown(), diags
	}

	keyRefVal, ok := keyRefAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key_ref expected to be basetypes.StringValue, was: %T`, keyRefAttribute))
	}

	maxVersionAttribute, ok := attributes["max_version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`max_version is missing from object`)

		return NewConfigTlsconfigValueUnknown(), diags
	}

	maxVersionVal, ok := maxVersionAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`max_version expected to be basetypes.Int64Value, was: %T`, maxVersionAttribute))
	}

	minVersionAttribute, ok := attributes["min_version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`min_version is missing from object`)

		return NewConfigTlsconfigValueUnknown(), diags
	}

	minVersionVal, ok := minVersionAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`min_version expected to be basetypes.Int64Value, was: %T`, minVersionAttribute))
	}

	serverNameAttribute, ok := attributes["server_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`server_name is missing from object`)

		return NewConfigTlsconfigValueUnknown(), diags
	}

	serverNameVal, ok := serverNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`server_name expected to be basetypes.StringValue, was: %T`, serverNameAttribute))
	}

	if diags.HasError() {
		return NewConfigTlsconfigValueUnknown(), diags
	}

	return ConfigTlsconfigValue{
		Ca:                 caVal,
		CaFile:             caFileVal,
		CaRef:              caRefVal,
		Cert:               certVal,
		CertFile:           certFileVal,
		CertRef:            certRefVal,
		InsecureSkipVerify: insecureSkipVerifyVal,
		Key:                keyVal,
		KeyFile:            keyFileVal,
		KeyRef:             keyRefVal,
		MaxVersion:         maxVersionVal,
		MinVersion:         minVersionVal,
		ServerName:         serverNameVal,
		state:              attr.ValueStateKnown,
	}, diags
}

func NewConfigTlsconfigValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ConfigTlsconfigValue {
	object, diags := NewConfigTlsconfigValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewConfigTlsconfigValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ConfigTlsconfigType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewConfigTlsconfigValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewConfigTlsconfigValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigTlsconfigValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewConfigTlsconfigValueMust(ConfigTlsconfigValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ConfigTlsconfigType) ValueType(ctx context.Context) attr.Value {
	return ConfigTlsconfigValue{}
}

var _ basetypes.ObjectValuable = ConfigTlsconfigValue{}

type ConfigTlsconfigValue struct {
	Ca                 basetypes.StringValue `tfsdk:"ca"`
	CaFile             basetypes.StringValue `tfsdk:"ca_file"`
	CaRef              basetypes.StringValue `tfsdk:"ca_ref"`
	Cert               basetypes.StringValue `tfsdk:"cert"`
	CertFile           basetypes.StringValue `tfsdk:"cert_file"`
	CertRef            basetypes.StringValue `tfsdk:"cert_ref"`
	InsecureSkipVerify basetypes.BoolValue   `tfsdk:"insecure_skip_verify"`
	Key                basetypes.StringValue `tfsdk:"key"`
	KeyFile            basetypes.StringValue `tfsdk:"key_file"`
	KeyRef             basetypes.StringValue `tfsdk:"key_ref"`
	MaxVersion         basetypes.Int64Value  `tfsdk:"max_version"`
	MinVersion         basetypes.Int64Value  `tfsdk:"min_version"`
	ServerName         basetypes.StringValue `tfsdk:"server_name"`
	state              attr.ValueState
}

func (v ConfigTlsconfigValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 13)

	var val tftypes.Value
	var err error

	attrTypes["ca"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["ca_file"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["ca_ref"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["cert"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["cert_file"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["cert_ref"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["insecure_skip_verify"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["key"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["key_file"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["key_ref"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["max_version"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["min_version"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["server_name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 13)

		val, err = v.Ca.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ca"] = val

		val, err = v.CaFile.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ca_file"] = val

		val, err = v.CaRef.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ca_ref"] = val

		val, err = v.Cert.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["cert"] = val

		val, err = v.CertFile.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["cert_file"] = val

		val, err = v.CertRef.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["cert_ref"] = val

		val, err = v.InsecureSkipVerify.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["insecure_skip_verify"] = val

		val, err = v.Key.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["key"] = val

		val, err = v.KeyFile.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["key_file"] = val

		val, err = v.KeyRef.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["key_ref"] = val

		val, err = v.MaxVersion.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["max_version"] = val

		val, err = v.MinVersion.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["min_version"] = val

		val, err = v.ServerName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["server_name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ConfigTlsconfigValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ConfigTlsconfigValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ConfigTlsconfigValue) String() string {
	return "ConfigTlsconfigValue"
}

func (v ConfigTlsconfigValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"ca":                   basetypes.StringType{},
		"ca_file":              basetypes.StringType{},
		"ca_ref":               basetypes.StringType{},
		"cert":                 basetypes.StringType{},
		"cert_file":            basetypes.StringType{},
		"cert_ref":             basetypes.StringType{},
		"insecure_skip_verify": basetypes.BoolType{},
		"key":                  basetypes.StringType{},
		"key_file":             basetypes.StringType{},
		"key_ref":              basetypes.StringType{},
		"max_version":          basetypes.Int64Type{},
		"min_version":          basetypes.Int64Type{},
		"server_name":          basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"ca":                   v.Ca,
			"ca_file":              v.CaFile,
			"ca_ref":               v.CaRef,
			"cert":                 v.Cert,
			"cert_file":            v.CertFile,
			"cert_ref":             v.CertRef,
			"insecure_skip_verify": v.InsecureSkipVerify,
			"key":                  v.Key,
			"key_file":             v.KeyFile,
			"key_ref":              v.KeyRef,
			"max_version":          v.MaxVersion,
			"min_version":          v.MinVersion,
			"server_name":          v.ServerName,
		})

	return objVal, diags
}

func (v ConfigTlsconfigValue) Equal(o attr.Value) bool {
	other, ok := o.(ConfigTlsconfigValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Ca.Equal(other.Ca) {
		return false
	}

	if !v.CaFile.Equal(other.CaFile) {
		return false
	}

	if !v.CaRef.Equal(other.CaRef) {
		return false
	}

	if !v.Cert.Equal(other.Cert) {
		return false
	}

	if !v.CertFile.Equal(other.CertFile) {
		return false
	}

	if !v.CertRef.Equal(other.CertRef) {
		return false
	}

	if !v.InsecureSkipVerify.Equal(other.InsecureSkipVerify) {
		return false
	}

	if !v.Key.Equal(other.Key) {
		return false
	}

	if !v.KeyFile.Equal(other.KeyFile) {
		return false
	}

	if !v.KeyRef.Equal(other.KeyRef) {
		return false
	}

	if !v.MaxVersion.Equal(other.MaxVersion) {
		return false
	}

	if !v.MinVersion.Equal(other.MinVersion) {
		return false
	}

	if !v.ServerName.Equal(other.ServerName) {
		return false
	}

	return true
}

func (v ConfigTlsconfigValue) Type(ctx context.Context) attr.Type {
	return ConfigTlsconfigType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ConfigTlsconfigValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"ca":                   basetypes.StringType{},
		"ca_file":              basetypes.StringType{},
		"ca_ref":               basetypes.StringType{},
		"cert":                 basetypes.StringType{},
		"cert_file":            basetypes.StringType{},
		"cert_ref":             basetypes.StringType{},
		"insecure_skip_verify": basetypes.BoolType{},
		"key":                  basetypes.StringType{},
		"key_file":             basetypes.StringType{},
		"key_ref":              basetypes.StringType{},
		"max_version":          basetypes.Int64Type{},
		"min_version":          basetypes.Int64Type{},
		"server_name":          basetypes.StringType{},
	}
}
