// Code generated by skaff types DO NOT EDIT.

package types

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
)

var _ basetypes.ObjectTypable = ConfigRocketchatConfigType{}

type ConfigRocketchatConfigType struct {
	basetypes.ObjectType
}

func (t ConfigRocketchatConfigType) Equal(o attr.Type) bool {
	other, ok := o.(ConfigRocketchatConfigType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ConfigRocketchatConfigType) String() string {
	return "ConfigRocketchatConfigType"
}

func (t ConfigRocketchatConfigType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	actionsAttribute, ok := attributes["actions"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`actions is missing from object`)

		return nil, diags
	}

	actionsVal, ok := actionsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`actions expected to be basetypes.ListValue, was: %T`, actionsAttribute))
	}

	apiUrlAttribute, ok := attributes["api_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`api_url is missing from object`)

		return nil, diags
	}

	apiUrlVal, ok := apiUrlAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`api_url expected to be basetypes.ObjectValue, was: %T`, apiUrlAttribute))
	}

	channelAttribute, ok := attributes["channel"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`channel is missing from object`)

		return nil, diags
	}

	channelVal, ok := channelAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`channel expected to be basetypes.StringValue, was: %T`, channelAttribute))
	}

	colorAttribute, ok := attributes["color"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`color is missing from object`)

		return nil, diags
	}

	colorVal, ok := colorAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`color expected to be basetypes.StringValue, was: %T`, colorAttribute))
	}

	emojiAttribute, ok := attributes["emoji"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`emoji is missing from object`)

		return nil, diags
	}

	emojiVal, ok := emojiAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`emoji expected to be basetypes.StringValue, was: %T`, emojiAttribute))
	}

	fieldsAttribute, ok := attributes["fields"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`fields is missing from object`)

		return nil, diags
	}

	fieldsVal, ok := fieldsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`fields expected to be basetypes.ListValue, was: %T`, fieldsAttribute))
	}

	httpConfigAttribute, ok := attributes["http_config"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`http_config is missing from object`)

		return nil, diags
	}

	httpConfigVal, ok := httpConfigAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`http_config expected to be basetypes.ObjectValue, was: %T`, httpConfigAttribute))
	}

	iconUrlAttribute, ok := attributes["icon_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`icon_url is missing from object`)

		return nil, diags
	}

	iconUrlVal, ok := iconUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`icon_url expected to be basetypes.StringValue, was: %T`, iconUrlAttribute))
	}

	imageUrlAttribute, ok := attributes["image_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`image_url is missing from object`)

		return nil, diags
	}

	imageUrlVal, ok := imageUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`image_url expected to be basetypes.StringValue, was: %T`, imageUrlAttribute))
	}

	linkNamesAttribute, ok := attributes["link_names"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`link_names is missing from object`)

		return nil, diags
	}

	linkNamesVal, ok := linkNamesAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`link_names expected to be basetypes.BoolValue, was: %T`, linkNamesAttribute))
	}

	sendResolvedAttribute, ok := attributes["send_resolved"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`send_resolved is missing from object`)

		return nil, diags
	}

	sendResolvedVal, ok := sendResolvedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`send_resolved expected to be basetypes.BoolValue, was: %T`, sendResolvedAttribute))
	}

	shortFieldsAttribute, ok := attributes["short_fields"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`short_fields is missing from object`)

		return nil, diags
	}

	shortFieldsVal, ok := shortFieldsAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`short_fields expected to be basetypes.BoolValue, was: %T`, shortFieldsAttribute))
	}

	textAttribute, ok := attributes["text"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`text is missing from object`)

		return nil, diags
	}

	textVal, ok := textAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`text expected to be basetypes.StringValue, was: %T`, textAttribute))
	}

	thumbUrlAttribute, ok := attributes["thumb_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`thumb_url is missing from object`)

		return nil, diags
	}

	thumbUrlVal, ok := thumbUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`thumb_url expected to be basetypes.StringValue, was: %T`, thumbUrlAttribute))
	}

	titleAttribute, ok := attributes["title"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`title is missing from object`)

		return nil, diags
	}

	titleVal, ok := titleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`title expected to be basetypes.StringValue, was: %T`, titleAttribute))
	}

	titleLinkAttribute, ok := attributes["title_link"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`title_link is missing from object`)

		return nil, diags
	}

	titleLinkVal, ok := titleLinkAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`title_link expected to be basetypes.StringValue, was: %T`, titleLinkAttribute))
	}

	tokenAttribute, ok := attributes["token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`token is missing from object`)

		return nil, diags
	}

	tokenVal, ok := tokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`token expected to be basetypes.StringValue, was: %T`, tokenAttribute))
	}

	tokenFileAttribute, ok := attributes["token_file"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`token_file is missing from object`)

		return nil, diags
	}

	tokenFileVal, ok := tokenFileAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`token_file expected to be basetypes.StringValue, was: %T`, tokenFileAttribute))
	}

	tokenIdAttribute, ok := attributes["token_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`token_id is missing from object`)

		return nil, diags
	}

	tokenIdVal, ok := tokenIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`token_id expected to be basetypes.StringValue, was: %T`, tokenIdAttribute))
	}

	tokenIdFileAttribute, ok := attributes["token_id_file"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`token_id_file is missing from object`)

		return nil, diags
	}

	tokenIdFileVal, ok := tokenIdFileAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`token_id_file expected to be basetypes.StringValue, was: %T`, tokenIdFileAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ConfigRocketchatConfigValue{
		Actions:      actionsVal,
		ApiUrl:       apiUrlVal,
		Channel:      channelVal,
		Color:        colorVal,
		Emoji:        emojiVal,
		Fields:       fieldsVal,
		HttpConfig:   httpConfigVal,
		IconUrl:      iconUrlVal,
		ImageUrl:     imageUrlVal,
		LinkNames:    linkNamesVal,
		SendResolved: sendResolvedVal,
		ShortFields:  shortFieldsVal,
		Text:         textVal,
		ThumbUrl:     thumbUrlVal,
		Title:        titleVal,
		TitleLink:    titleLinkVal,
		Token:        tokenVal,
		TokenFile:    tokenFileVal,
		TokenId:      tokenIdVal,
		TokenIdFile:  tokenIdFileVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewConfigRocketchatConfigValueNull() ConfigRocketchatConfigValue {
	return ConfigRocketchatConfigValue{
		state: attr.ValueStateNull,
	}
}

func NewConfigRocketchatConfigValueUnknown() ConfigRocketchatConfigValue {
	return ConfigRocketchatConfigValue{
		state: attr.ValueStateUnknown,
	}
}

func NewConfigRocketchatConfigValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ConfigRocketchatConfigValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ConfigRocketchatConfigValue Attribute Value",
				"While creating a ConfigRocketchatConfigValue value, a missing attribute value was detected. "+
					"A ConfigRocketchatConfigValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigRocketchatConfigValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ConfigRocketchatConfigValue Attribute Type",
				"While creating a ConfigRocketchatConfigValue value, an invalid attribute value was detected. "+
					"A ConfigRocketchatConfigValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ConfigRocketchatConfigValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ConfigRocketchatConfigValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ConfigRocketchatConfigValue Attribute Value",
				"While creating a ConfigRocketchatConfigValue value, an extra attribute value was detected. "+
					"A ConfigRocketchatConfigValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ConfigRocketchatConfigValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewConfigRocketchatConfigValueUnknown(), diags
	}

	actionsAttribute, ok := attributes["actions"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`actions is missing from object`)

		return NewConfigRocketchatConfigValueUnknown(), diags
	}

	actionsVal, ok := actionsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`actions expected to be basetypes.ListValue, was: %T`, actionsAttribute))
	}

	apiUrlAttribute, ok := attributes["api_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`api_url is missing from object`)

		return NewConfigRocketchatConfigValueUnknown(), diags
	}

	apiUrlVal, ok := apiUrlAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`api_url expected to be basetypes.ObjectValue, was: %T`, apiUrlAttribute))
	}

	channelAttribute, ok := attributes["channel"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`channel is missing from object`)

		return NewConfigRocketchatConfigValueUnknown(), diags
	}

	channelVal, ok := channelAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`channel expected to be basetypes.StringValue, was: %T`, channelAttribute))
	}

	colorAttribute, ok := attributes["color"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`color is missing from object`)

		return NewConfigRocketchatConfigValueUnknown(), diags
	}

	colorVal, ok := colorAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`color expected to be basetypes.StringValue, was: %T`, colorAttribute))
	}

	emojiAttribute, ok := attributes["emoji"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`emoji is missing from object`)

		return NewConfigRocketchatConfigValueUnknown(), diags
	}

	emojiVal, ok := emojiAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`emoji expected to be basetypes.StringValue, was: %T`, emojiAttribute))
	}

	fieldsAttribute, ok := attributes["fields"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`fields is missing from object`)

		return NewConfigRocketchatConfigValueUnknown(), diags
	}

	fieldsVal, ok := fieldsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`fields expected to be basetypes.ListValue, was: %T`, fieldsAttribute))
	}

	httpConfigAttribute, ok := attributes["http_config"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`http_config is missing from object`)

		return NewConfigRocketchatConfigValueUnknown(), diags
	}

	httpConfigVal, ok := httpConfigAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`http_config expected to be basetypes.ObjectValue, was: %T`, httpConfigAttribute))
	}

	iconUrlAttribute, ok := attributes["icon_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`icon_url is missing from object`)

		return NewConfigRocketchatConfigValueUnknown(), diags
	}

	iconUrlVal, ok := iconUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`icon_url expected to be basetypes.StringValue, was: %T`, iconUrlAttribute))
	}

	imageUrlAttribute, ok := attributes["image_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`image_url is missing from object`)

		return NewConfigRocketchatConfigValueUnknown(), diags
	}

	imageUrlVal, ok := imageUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`image_url expected to be basetypes.StringValue, was: %T`, imageUrlAttribute))
	}

	linkNamesAttribute, ok := attributes["link_names"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`link_names is missing from object`)

		return NewConfigRocketchatConfigValueUnknown(), diags
	}

	linkNamesVal, ok := linkNamesAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`link_names expected to be basetypes.BoolValue, was: %T`, linkNamesAttribute))
	}

	sendResolvedAttribute, ok := attributes["send_resolved"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`send_resolved is missing from object`)

		return NewConfigRocketchatConfigValueUnknown(), diags
	}

	sendResolvedVal, ok := sendResolvedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`send_resolved expected to be basetypes.BoolValue, was: %T`, sendResolvedAttribute))
	}

	shortFieldsAttribute, ok := attributes["short_fields"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`short_fields is missing from object`)

		return NewConfigRocketchatConfigValueUnknown(), diags
	}

	shortFieldsVal, ok := shortFieldsAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`short_fields expected to be basetypes.BoolValue, was: %T`, shortFieldsAttribute))
	}

	textAttribute, ok := attributes["text"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`text is missing from object`)

		return NewConfigRocketchatConfigValueUnknown(), diags
	}

	textVal, ok := textAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`text expected to be basetypes.StringValue, was: %T`, textAttribute))
	}

	thumbUrlAttribute, ok := attributes["thumb_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`thumb_url is missing from object`)

		return NewConfigRocketchatConfigValueUnknown(), diags
	}

	thumbUrlVal, ok := thumbUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`thumb_url expected to be basetypes.StringValue, was: %T`, thumbUrlAttribute))
	}

	titleAttribute, ok := attributes["title"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`title is missing from object`)

		return NewConfigRocketchatConfigValueUnknown(), diags
	}

	titleVal, ok := titleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`title expected to be basetypes.StringValue, was: %T`, titleAttribute))
	}

	titleLinkAttribute, ok := attributes["title_link"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`title_link is missing from object`)

		return NewConfigRocketchatConfigValueUnknown(), diags
	}

	titleLinkVal, ok := titleLinkAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`title_link expected to be basetypes.StringValue, was: %T`, titleLinkAttribute))
	}

	tokenAttribute, ok := attributes["token"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`token is missing from object`)

		return NewConfigRocketchatConfigValueUnknown(), diags
	}

	tokenVal, ok := tokenAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`token expected to be basetypes.StringValue, was: %T`, tokenAttribute))
	}

	tokenFileAttribute, ok := attributes["token_file"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`token_file is missing from object`)

		return NewConfigRocketchatConfigValueUnknown(), diags
	}

	tokenFileVal, ok := tokenFileAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`token_file expected to be basetypes.StringValue, was: %T`, tokenFileAttribute))
	}

	tokenIdAttribute, ok := attributes["token_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`token_id is missing from object`)

		return NewConfigRocketchatConfigValueUnknown(), diags
	}

	tokenIdVal, ok := tokenIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`token_id expected to be basetypes.StringValue, was: %T`, tokenIdAttribute))
	}

	tokenIdFileAttribute, ok := attributes["token_id_file"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`token_id_file is missing from object`)

		return NewConfigRocketchatConfigValueUnknown(), diags
	}

	tokenIdFileVal, ok := tokenIdFileAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`token_id_file expected to be basetypes.StringValue, was: %T`, tokenIdFileAttribute))
	}

	if diags.HasError() {
		return NewConfigRocketchatConfigValueUnknown(), diags
	}

	return ConfigRocketchatConfigValue{
		Actions:      actionsVal,
		ApiUrl:       apiUrlVal,
		Channel:      channelVal,
		Color:        colorVal,
		Emoji:        emojiVal,
		Fields:       fieldsVal,
		HttpConfig:   httpConfigVal,
		IconUrl:      iconUrlVal,
		ImageUrl:     imageUrlVal,
		LinkNames:    linkNamesVal,
		SendResolved: sendResolvedVal,
		ShortFields:  shortFieldsVal,
		Text:         textVal,
		ThumbUrl:     thumbUrlVal,
		Title:        titleVal,
		TitleLink:    titleLinkVal,
		Token:        tokenVal,
		TokenFile:    tokenFileVal,
		TokenId:      tokenIdVal,
		TokenIdFile:  tokenIdFileVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewConfigRocketchatConfigValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ConfigRocketchatConfigValue {
	object, diags := NewConfigRocketchatConfigValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewConfigRocketchatConfigValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ConfigRocketchatConfigType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewConfigRocketchatConfigValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewConfigRocketchatConfigValueUnknown(), nil
	}

	if in.IsNull() {
		return NewConfigRocketchatConfigValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewConfigRocketchatConfigValueMust(ConfigRocketchatConfigValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ConfigRocketchatConfigType) ValueType(ctx context.Context) attr.Value {
	return ConfigRocketchatConfigValue{}
}

var _ basetypes.ObjectValuable = ConfigRocketchatConfigValue{}

type ConfigRocketchatConfigValue struct {
	Actions      basetypes.ListValue   `tfsdk:"actions"`
	ApiUrl       basetypes.ObjectValue `tfsdk:"api_url"`
	Channel      basetypes.StringValue `tfsdk:"channel"`
	Color        basetypes.StringValue `tfsdk:"color"`
	Emoji        basetypes.StringValue `tfsdk:"emoji"`
	Fields       basetypes.ListValue   `tfsdk:"fields"`
	HttpConfig   basetypes.ObjectValue `tfsdk:"http_config"`
	IconUrl      basetypes.StringValue `tfsdk:"icon_url"`
	ImageUrl     basetypes.StringValue `tfsdk:"image_url"`
	LinkNames    basetypes.BoolValue   `tfsdk:"link_names"`
	SendResolved basetypes.BoolValue   `tfsdk:"send_resolved"`
	ShortFields  basetypes.BoolValue   `tfsdk:"short_fields"`
	Text         basetypes.StringValue `tfsdk:"text"`
	ThumbUrl     basetypes.StringValue `tfsdk:"thumb_url"`
	Title        basetypes.StringValue `tfsdk:"title"`
	TitleLink    basetypes.StringValue `tfsdk:"title_link"`
	Token        basetypes.StringValue `tfsdk:"token"`
	TokenFile    basetypes.StringValue `tfsdk:"token_file"`
	TokenId      basetypes.StringValue `tfsdk:"token_id"`
	TokenIdFile  basetypes.StringValue `tfsdk:"token_id_file"`
	state        attr.ValueState
}

func (v ConfigRocketchatConfigValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 20)

	var val tftypes.Value
	var err error

	attrTypes["actions"] = basetypes.ListType{
		ElemType: ConfigRocketchatAttachmentActionValue{}.Type(ctx),
	}.TerraformType(ctx)
	attrTypes["api_url"] = basetypes.ObjectType{
		AttrTypes: ConfigUrltype2Value{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["channel"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["color"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["emoji"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["fields"] = basetypes.ListType{
		ElemType: ConfigRocketchatAttachmentFieldValue{}.Type(ctx),
	}.TerraformType(ctx)
	attrTypes["http_config"] = basetypes.ObjectType{
		AttrTypes: ConfigHttpclientConfigValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["icon_url"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["image_url"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["link_names"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["send_resolved"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["short_fields"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["text"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["thumb_url"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["title"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["title_link"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["token"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["token_file"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["token_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["token_id_file"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 20)

		val, err = v.Actions.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["actions"] = val

		val, err = v.ApiUrl.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["api_url"] = val

		val, err = v.Channel.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["channel"] = val

		val, err = v.Color.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["color"] = val

		val, err = v.Emoji.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["emoji"] = val

		val, err = v.Fields.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["fields"] = val

		val, err = v.HttpConfig.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["http_config"] = val

		val, err = v.IconUrl.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["icon_url"] = val

		val, err = v.ImageUrl.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["image_url"] = val

		val, err = v.LinkNames.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["link_names"] = val

		val, err = v.SendResolved.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["send_resolved"] = val

		val, err = v.ShortFields.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["short_fields"] = val

		val, err = v.Text.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["text"] = val

		val, err = v.ThumbUrl.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["thumb_url"] = val

		val, err = v.Title.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["title"] = val

		val, err = v.TitleLink.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["title_link"] = val

		val, err = v.Token.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["token"] = val

		val, err = v.TokenFile.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["token_file"] = val

		val, err = v.TokenId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["token_id"] = val

		val, err = v.TokenIdFile.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["token_id_file"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ConfigRocketchatConfigValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ConfigRocketchatConfigValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ConfigRocketchatConfigValue) String() string {
	return "ConfigRocketchatConfigValue"
}

func (v ConfigRocketchatConfigValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	actions := types.ListValueMust(
		ConfigRocketchatAttachmentActionType{
			basetypes.ObjectType{
				AttrTypes: ConfigRocketchatAttachmentActionValue{}.AttributeTypes(ctx),
			},
		},
		v.Actions.Elements(),
	)

	if v.Actions.IsNull() {
		actions = types.ListNull(
			ConfigRocketchatAttachmentActionType{
				basetypes.ObjectType{
					AttrTypes: ConfigRocketchatAttachmentActionValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.Actions.IsUnknown() {
		actions = types.ListUnknown(
			ConfigRocketchatAttachmentActionType{
				basetypes.ObjectType{
					AttrTypes: ConfigRocketchatAttachmentActionValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	var apiUrl basetypes.ObjectValue

	if v.ApiUrl.IsNull() {
		apiUrl = types.ObjectNull(
			ConfigUrltype2Value{}.AttributeTypes(ctx),
		)
	}

	if v.ApiUrl.IsUnknown() {
		apiUrl = types.ObjectUnknown(
			ConfigUrltype2Value{}.AttributeTypes(ctx),
		)
	}

	if !v.ApiUrl.IsNull() && !v.ApiUrl.IsUnknown() {
		apiUrl = types.ObjectValueMust(
			ConfigUrltype2Value{}.AttributeTypes(ctx),
			v.ApiUrl.Attributes(),
		)
	}

	fields := types.ListValueMust(
		ConfigRocketchatAttachmentFieldType{
			basetypes.ObjectType{
				AttrTypes: ConfigRocketchatAttachmentFieldValue{}.AttributeTypes(ctx),
			},
		},
		v.Fields.Elements(),
	)

	if v.Fields.IsNull() {
		fields = types.ListNull(
			ConfigRocketchatAttachmentFieldType{
				basetypes.ObjectType{
					AttrTypes: ConfigRocketchatAttachmentFieldValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.Fields.IsUnknown() {
		fields = types.ListUnknown(
			ConfigRocketchatAttachmentFieldType{
				basetypes.ObjectType{
					AttrTypes: ConfigRocketchatAttachmentFieldValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	var httpConfig basetypes.ObjectValue

	if v.HttpConfig.IsNull() {
		httpConfig = types.ObjectNull(
			ConfigHttpclientConfigValue{}.AttributeTypes(ctx),
		)
	}

	if v.HttpConfig.IsUnknown() {
		httpConfig = types.ObjectUnknown(
			ConfigHttpclientConfigValue{}.AttributeTypes(ctx),
		)
	}

	if !v.HttpConfig.IsNull() && !v.HttpConfig.IsUnknown() {
		httpConfig = types.ObjectValueMust(
			ConfigHttpclientConfigValue{}.AttributeTypes(ctx),
			v.HttpConfig.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"actions": basetypes.ListType{
			ElemType: ConfigRocketchatAttachmentActionValue{}.Type(ctx),
		},
		"api_url": basetypes.ObjectType{
			AttrTypes: ConfigUrltype2Value{}.AttributeTypes(ctx),
		},
		"channel": basetypes.StringType{},
		"color":   basetypes.StringType{},
		"emoji":   basetypes.StringType{},
		"fields": basetypes.ListType{
			ElemType: ConfigRocketchatAttachmentFieldValue{}.Type(ctx),
		},
		"http_config": basetypes.ObjectType{
			AttrTypes: ConfigHttpclientConfigValue{}.AttributeTypes(ctx),
		},
		"icon_url":      basetypes.StringType{},
		"image_url":     basetypes.StringType{},
		"link_names":    basetypes.BoolType{},
		"send_resolved": basetypes.BoolType{},
		"short_fields":  basetypes.BoolType{},
		"text":          basetypes.StringType{},
		"thumb_url":     basetypes.StringType{},
		"title":         basetypes.StringType{},
		"title_link":    basetypes.StringType{},
		"token":         basetypes.StringType{},
		"token_file":    basetypes.StringType{},
		"token_id":      basetypes.StringType{},
		"token_id_file": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"actions":       actions,
			"api_url":       apiUrl,
			"channel":       v.Channel,
			"color":         v.Color,
			"emoji":         v.Emoji,
			"fields":        fields,
			"http_config":   httpConfig,
			"icon_url":      v.IconUrl,
			"image_url":     v.ImageUrl,
			"link_names":    v.LinkNames,
			"send_resolved": v.SendResolved,
			"short_fields":  v.ShortFields,
			"text":          v.Text,
			"thumb_url":     v.ThumbUrl,
			"title":         v.Title,
			"title_link":    v.TitleLink,
			"token":         v.Token,
			"token_file":    v.TokenFile,
			"token_id":      v.TokenId,
			"token_id_file": v.TokenIdFile,
		})

	return objVal, diags
}

func (v ConfigRocketchatConfigValue) Equal(o attr.Value) bool {
	other, ok := o.(ConfigRocketchatConfigValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Actions.Equal(other.Actions) {
		return false
	}

	if !v.ApiUrl.Equal(other.ApiUrl) {
		return false
	}

	if !v.Channel.Equal(other.Channel) {
		return false
	}

	if !v.Color.Equal(other.Color) {
		return false
	}

	if !v.Emoji.Equal(other.Emoji) {
		return false
	}

	if !v.Fields.Equal(other.Fields) {
		return false
	}

	if !v.HttpConfig.Equal(other.HttpConfig) {
		return false
	}

	if !v.IconUrl.Equal(other.IconUrl) {
		return false
	}

	if !v.ImageUrl.Equal(other.ImageUrl) {
		return false
	}

	if !v.LinkNames.Equal(other.LinkNames) {
		return false
	}

	if !v.SendResolved.Equal(other.SendResolved) {
		return false
	}

	if !v.ShortFields.Equal(other.ShortFields) {
		return false
	}

	if !v.Text.Equal(other.Text) {
		return false
	}

	if !v.ThumbUrl.Equal(other.ThumbUrl) {
		return false
	}

	if !v.Title.Equal(other.Title) {
		return false
	}

	if !v.TitleLink.Equal(other.TitleLink) {
		return false
	}

	if !v.Token.Equal(other.Token) {
		return false
	}

	if !v.TokenFile.Equal(other.TokenFile) {
		return false
	}

	if !v.TokenId.Equal(other.TokenId) {
		return false
	}

	if !v.TokenIdFile.Equal(other.TokenIdFile) {
		return false
	}

	return true
}

func (v ConfigRocketchatConfigValue) Type(ctx context.Context) attr.Type {
	return ConfigRocketchatConfigType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ConfigRocketchatConfigValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"actions": basetypes.ListType{
			ElemType: ConfigRocketchatAttachmentActionValue{}.Type(ctx),
		},
		"api_url": basetypes.ObjectType{
			AttrTypes: ConfigUrltype2Value{}.AttributeTypes(ctx),
		},
		"channel": basetypes.StringType{},
		"color":   basetypes.StringType{},
		"emoji":   basetypes.StringType{},
		"fields": basetypes.ListType{
			ElemType: ConfigRocketchatAttachmentFieldValue{}.Type(ctx),
		},
		"http_config": basetypes.ObjectType{
			AttrTypes: ConfigHttpclientConfigValue{}.AttributeTypes(ctx),
		},
		"icon_url":      basetypes.StringType{},
		"image_url":     basetypes.StringType{},
		"link_names":    basetypes.BoolType{},
		"send_resolved": basetypes.BoolType{},
		"short_fields":  basetypes.BoolType{},
		"text":          basetypes.StringType{},
		"thumb_url":     basetypes.StringType{},
		"title":         basetypes.StringType{},
		"title_link":    basetypes.StringType{},
		"token":         basetypes.StringType{},
		"token_file":    basetypes.StringType{},
		"token_id":      basetypes.StringType{},
		"token_id_file": basetypes.StringType{},
	}
}
