// Code generated by skaff types DO NOT EDIT.

package types

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
)

var _ basetypes.ObjectTypable = RuletypesPlannedMaintenanceType{}

type RuletypesPlannedMaintenanceType struct {
	basetypes.ObjectType
}

func (t RuletypesPlannedMaintenanceType) Equal(o attr.Type) bool {
	other, ok := o.(RuletypesPlannedMaintenanceType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t RuletypesPlannedMaintenanceType) String() string {
	return "RuletypesPlannedMaintenanceType"
}

func (t RuletypesPlannedMaintenanceType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	alertIdsAttribute, ok := attributes["alert_ids"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`alert_ids is missing from object`)

		return nil, diags
	}

	alertIdsVal, ok := alertIdsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`alert_ids expected to be basetypes.ListValue, was: %T`, alertIdsAttribute))
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return nil, diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	createdByAttribute, ok := attributes["created_by"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_by is missing from object`)

		return nil, diags
	}

	createdByVal, ok := createdByAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_by expected to be basetypes.StringValue, was: %T`, createdByAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return nil, diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	kindAttribute, ok := attributes["kind"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kind is missing from object`)

		return nil, diags
	}

	kindVal, ok := kindAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kind expected to be basetypes.StringValue, was: %T`, kindAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	scheduleAttribute, ok := attributes["schedule"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`schedule is missing from object`)

		return nil, diags
	}

	scheduleVal, ok := scheduleAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`schedule expected to be basetypes.ObjectValue, was: %T`, scheduleAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return nil, diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return nil, diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	updatedByAttribute, ok := attributes["updated_by"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_by is missing from object`)

		return nil, diags
	}

	updatedByVal, ok := updatedByAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_by expected to be basetypes.StringValue, was: %T`, updatedByAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return RuletypesPlannedMaintenanceValue{
		AlertIds:    alertIdsVal,
		CreatedAt:   createdAtVal,
		CreatedBy:   createdByVal,
		Description: descriptionVal,
		Id:          idVal,
		Kind:        kindVal,
		Name:        nameVal,
		Schedule:    scheduleVal,
		Status:      statusVal,
		UpdatedAt:   updatedAtVal,
		UpdatedBy:   updatedByVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewRuletypesPlannedMaintenanceValueNull() RuletypesPlannedMaintenanceValue {
	return RuletypesPlannedMaintenanceValue{
		state: attr.ValueStateNull,
	}
}

func NewRuletypesPlannedMaintenanceValueUnknown() RuletypesPlannedMaintenanceValue {
	return RuletypesPlannedMaintenanceValue{
		state: attr.ValueStateUnknown,
	}
}

func NewRuletypesPlannedMaintenanceValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (RuletypesPlannedMaintenanceValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing RuletypesPlannedMaintenanceValue Attribute Value",
				"While creating a RuletypesPlannedMaintenanceValue value, a missing attribute value was detected. "+
					"A RuletypesPlannedMaintenanceValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RuletypesPlannedMaintenanceValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid RuletypesPlannedMaintenanceValue Attribute Type",
				"While creating a RuletypesPlannedMaintenanceValue value, an invalid attribute value was detected. "+
					"A RuletypesPlannedMaintenanceValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RuletypesPlannedMaintenanceValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("RuletypesPlannedMaintenanceValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra RuletypesPlannedMaintenanceValue Attribute Value",
				"While creating a RuletypesPlannedMaintenanceValue value, an extra attribute value was detected. "+
					"A RuletypesPlannedMaintenanceValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra RuletypesPlannedMaintenanceValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewRuletypesPlannedMaintenanceValueUnknown(), diags
	}

	alertIdsAttribute, ok := attributes["alert_ids"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`alert_ids is missing from object`)

		return NewRuletypesPlannedMaintenanceValueUnknown(), diags
	}

	alertIdsVal, ok := alertIdsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`alert_ids expected to be basetypes.ListValue, was: %T`, alertIdsAttribute))
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return NewRuletypesPlannedMaintenanceValueUnknown(), diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	createdByAttribute, ok := attributes["created_by"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_by is missing from object`)

		return NewRuletypesPlannedMaintenanceValueUnknown(), diags
	}

	createdByVal, ok := createdByAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_by expected to be basetypes.StringValue, was: %T`, createdByAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return NewRuletypesPlannedMaintenanceValueUnknown(), diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewRuletypesPlannedMaintenanceValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	kindAttribute, ok := attributes["kind"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kind is missing from object`)

		return NewRuletypesPlannedMaintenanceValueUnknown(), diags
	}

	kindVal, ok := kindAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kind expected to be basetypes.StringValue, was: %T`, kindAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewRuletypesPlannedMaintenanceValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	scheduleAttribute, ok := attributes["schedule"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`schedule is missing from object`)

		return NewRuletypesPlannedMaintenanceValueUnknown(), diags
	}

	scheduleVal, ok := scheduleAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`schedule expected to be basetypes.ObjectValue, was: %T`, scheduleAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return NewRuletypesPlannedMaintenanceValueUnknown(), diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return NewRuletypesPlannedMaintenanceValueUnknown(), diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	updatedByAttribute, ok := attributes["updated_by"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_by is missing from object`)

		return NewRuletypesPlannedMaintenanceValueUnknown(), diags
	}

	updatedByVal, ok := updatedByAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_by expected to be basetypes.StringValue, was: %T`, updatedByAttribute))
	}

	if diags.HasError() {
		return NewRuletypesPlannedMaintenanceValueUnknown(), diags
	}

	return RuletypesPlannedMaintenanceValue{
		AlertIds:    alertIdsVal,
		CreatedAt:   createdAtVal,
		CreatedBy:   createdByVal,
		Description: descriptionVal,
		Id:          idVal,
		Kind:        kindVal,
		Name:        nameVal,
		Schedule:    scheduleVal,
		Status:      statusVal,
		UpdatedAt:   updatedAtVal,
		UpdatedBy:   updatedByVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewRuletypesPlannedMaintenanceValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) RuletypesPlannedMaintenanceValue {
	object, diags := NewRuletypesPlannedMaintenanceValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewRuletypesPlannedMaintenanceValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t RuletypesPlannedMaintenanceType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewRuletypesPlannedMaintenanceValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewRuletypesPlannedMaintenanceValueUnknown(), nil
	}

	if in.IsNull() {
		return NewRuletypesPlannedMaintenanceValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewRuletypesPlannedMaintenanceValueMust(RuletypesPlannedMaintenanceValue{}.AttributeTypes(ctx), attributes), nil
}

func (t RuletypesPlannedMaintenanceType) ValueType(ctx context.Context) attr.Value {
	return RuletypesPlannedMaintenanceValue{}
}

var _ basetypes.ObjectValuable = RuletypesPlannedMaintenanceValue{}

type RuletypesPlannedMaintenanceValue struct {
	AlertIds    basetypes.ListValue   `tfsdk:"alert_ids"`
	CreatedAt   basetypes.StringValue `tfsdk:"created_at"`
	CreatedBy   basetypes.StringValue `tfsdk:"created_by"`
	Description basetypes.StringValue `tfsdk:"description"`
	Id          basetypes.StringValue `tfsdk:"id"`
	Kind        basetypes.StringValue `tfsdk:"kind"`
	Name        basetypes.StringValue `tfsdk:"name"`
	Schedule    basetypes.ObjectValue `tfsdk:"schedule"`
	Status      basetypes.StringValue `tfsdk:"status"`
	UpdatedAt   basetypes.StringValue `tfsdk:"updated_at"`
	UpdatedBy   basetypes.StringValue `tfsdk:"updated_by"`
	state       attr.ValueState
}

func (v RuletypesPlannedMaintenanceValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 11)

	var val tftypes.Value
	var err error

	attrTypes["alert_ids"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["created_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["created_by"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["kind"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["schedule"] = basetypes.ObjectType{
		AttrTypes: RuletypesScheduleValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["status"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["updated_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["updated_by"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 11)

		val, err = v.AlertIds.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["alert_ids"] = val

		val, err = v.CreatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_at"] = val

		val, err = v.CreatedBy.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_by"] = val

		val, err = v.Description.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["description"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Kind.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["kind"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Schedule.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["schedule"] = val

		val, err = v.Status.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["status"] = val

		val, err = v.UpdatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["updated_at"] = val

		val, err = v.UpdatedBy.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["updated_by"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v RuletypesPlannedMaintenanceValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v RuletypesPlannedMaintenanceValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v RuletypesPlannedMaintenanceValue) String() string {
	return "RuletypesPlannedMaintenanceValue"
}

func (v RuletypesPlannedMaintenanceValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var schedule basetypes.ObjectValue

	if v.Schedule.IsNull() {
		schedule = types.ObjectNull(
			RuletypesScheduleValue{}.AttributeTypes(ctx),
		)
	}

	if v.Schedule.IsUnknown() {
		schedule = types.ObjectUnknown(
			RuletypesScheduleValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Schedule.IsNull() && !v.Schedule.IsUnknown() {
		schedule = types.ObjectValueMust(
			RuletypesScheduleValue{}.AttributeTypes(ctx),
			v.Schedule.Attributes(),
		)
	}

	var alertIdsVal basetypes.ListValue
	switch {
	case v.AlertIds.IsUnknown():
		alertIdsVal = types.ListUnknown(types.StringType)
	case v.AlertIds.IsNull():
		alertIdsVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		alertIdsVal, d = types.ListValue(types.StringType, v.AlertIds.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"alert_ids": basetypes.ListType{
				ElemType: types.StringType,
			},
			"created_at":  basetypes.StringType{},
			"created_by":  basetypes.StringType{},
			"description": basetypes.StringType{},
			"id":          basetypes.StringType{},
			"kind":        basetypes.StringType{},
			"name":        basetypes.StringType{},
			"schedule": basetypes.ObjectType{
				AttrTypes: RuletypesScheduleValue{}.AttributeTypes(ctx),
			},
			"status":     basetypes.StringType{},
			"updated_at": basetypes.StringType{},
			"updated_by": basetypes.StringType{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"alert_ids": basetypes.ListType{
			ElemType: types.StringType,
		},
		"created_at":  basetypes.StringType{},
		"created_by":  basetypes.StringType{},
		"description": basetypes.StringType{},
		"id":          basetypes.StringType{},
		"kind":        basetypes.StringType{},
		"name":        basetypes.StringType{},
		"schedule": basetypes.ObjectType{
			AttrTypes: RuletypesScheduleValue{}.AttributeTypes(ctx),
		},
		"status":     basetypes.StringType{},
		"updated_at": basetypes.StringType{},
		"updated_by": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"alert_ids":   alertIdsVal,
			"created_at":  v.CreatedAt,
			"created_by":  v.CreatedBy,
			"description": v.Description,
			"id":          v.Id,
			"kind":        v.Kind,
			"name":        v.Name,
			"schedule":    schedule,
			"status":      v.Status,
			"updated_at":  v.UpdatedAt,
			"updated_by":  v.UpdatedBy,
		})

	return objVal, diags
}

func (v RuletypesPlannedMaintenanceValue) Equal(o attr.Value) bool {
	other, ok := o.(RuletypesPlannedMaintenanceValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AlertIds.Equal(other.AlertIds) {
		return false
	}

	if !v.CreatedAt.Equal(other.CreatedAt) {
		return false
	}

	if !v.CreatedBy.Equal(other.CreatedBy) {
		return false
	}

	if !v.Description.Equal(other.Description) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Kind.Equal(other.Kind) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Schedule.Equal(other.Schedule) {
		return false
	}

	if !v.Status.Equal(other.Status) {
		return false
	}

	if !v.UpdatedAt.Equal(other.UpdatedAt) {
		return false
	}

	if !v.UpdatedBy.Equal(other.UpdatedBy) {
		return false
	}

	return true
}

func (v RuletypesPlannedMaintenanceValue) Type(ctx context.Context) attr.Type {
	return RuletypesPlannedMaintenanceType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v RuletypesPlannedMaintenanceValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"alert_ids": basetypes.ListType{
			ElemType: types.StringType,
		},
		"created_at":  basetypes.StringType{},
		"created_by":  basetypes.StringType{},
		"description": basetypes.StringType{},
		"id":          basetypes.StringType{},
		"kind":        basetypes.StringType{},
		"name":        basetypes.StringType{},
		"schedule": basetypes.ObjectType{
			AttrTypes: RuletypesScheduleValue{}.AttributeTypes(ctx),
		},
		"status":     basetypes.StringType{},
		"updated_at": basetypes.StringType{},
		"updated_by": basetypes.StringType{},
	}
}
