// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package schemas

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ServiceAccountRoleDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Required: true,
			},
			"role_id": schema.StringAttribute{
				Computed: true,
			},
			"service_account_id": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type ServiceAccountRoleDataSourceModel struct {
	Id               types.String `tfsdk:"id"`
	RoleId           types.String `tfsdk:"role_id"`
	ServiceAccountId types.String `tfsdk:"service_account_id"`
}
