// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package schemas

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func UserDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"display_name": schema.StringAttribute{
				Computed: true,
			},
			"email": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Required: true,
			},
			"is_root": schema.BoolAttribute{
				Computed: true,
			},
			"org_id": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type UserDataSourceModel struct {
	DisplayName types.String `tfsdk:"display_name"`
	Email       types.String `tfsdk:"email"`
	Id          types.String `tfsdk:"id"`
	IsRoot      types.Bool   `tfsdk:"is_root"`
	OrgId       types.String `tfsdk:"org_id"`
}
