// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package schemas

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ServiceAccountDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"email": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Required: true,
			},
			"name": schema.StringAttribute{
				Computed: true,
			},
			"org_id": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type ServiceAccountDataSourceModel struct {
	Email types.String `tfsdk:"email"`
	Id    types.String `tfsdk:"id"`
	Name  types.String `tfsdk:"name"`
	OrgId types.String `tfsdk:"org_id"`
}
