// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package schemas

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"

	customtypes "github.com/SigNoz/terraform-provider-signoz/internal/types"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ServiceAccountResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"email": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"org_id": schema.StringAttribute{
				Computed: true,
			},
			"service_account_roles": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"created_at": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.StringAttribute{
							Computed: true,
						},
						"role": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"created_at": schema.StringAttribute{
									Computed: true,
								},
								"description": schema.StringAttribute{
									Computed: true,
								},
								"id": schema.StringAttribute{
									Computed: true,
								},
								"name": schema.StringAttribute{
									Computed: true,
								},
								"org_id": schema.StringAttribute{
									Computed: true,
								},
								"type": schema.StringAttribute{
									Computed: true,
								},
								"updated_at": schema.StringAttribute{
									Computed: true,
								},
							},
							CustomType: customtypes.AuthtypesRoleType{
								ObjectType: types.ObjectType{
									AttrTypes: customtypes.AuthtypesRoleValue{}.AttributeTypes(ctx),
								},
							},
							Computed: true,
						},
						"role_id": schema.StringAttribute{
							Computed: true,
						},
						"service_account_id": schema.StringAttribute{
							Computed: true,
						},
						"updated_at": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: customtypes.ServiceaccounttypesServiceAccountRoleType{
						ObjectType: types.ObjectType{
							AttrTypes: customtypes.ServiceaccounttypesServiceAccountRoleValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
		},
	}
}

type ServiceAccountModel struct {
	Email               types.String `tfsdk:"email"`
	Id                  types.String `tfsdk:"id"`
	Name                types.String `tfsdk:"name"`
	OrgId               types.String `tfsdk:"org_id"`
	ServiceAccountRoles types.List   `tfsdk:"service_account_roles"`
}
