// Code generated by skaff convertors DO NOT EDIT.
package conv

import (
	"context"
	"fmt"

	"github.com/SigNoz/terraform-provider-signoz/internal/apitypes"
	"github.com/SigNoz/terraform-provider-signoz/internal/customtypes"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

func ExpandDashboardtypesVariablePlugin(ctx context.Context, v customtypes.DashboardtypesVariablePluginValue) (*apitypes.DashboardtypesVariablePlugin, diag.Diagnostics) {
	var diags diag.Diagnostics
	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}
	var out apitypes.DashboardtypesVariablePlugin

	if !v.CustomVariable.IsNull() && !v.CustomVariable.IsUnknown() {
		typed, d := dashboardtypesVariablePluginVariantGithubComSigNozSignozPkgTypesDashboardtypesCustomVariableSpecValueFromObject(ctx, v.CustomVariable)
		diags.Append(d...)
		member, d := ExpandDashboardtypesVariablePluginVariantGithubComSigNozSignozPkgTypesDashboardtypesCustomVariableSpec(ctx, typed)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if member != nil {
			if err := out.FromDashboardtypesVariablePluginVariantGithubComSigNozSignozPkgTypesDashboardtypesCustomVariableSpec(*member); err != nil {
				diags.AddError("Failed to encode custom_variable union variant", err.Error())
				return nil, diags
			}
		}
		return &out, diags
	}

	if !v.DynamicVariable.IsNull() && !v.DynamicVariable.IsUnknown() {
		typed, d := dashboardtypesVariablePluginVariantGithubComSigNozSignozPkgTypesDashboardtypesDynamicVariableSpecValueFromObject(ctx, v.DynamicVariable)
		diags.Append(d...)
		member, d := ExpandDashboardtypesVariablePluginVariantGithubComSigNozSignozPkgTypesDashboardtypesDynamicVariableSpec(ctx, typed)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if member != nil {
			if err := out.FromDashboardtypesVariablePluginVariantGithubComSigNozSignozPkgTypesDashboardtypesDynamicVariableSpec(*member); err != nil {
				diags.AddError("Failed to encode dynamic_variable union variant", err.Error())
				return nil, diags
			}
		}
		return &out, diags
	}

	if !v.QueryVariable.IsNull() && !v.QueryVariable.IsUnknown() {
		typed, d := dashboardtypesVariablePluginVariantGithubComSigNozSignozPkgTypesDashboardtypesQueryVariableSpecValueFromObject(ctx, v.QueryVariable)
		diags.Append(d...)
		member, d := ExpandDashboardtypesVariablePluginVariantGithubComSigNozSignozPkgTypesDashboardtypesQueryVariableSpec(ctx, typed)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if member != nil {
			if err := out.FromDashboardtypesVariablePluginVariantGithubComSigNozSignozPkgTypesDashboardtypesQueryVariableSpec(*member); err != nil {
				diags.AddError("Failed to encode query_variable union variant", err.Error())
				return nil, diags
			}
		}
		return &out, diags
	}

	return &out, diags
}

func FlattenDashboardtypesVariablePlugin(ctx context.Context, in *apitypes.DashboardtypesVariablePlugin) (customtypes.DashboardtypesVariablePluginValue, diag.Diagnostics) {
	var diags diag.Diagnostics
	if in == nil {
		return customtypes.NewDashboardtypesVariablePluginValueNull(), diags
	}
	attrs := map[string]attr.Value{
		"custom_variable":  basetypes.NewObjectNull(customtypes.DashboardtypesVariablePluginVariantGithubComSigNozSignozPkgTypesDashboardtypesCustomVariableSpecValue{}.AttributeTypes(ctx)),
		"dynamic_variable": basetypes.NewObjectNull(customtypes.DashboardtypesVariablePluginVariantGithubComSigNozSignozPkgTypesDashboardtypesDynamicVariableSpecValue{}.AttributeTypes(ctx)),
		"query_variable":   basetypes.NewObjectNull(customtypes.DashboardtypesVariablePluginVariantGithubComSigNozSignozPkgTypesDashboardtypesQueryVariableSpecValue{}.AttributeTypes(ctx)),
	}
	disc, err := in.ValueByDiscriminator()
	if err != nil {
		diags.AddError("Failed to decode DashboardtypesVariablePlugin union", err.Error())
		return customtypes.NewDashboardtypesVariablePluginValueUnknown(), diags
	}
	switch member := disc.(type) {
	case apitypes.DashboardtypesVariablePluginVariantGithubComSigNozSignozPkgTypesDashboardtypesCustomVariableSpec:
		fv, d := FlattenDashboardtypesVariablePluginVariantGithubComSigNozSignozPkgTypesDashboardtypesCustomVariableSpec(ctx, &member)
		diags.Append(d...)
		ov, d := fv.ToObjectValue(ctx)
		diags.Append(d...)
		attrs["custom_variable"] = ov
	case apitypes.DashboardtypesVariablePluginVariantGithubComSigNozSignozPkgTypesDashboardtypesDynamicVariableSpec:
		fv, d := FlattenDashboardtypesVariablePluginVariantGithubComSigNozSignozPkgTypesDashboardtypesDynamicVariableSpec(ctx, &member)
		diags.Append(d...)
		ov, d := fv.ToObjectValue(ctx)
		diags.Append(d...)
		attrs["dynamic_variable"] = ov
	case apitypes.DashboardtypesVariablePluginVariantGithubComSigNozSignozPkgTypesDashboardtypesQueryVariableSpec:
		fv, d := FlattenDashboardtypesVariablePluginVariantGithubComSigNozSignozPkgTypesDashboardtypesQueryVariableSpec(ctx, &member)
		diags.Append(d...)
		ov, d := fv.ToObjectValue(ctx)
		diags.Append(d...)
		attrs["query_variable"] = ov
	}
	if diags.HasError() {
		return customtypes.NewDashboardtypesVariablePluginValueUnknown(), diags
	}
	rv, d := customtypes.NewDashboardtypesVariablePluginValue(customtypes.DashboardtypesVariablePluginValue{}.AttributeTypes(ctx), attrs)
	diags.Append(d...)
	return rv, diags
}

func ExpandDashboardtypesVariablePluginList(ctx context.Context, l types.List) (*[]apitypes.DashboardtypesVariablePlugin, diag.Diagnostics) {
	var diags diag.Diagnostics
	if l.IsNull() || l.IsUnknown() {
		return nil, diags
	}
	out := make([]apitypes.DashboardtypesVariablePlugin, 0, len(l.Elements()))
	for i, el := range l.Elements() {
		sv, ok := el.(customtypes.DashboardtypesVariablePluginValue)
		if !ok {
			diags.AddError("Unexpected list element type",
				fmt.Sprintf("element %d: expected customtypes.DashboardtypesVariablePluginValue, got %T", i, el))
			return nil, diags
		}
		one, d := ExpandDashboardtypesVariablePlugin(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out = append(out, *one)
		}
	}
	return &out, diags
}

func FlattenDashboardtypesVariablePluginList(ctx context.Context, in *[]apitypes.DashboardtypesVariablePlugin) (types.List, diag.Diagnostics) {
	elemType := customtypes.DashboardtypesVariablePluginValue{}.Type(ctx)
	if in == nil {
		return types.ListNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make([]attr.Value, 0, len(*in))
	for i := range *in {
		sv, d := FlattenDashboardtypesVariablePlugin(ctx, &(*in)[i])
		diags.Append(d...)
		if diags.HasError() {
			return types.ListUnknown(elemType), diags
		}
		elems = append(elems, sv)
	}
	listVal, d := types.ListValue(elemType, elems)
	diags.Append(d...)
	return listVal, diags
}

func ExpandDashboardtypesVariablePluginMap(ctx context.Context, m types.Map) (*map[string]apitypes.DashboardtypesVariablePlugin, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m.IsNull() || m.IsUnknown() {
		return nil, diags
	}
	out := make(map[string]apitypes.DashboardtypesVariablePlugin, len(m.Elements()))
	for k, el := range m.Elements() {
		sv, ok := el.(customtypes.DashboardtypesVariablePluginValue)
		if !ok {
			diags.AddError("Unexpected map element type",
				fmt.Sprintf("element %q: expected customtypes.DashboardtypesVariablePluginValue, got %T", k, el))
			return nil, diags
		}
		one, d := ExpandDashboardtypesVariablePlugin(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out[k] = *one
		}
	}
	return &out, diags
}

func FlattenDashboardtypesVariablePluginMap(ctx context.Context, in *map[string]apitypes.DashboardtypesVariablePlugin) (types.Map, diag.Diagnostics) {
	elemType := customtypes.DashboardtypesVariablePluginValue{}.Type(ctx)
	if in == nil {
		return types.MapNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make(map[string]attr.Value, len(*in))
	for k := range *in {
		v := (*in)[k]
		sv, d := FlattenDashboardtypesVariablePlugin(ctx, &v)
		diags.Append(d...)
		if diags.HasError() {
			return types.MapUnknown(elemType), diags
		}
		elems[k] = sv
	}
	mapVal, d := types.MapValue(elemType, elems)
	diags.Append(d...)
	return mapVal, diags
}

// dashboardtypesVariablePluginValueFromObject lifts the raw basetypes.ObjectValue the
// framework stores for a nested customtype into a typed customtypes.DashboardtypesVariablePluginValue
// (structural cast, no field coercion); package-private, called by parent expanders.
func dashboardtypesVariablePluginValueFromObject(ctx context.Context, ov basetypes.ObjectValue) (customtypes.DashboardtypesVariablePluginValue, diag.Diagnostics) {
	if ov.IsNull() {
		return customtypes.NewDashboardtypesVariablePluginValueNull(), nil
	}
	if ov.IsUnknown() {
		return customtypes.NewDashboardtypesVariablePluginValueUnknown(), nil
	}
	return customtypes.NewDashboardtypesVariablePluginValue(
		customtypes.DashboardtypesVariablePluginValue{}.AttributeTypes(ctx),
		ov.Attributes(),
	)
}
