// Code generated by skaff convertors DO NOT EDIT.
package conv

import (
	"context"
	"fmt"

	"github.com/SigNoz/terraform-provider-signoz/internal/apitypes"
	"github.com/SigNoz/terraform-provider-signoz/internal/convtypes"
	"github.com/SigNoz/terraform-provider-signoz/internal/customtypes"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

func ExpandDashboardtypesLink(ctx context.Context, v customtypes.DashboardtypesLinkValue) (*apitypes.DashboardtypesLink, diag.Diagnostics) {
	var diags diag.Diagnostics
	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	if diags.HasError() {
		return nil, diags
	}
	return &apitypes.DashboardtypesLink{
		Name:            convtypes.StringPointer(v.Name),
		RenderVariables: convtypes.BoolPointer(v.RenderVariables),
		TargetBlank:     convtypes.BoolPointer(v.TargetBlank),
		Tooltip:         convtypes.StringPointer(v.Tooltip),
		Url:             convtypes.StringPointer(v.Url),
	}, diags
}

func FlattenDashboardtypesLink(ctx context.Context, in *apitypes.DashboardtypesLink) (customtypes.DashboardtypesLinkValue, diag.Diagnostics) {
	var diags diag.Diagnostics
	if in == nil {
		return customtypes.NewDashboardtypesLinkValueNull(), diags
	}

	if diags.HasError() {
		return customtypes.NewDashboardtypesLinkValueUnknown(), diags
	}

	rv, d := customtypes.NewDashboardtypesLinkValue(
		customtypes.DashboardtypesLinkValue{}.AttributeTypes(ctx),
		map[string]attr.Value{
			"name":             convtypes.StringFromPointer(in.Name),
			"render_variables": convtypes.BoolFromPointer(in.RenderVariables),
			"target_blank":     convtypes.BoolFromPointer(in.TargetBlank),
			"tooltip":          convtypes.StringFromPointer(in.Tooltip),
			"url":              convtypes.StringFromPointer(in.Url),
		},
	)
	diags.Append(d...)
	return rv, diags
}

func ExpandDashboardtypesLinkList(ctx context.Context, l types.List) (*[]apitypes.DashboardtypesLink, diag.Diagnostics) {
	var diags diag.Diagnostics
	if l.IsNull() || l.IsUnknown() {
		return nil, diags
	}
	out := make([]apitypes.DashboardtypesLink, 0, len(l.Elements()))
	for i, el := range l.Elements() {
		sv, ok := el.(customtypes.DashboardtypesLinkValue)
		if !ok {
			diags.AddError("Unexpected list element type",
				fmt.Sprintf("element %d: expected customtypes.DashboardtypesLinkValue, got %T", i, el))
			return nil, diags
		}
		one, d := ExpandDashboardtypesLink(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out = append(out, *one)
		}
	}
	return &out, diags
}

func FlattenDashboardtypesLinkList(ctx context.Context, in *[]apitypes.DashboardtypesLink) (types.List, diag.Diagnostics) {
	elemType := customtypes.DashboardtypesLinkValue{}.Type(ctx)
	if in == nil {
		return types.ListNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make([]attr.Value, 0, len(*in))
	for i := range *in {
		sv, d := FlattenDashboardtypesLink(ctx, &(*in)[i])
		diags.Append(d...)
		if diags.HasError() {
			return types.ListUnknown(elemType), diags
		}
		elems = append(elems, sv)
	}
	listVal, d := types.ListValue(elemType, elems)
	diags.Append(d...)
	return listVal, diags
}

func ExpandDashboardtypesLinkMap(ctx context.Context, m types.Map) (*map[string]apitypes.DashboardtypesLink, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m.IsNull() || m.IsUnknown() {
		return nil, diags
	}
	out := make(map[string]apitypes.DashboardtypesLink, len(m.Elements()))
	for k, el := range m.Elements() {
		sv, ok := el.(customtypes.DashboardtypesLinkValue)
		if !ok {
			diags.AddError("Unexpected map element type",
				fmt.Sprintf("element %q: expected customtypes.DashboardtypesLinkValue, got %T", k, el))
			return nil, diags
		}
		one, d := ExpandDashboardtypesLink(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out[k] = *one
		}
	}
	return &out, diags
}

func FlattenDashboardtypesLinkMap(ctx context.Context, in *map[string]apitypes.DashboardtypesLink) (types.Map, diag.Diagnostics) {
	elemType := customtypes.DashboardtypesLinkValue{}.Type(ctx)
	if in == nil {
		return types.MapNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make(map[string]attr.Value, len(*in))
	for k := range *in {
		v := (*in)[k]
		sv, d := FlattenDashboardtypesLink(ctx, &v)
		diags.Append(d...)
		if diags.HasError() {
			return types.MapUnknown(elemType), diags
		}
		elems[k] = sv
	}
	mapVal, d := types.MapValue(elemType, elems)
	diags.Append(d...)
	return mapVal, diags
}

// dashboardtypesLinkValueFromObject lifts the raw basetypes.ObjectValue the
// framework stores for a nested customtype into a typed customtypes.DashboardtypesLinkValue
// (structural cast, no field coercion); package-private, called by parent expanders.
func dashboardtypesLinkValueFromObject(ctx context.Context, ov basetypes.ObjectValue) (customtypes.DashboardtypesLinkValue, diag.Diagnostics) {
	if ov.IsNull() {
		return customtypes.NewDashboardtypesLinkValueNull(), nil
	}
	if ov.IsUnknown() {
		return customtypes.NewDashboardtypesLinkValueUnknown(), nil
	}
	return customtypes.NewDashboardtypesLinkValue(
		customtypes.DashboardtypesLinkValue{}.AttributeTypes(ctx),
		ov.Attributes(),
	)
}
