// Code generated by skaff convertors DO NOT EDIT.
package conv

import (
	"context"
	"fmt"

	"github.com/SigNoz/terraform-provider-signoz/internal/apitypes"
	"github.com/SigNoz/terraform-provider-signoz/internal/customtypes"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

func ExpandDashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpec(ctx context.Context, v customtypes.DashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpecValue) (*apitypes.DashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpec, diag.Diagnostics) {
	var diags diag.Diagnostics
	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	specTyped, d := dashboardGridLayoutSpecValueFromObject(ctx, v.Spec)
	diags.Append(d...)
	spec, d := ExpandDashboardGridLayoutSpec(ctx, specTyped)
	diags.Append(d...)
	if diags.HasError() {
		return nil, diags
	}
	out := &apitypes.DashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpec{
		Kind: apitypes.DashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpecKind(v.Kind.ValueString()),
	}
	if spec != nil {
		out.Spec = *spec
	}
	return out, diags
}

func FlattenDashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpec(ctx context.Context, in *apitypes.DashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpec) (customtypes.DashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpecValue, diag.Diagnostics) {
	var diags diag.Diagnostics
	if in == nil {
		return customtypes.NewDashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpecValueNull(), diags
	}

	specFlatTyped, d := FlattenDashboardGridLayoutSpec(ctx, &in.Spec)
	diags.Append(d...)
	specFlat, d := specFlatTyped.ToObjectValue(ctx)
	diags.Append(d...)
	if diags.HasError() {
		return customtypes.NewDashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpecValueUnknown(), diags
	}

	rv, d := customtypes.NewDashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpecValue(
		customtypes.DashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpecValue{}.AttributeTypes(ctx),
		map[string]attr.Value{
			"kind": types.StringValue(string(in.Kind)),
			"spec": specFlat,
		},
	)
	diags.Append(d...)
	return rv, diags
}

func ExpandDashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpecList(ctx context.Context, l types.List) (*[]apitypes.DashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpec, diag.Diagnostics) {
	var diags diag.Diagnostics
	if l.IsNull() || l.IsUnknown() {
		return nil, diags
	}
	out := make([]apitypes.DashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpec, 0, len(l.Elements()))
	for i, el := range l.Elements() {
		sv, ok := el.(customtypes.DashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpecValue)
		if !ok {
			diags.AddError("Unexpected list element type",
				fmt.Sprintf("element %d: expected customtypes.DashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpecValue, got %T", i, el))
			return nil, diags
		}
		one, d := ExpandDashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpec(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out = append(out, *one)
		}
	}
	return &out, diags
}

func FlattenDashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpecList(ctx context.Context, in *[]apitypes.DashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpec) (types.List, diag.Diagnostics) {
	elemType := customtypes.DashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpecValue{}.Type(ctx)
	if in == nil {
		return types.ListNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make([]attr.Value, 0, len(*in))
	for i := range *in {
		sv, d := FlattenDashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpec(ctx, &(*in)[i])
		diags.Append(d...)
		if diags.HasError() {
			return types.ListUnknown(elemType), diags
		}
		elems = append(elems, sv)
	}
	listVal, d := types.ListValue(elemType, elems)
	diags.Append(d...)
	return listVal, diags
}

func ExpandDashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpecMap(ctx context.Context, m types.Map) (*map[string]apitypes.DashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpec, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m.IsNull() || m.IsUnknown() {
		return nil, diags
	}
	out := make(map[string]apitypes.DashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpec, len(m.Elements()))
	for k, el := range m.Elements() {
		sv, ok := el.(customtypes.DashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpecValue)
		if !ok {
			diags.AddError("Unexpected map element type",
				fmt.Sprintf("element %q: expected customtypes.DashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpecValue, got %T", k, el))
			return nil, diags
		}
		one, d := ExpandDashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpec(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out[k] = *one
		}
	}
	return &out, diags
}

func FlattenDashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpecMap(ctx context.Context, in *map[string]apitypes.DashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpec) (types.Map, diag.Diagnostics) {
	elemType := customtypes.DashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpecValue{}.Type(ctx)
	if in == nil {
		return types.MapNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make(map[string]attr.Value, len(*in))
	for k := range *in {
		v := (*in)[k]
		sv, d := FlattenDashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpec(ctx, &v)
		diags.Append(d...)
		if diags.HasError() {
			return types.MapUnknown(elemType), diags
		}
		elems[k] = sv
	}
	mapVal, d := types.MapValue(elemType, elems)
	diags.Append(d...)
	return mapVal, diags
}

// dashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpecValueFromObject lifts the raw basetypes.ObjectValue the
// framework stores for a nested customtype into a typed customtypes.DashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpecValue
// (structural cast, no field coercion); package-private, called by parent expanders.
func dashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpecValueFromObject(ctx context.Context, ov basetypes.ObjectValue) (customtypes.DashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpecValue, diag.Diagnostics) {
	if ov.IsNull() {
		return customtypes.NewDashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpecValueNull(), nil
	}
	if ov.IsUnknown() {
		return customtypes.NewDashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpecValueUnknown(), nil
	}
	return customtypes.NewDashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpecValue(
		customtypes.DashboardtypesLayoutEnvelopeGithubComPersesSpecGoDashboardGridLayoutSpecValue{}.AttributeTypes(ctx),
		ov.Attributes(),
	)
}
