// Code generated by skaff convertors DO NOT EDIT.
package conv

import (
	"context"
	"fmt"

	"github.com/SigNoz/terraform-provider-signoz/internal/apitypes"
	"github.com/SigNoz/terraform-provider-signoz/internal/convtypes"
	"github.com/SigNoz/terraform-provider-signoz/internal/customtypes"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

func ExpandDashboardtypesTableFormatting(ctx context.Context, v customtypes.DashboardtypesTableFormattingValue) (*apitypes.DashboardtypesTableFormatting, diag.Diagnostics) {
	var diags diag.Diagnostics
	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	columnUnits, d := convtypes.StringMapPointerFromMap(ctx, v.ColumnUnits)
	diags.Append(d...)
	var decimalPrecision *apitypes.DashboardtypesPrecisionOption
	if !v.DecimalPrecision.IsNull() && !v.DecimalPrecision.IsUnknown() {
		x := apitypes.DashboardtypesPrecisionOption(v.DecimalPrecision.ValueString())
		decimalPrecision = &x
	}
	if diags.HasError() {
		return nil, diags
	}
	return &apitypes.DashboardtypesTableFormatting{
		ColumnUnits:      columnUnits,
		DecimalPrecision: decimalPrecision,
	}, diags
}

func FlattenDashboardtypesTableFormatting(ctx context.Context, in *apitypes.DashboardtypesTableFormatting) (customtypes.DashboardtypesTableFormattingValue, diag.Diagnostics) {
	var diags diag.Diagnostics
	if in == nil {
		return customtypes.NewDashboardtypesTableFormattingValueNull(), diags
	}

	columnUnitsFlat, d := convtypes.MapFromStringPointerMap(ctx, in.ColumnUnits)
	diags.Append(d...)
	var decimalPrecisionFlat types.String
	if in.DecimalPrecision != nil {
		decimalPrecisionFlat = types.StringValue(string(*in.DecimalPrecision))
	} else {
		decimalPrecisionFlat = types.StringNull()
	}
	if diags.HasError() {
		return customtypes.NewDashboardtypesTableFormattingValueUnknown(), diags
	}

	rv, d := customtypes.NewDashboardtypesTableFormattingValue(
		customtypes.DashboardtypesTableFormattingValue{}.AttributeTypes(ctx),
		map[string]attr.Value{
			"column_units":      columnUnitsFlat,
			"decimal_precision": decimalPrecisionFlat,
		},
	)
	diags.Append(d...)
	return rv, diags
}

func ExpandDashboardtypesTableFormattingList(ctx context.Context, l types.List) (*[]apitypes.DashboardtypesTableFormatting, diag.Diagnostics) {
	var diags diag.Diagnostics
	if l.IsNull() || l.IsUnknown() {
		return nil, diags
	}
	out := make([]apitypes.DashboardtypesTableFormatting, 0, len(l.Elements()))
	for i, el := range l.Elements() {
		sv, ok := el.(customtypes.DashboardtypesTableFormattingValue)
		if !ok {
			diags.AddError("Unexpected list element type",
				fmt.Sprintf("element %d: expected customtypes.DashboardtypesTableFormattingValue, got %T", i, el))
			return nil, diags
		}
		one, d := ExpandDashboardtypesTableFormatting(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out = append(out, *one)
		}
	}
	return &out, diags
}

func FlattenDashboardtypesTableFormattingList(ctx context.Context, in *[]apitypes.DashboardtypesTableFormatting) (types.List, diag.Diagnostics) {
	elemType := customtypes.DashboardtypesTableFormattingValue{}.Type(ctx)
	if in == nil {
		return types.ListNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make([]attr.Value, 0, len(*in))
	for i := range *in {
		sv, d := FlattenDashboardtypesTableFormatting(ctx, &(*in)[i])
		diags.Append(d...)
		if diags.HasError() {
			return types.ListUnknown(elemType), diags
		}
		elems = append(elems, sv)
	}
	listVal, d := types.ListValue(elemType, elems)
	diags.Append(d...)
	return listVal, diags
}

func ExpandDashboardtypesTableFormattingMap(ctx context.Context, m types.Map) (*map[string]apitypes.DashboardtypesTableFormatting, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m.IsNull() || m.IsUnknown() {
		return nil, diags
	}
	out := make(map[string]apitypes.DashboardtypesTableFormatting, len(m.Elements()))
	for k, el := range m.Elements() {
		sv, ok := el.(customtypes.DashboardtypesTableFormattingValue)
		if !ok {
			diags.AddError("Unexpected map element type",
				fmt.Sprintf("element %q: expected customtypes.DashboardtypesTableFormattingValue, got %T", k, el))
			return nil, diags
		}
		one, d := ExpandDashboardtypesTableFormatting(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out[k] = *one
		}
	}
	return &out, diags
}

func FlattenDashboardtypesTableFormattingMap(ctx context.Context, in *map[string]apitypes.DashboardtypesTableFormatting) (types.Map, diag.Diagnostics) {
	elemType := customtypes.DashboardtypesTableFormattingValue{}.Type(ctx)
	if in == nil {
		return types.MapNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make(map[string]attr.Value, len(*in))
	for k := range *in {
		v := (*in)[k]
		sv, d := FlattenDashboardtypesTableFormatting(ctx, &v)
		diags.Append(d...)
		if diags.HasError() {
			return types.MapUnknown(elemType), diags
		}
		elems[k] = sv
	}
	mapVal, d := types.MapValue(elemType, elems)
	diags.Append(d...)
	return mapVal, diags
}

// dashboardtypesTableFormattingValueFromObject lifts the raw basetypes.ObjectValue the
// framework stores for a nested customtype into a typed customtypes.DashboardtypesTableFormattingValue
// (structural cast, no field coercion); package-private, called by parent expanders.
func dashboardtypesTableFormattingValueFromObject(ctx context.Context, ov basetypes.ObjectValue) (customtypes.DashboardtypesTableFormattingValue, diag.Diagnostics) {
	if ov.IsNull() {
		return customtypes.NewDashboardtypesTableFormattingValueNull(), nil
	}
	if ov.IsUnknown() {
		return customtypes.NewDashboardtypesTableFormattingValueUnknown(), nil
	}
	return customtypes.NewDashboardtypesTableFormattingValue(
		customtypes.DashboardtypesTableFormattingValue{}.AttributeTypes(ctx),
		ov.Attributes(),
	)
}
