// Code generated by skaff convertors DO NOT EDIT.
package conv

import (
	"context"
	"fmt"

	"github.com/SigNoz/terraform-provider-signoz/internal/apitypes"
	"github.com/SigNoz/terraform-provider-signoz/internal/customtypes"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

func ExpandAlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfig(ctx context.Context, v customtypes.AlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfigValue) (*apitypes.AlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfig, diag.Diagnostics) {
	var diags diag.Diagnostics
	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	specTyped, d := alertmanagertypesChannelPagerdutyConfigValueFromObject(ctx, v.Spec)
	diags.Append(d...)
	spec, d := ExpandAlertmanagertypesChannelPagerdutyConfig(ctx, specTyped)
	diags.Append(d...)
	if diags.HasError() {
		return nil, diags
	}
	out := &apitypes.AlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfig{
		Kind: apitypes.AlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfigKind(v.Kind.ValueString()),
	}
	if spec != nil {
		out.Spec = *spec
	}
	return out, diags
}

func FlattenAlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfig(ctx context.Context, in *apitypes.AlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfig) (customtypes.AlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfigValue, diag.Diagnostics) {
	var diags diag.Diagnostics
	if in == nil {
		return customtypes.NewAlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfigValueNull(), diags
	}

	specFlatTyped, d := FlattenAlertmanagertypesChannelPagerdutyConfig(ctx, &in.Spec)
	diags.Append(d...)
	specFlat, d := specFlatTyped.ToObjectValue(ctx)
	diags.Append(d...)
	if diags.HasError() {
		return customtypes.NewAlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfigValueUnknown(), diags
	}

	rv, d := customtypes.NewAlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfigValue(
		customtypes.AlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfigValue{}.AttributeTypes(ctx),
		map[string]attr.Value{
			"kind": types.StringValue(string(in.Kind)),
			"spec": specFlat,
		},
	)
	diags.Append(d...)
	return rv, diags
}

func ExpandAlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfigList(ctx context.Context, l types.List) (*[]apitypes.AlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfig, diag.Diagnostics) {
	var diags diag.Diagnostics
	if l.IsNull() || l.IsUnknown() {
		return nil, diags
	}
	out := make([]apitypes.AlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfig, 0, len(l.Elements()))
	for i, el := range l.Elements() {
		sv, ok := el.(customtypes.AlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfigValue)
		if !ok {
			diags.AddError("Unexpected list element type",
				fmt.Sprintf("element %d: expected customtypes.AlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfigValue, got %T", i, el))
			return nil, diags
		}
		one, d := ExpandAlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfig(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out = append(out, *one)
		}
	}
	return &out, diags
}

func FlattenAlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfigList(ctx context.Context, in *[]apitypes.AlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfig) (types.List, diag.Diagnostics) {
	elemType := customtypes.AlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfigValue{}.Type(ctx)
	if in == nil {
		return types.ListNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make([]attr.Value, 0, len(*in))
	for i := range *in {
		sv, d := FlattenAlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfig(ctx, &(*in)[i])
		diags.Append(d...)
		if diags.HasError() {
			return types.ListUnknown(elemType), diags
		}
		elems = append(elems, sv)
	}
	listVal, d := types.ListValue(elemType, elems)
	diags.Append(d...)
	return listVal, diags
}

func ExpandAlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfigMap(ctx context.Context, m types.Map) (*map[string]apitypes.AlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfig, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m.IsNull() || m.IsUnknown() {
		return nil, diags
	}
	out := make(map[string]apitypes.AlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfig, len(m.Elements()))
	for k, el := range m.Elements() {
		sv, ok := el.(customtypes.AlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfigValue)
		if !ok {
			diags.AddError("Unexpected map element type",
				fmt.Sprintf("element %q: expected customtypes.AlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfigValue, got %T", k, el))
			return nil, diags
		}
		one, d := ExpandAlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfig(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out[k] = *one
		}
	}
	return &out, diags
}

func FlattenAlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfigMap(ctx context.Context, in *map[string]apitypes.AlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfig) (types.Map, diag.Diagnostics) {
	elemType := customtypes.AlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfigValue{}.Type(ctx)
	if in == nil {
		return types.MapNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make(map[string]attr.Value, len(*in))
	for k := range *in {
		v := (*in)[k]
		sv, d := FlattenAlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfig(ctx, &v)
		diags.Append(d...)
		if diags.HasError() {
			return types.MapUnknown(elemType), diags
		}
		elems[k] = sv
	}
	mapVal, d := types.MapValue(elemType, elems)
	diags.Append(d...)
	return mapVal, diags
}

// alertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfigValueFromObject lifts the raw basetypes.ObjectValue the
// framework stores for a nested customtype into a typed customtypes.AlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfigValue
// (structural cast, no field coercion); package-private, called by parent expanders.
func alertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfigValueFromObject(ctx context.Context, ov basetypes.ObjectValue) (customtypes.AlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfigValue, diag.Diagnostics) {
	if ov.IsNull() {
		return customtypes.NewAlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfigValueNull(), nil
	}
	if ov.IsUnknown() {
		return customtypes.NewAlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfigValueUnknown(), nil
	}
	return customtypes.NewAlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfigValue(
		customtypes.AlertmanagertypesChannelConfigVariantGithubComSigNozSignozPkgTypesAlertmanagertypesChannelPagerdutyConfigValue{}.AttributeTypes(ctx),
		ov.Attributes(),
	)
}
