// Code generated by skaff convertors DO NOT EDIT.
package conv

import (
	"context"
	"fmt"

	"github.com/SigNoz/terraform-provider-signoz/internal/apitypes"
	"github.com/SigNoz/terraform-provider-signoz/internal/customtypes"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

func ExpandDashboardtypesHistogramPanelSpec(ctx context.Context, v customtypes.DashboardtypesHistogramPanelSpecValue) (*apitypes.DashboardtypesHistogramPanelSpec, diag.Diagnostics) {
	var diags diag.Diagnostics
	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	histogramBucketsTyped, d := dashboardtypesHistogramBucketsValueFromObject(ctx, v.HistogramBuckets)
	diags.Append(d...)
	histogramBuckets, d := ExpandDashboardtypesHistogramBuckets(ctx, histogramBucketsTyped)
	diags.Append(d...)
	legendTyped, d := dashboardtypesLegendValueFromObject(ctx, v.Legend)
	diags.Append(d...)
	legend, d := ExpandDashboardtypesLegend(ctx, legendTyped)
	diags.Append(d...)
	if diags.HasError() {
		return nil, diags
	}
	return &apitypes.DashboardtypesHistogramPanelSpec{
		HistogramBuckets: histogramBuckets,
		Legend:           legend,
	}, diags
}

func FlattenDashboardtypesHistogramPanelSpec(ctx context.Context, in *apitypes.DashboardtypesHistogramPanelSpec) (customtypes.DashboardtypesHistogramPanelSpecValue, diag.Diagnostics) {
	var diags diag.Diagnostics
	if in == nil {
		return customtypes.NewDashboardtypesHistogramPanelSpecValueNull(), diags
	}

	histogramBucketsFlatTyped, d := FlattenDashboardtypesHistogramBuckets(ctx, in.HistogramBuckets)
	diags.Append(d...)
	histogramBucketsFlat, d := histogramBucketsFlatTyped.ToObjectValue(ctx)
	diags.Append(d...)
	legendFlatTyped, d := FlattenDashboardtypesLegend(ctx, in.Legend)
	diags.Append(d...)
	legendFlat, d := legendFlatTyped.ToObjectValue(ctx)
	diags.Append(d...)
	if diags.HasError() {
		return customtypes.NewDashboardtypesHistogramPanelSpecValueUnknown(), diags
	}

	rv, d := customtypes.NewDashboardtypesHistogramPanelSpecValue(
		customtypes.DashboardtypesHistogramPanelSpecValue{}.AttributeTypes(ctx),
		map[string]attr.Value{
			"histogram_buckets": histogramBucketsFlat,
			"legend":            legendFlat,
		},
	)
	diags.Append(d...)
	return rv, diags
}

func ExpandDashboardtypesHistogramPanelSpecList(ctx context.Context, l types.List) (*[]apitypes.DashboardtypesHistogramPanelSpec, diag.Diagnostics) {
	var diags diag.Diagnostics
	if l.IsNull() || l.IsUnknown() {
		return nil, diags
	}
	out := make([]apitypes.DashboardtypesHistogramPanelSpec, 0, len(l.Elements()))
	for i, el := range l.Elements() {
		sv, ok := el.(customtypes.DashboardtypesHistogramPanelSpecValue)
		if !ok {
			diags.AddError("Unexpected list element type",
				fmt.Sprintf("element %d: expected customtypes.DashboardtypesHistogramPanelSpecValue, got %T", i, el))
			return nil, diags
		}
		one, d := ExpandDashboardtypesHistogramPanelSpec(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out = append(out, *one)
		}
	}
	return &out, diags
}

func FlattenDashboardtypesHistogramPanelSpecList(ctx context.Context, in *[]apitypes.DashboardtypesHistogramPanelSpec) (types.List, diag.Diagnostics) {
	elemType := customtypes.DashboardtypesHistogramPanelSpecValue{}.Type(ctx)
	if in == nil {
		return types.ListNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make([]attr.Value, 0, len(*in))
	for i := range *in {
		sv, d := FlattenDashboardtypesHistogramPanelSpec(ctx, &(*in)[i])
		diags.Append(d...)
		if diags.HasError() {
			return types.ListUnknown(elemType), diags
		}
		elems = append(elems, sv)
	}
	listVal, d := types.ListValue(elemType, elems)
	diags.Append(d...)
	return listVal, diags
}

func ExpandDashboardtypesHistogramPanelSpecMap(ctx context.Context, m types.Map) (*map[string]apitypes.DashboardtypesHistogramPanelSpec, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m.IsNull() || m.IsUnknown() {
		return nil, diags
	}
	out := make(map[string]apitypes.DashboardtypesHistogramPanelSpec, len(m.Elements()))
	for k, el := range m.Elements() {
		sv, ok := el.(customtypes.DashboardtypesHistogramPanelSpecValue)
		if !ok {
			diags.AddError("Unexpected map element type",
				fmt.Sprintf("element %q: expected customtypes.DashboardtypesHistogramPanelSpecValue, got %T", k, el))
			return nil, diags
		}
		one, d := ExpandDashboardtypesHistogramPanelSpec(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out[k] = *one
		}
	}
	return &out, diags
}

func FlattenDashboardtypesHistogramPanelSpecMap(ctx context.Context, in *map[string]apitypes.DashboardtypesHistogramPanelSpec) (types.Map, diag.Diagnostics) {
	elemType := customtypes.DashboardtypesHistogramPanelSpecValue{}.Type(ctx)
	if in == nil {
		return types.MapNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make(map[string]attr.Value, len(*in))
	for k := range *in {
		v := (*in)[k]
		sv, d := FlattenDashboardtypesHistogramPanelSpec(ctx, &v)
		diags.Append(d...)
		if diags.HasError() {
			return types.MapUnknown(elemType), diags
		}
		elems[k] = sv
	}
	mapVal, d := types.MapValue(elemType, elems)
	diags.Append(d...)
	return mapVal, diags
}

// dashboardtypesHistogramPanelSpecValueFromObject lifts the raw basetypes.ObjectValue the
// framework stores for a nested customtype into a typed customtypes.DashboardtypesHistogramPanelSpecValue
// (structural cast, no field coercion); package-private, called by parent expanders.
func dashboardtypesHistogramPanelSpecValueFromObject(ctx context.Context, ov basetypes.ObjectValue) (customtypes.DashboardtypesHistogramPanelSpecValue, diag.Diagnostics) {
	if ov.IsNull() {
		return customtypes.NewDashboardtypesHistogramPanelSpecValueNull(), nil
	}
	if ov.IsUnknown() {
		return customtypes.NewDashboardtypesHistogramPanelSpecValueUnknown(), nil
	}
	return customtypes.NewDashboardtypesHistogramPanelSpecValue(
		customtypes.DashboardtypesHistogramPanelSpecValue{}.AttributeTypes(ctx),
		ov.Attributes(),
	)
}
