// Code generated by skaff convertors DO NOT EDIT.
package conv

import (
	"context"
	"fmt"

	"github.com/SigNoz/terraform-provider-signoz/internal/apitypes"
	"github.com/SigNoz/terraform-provider-signoz/internal/customtypes"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

func ExpandQuerybuildertypesv5QueryEnvelopePromQL(ctx context.Context, v customtypes.Querybuildertypesv5QueryEnvelopePromQlValue) (*apitypes.Querybuildertypesv5QueryEnvelopePromQL, diag.Diagnostics) {
	var diags diag.Diagnostics
	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	specTyped, d := querybuildertypesv5PromQueryValueFromObject(ctx, v.Spec)
	diags.Append(d...)
	spec, d := ExpandQuerybuildertypesv5PromQuery(ctx, specTyped)
	diags.Append(d...)
	if diags.HasError() {
		return nil, diags
	}
	return &apitypes.Querybuildertypesv5QueryEnvelopePromQL{
		Spec: spec,
		Type: apitypes.Querybuildertypesv5QueryType(v.Querybuildertypesv5QueryEnvelopePromQlType.ValueString()),
	}, diags
}

func FlattenQuerybuildertypesv5QueryEnvelopePromQL(ctx context.Context, in *apitypes.Querybuildertypesv5QueryEnvelopePromQL) (customtypes.Querybuildertypesv5QueryEnvelopePromQlValue, diag.Diagnostics) {
	var diags diag.Diagnostics
	if in == nil {
		return customtypes.NewQuerybuildertypesv5QueryEnvelopePromQlValueNull(), diags
	}

	specFlatTyped, d := FlattenQuerybuildertypesv5PromQuery(ctx, in.Spec)
	diags.Append(d...)
	specFlat, d := specFlatTyped.ToObjectValue(ctx)
	diags.Append(d...)
	if diags.HasError() {
		return customtypes.NewQuerybuildertypesv5QueryEnvelopePromQlValueUnknown(), diags
	}

	rv, d := customtypes.NewQuerybuildertypesv5QueryEnvelopePromQlValue(
		customtypes.Querybuildertypesv5QueryEnvelopePromQlValue{}.AttributeTypes(ctx),
		map[string]attr.Value{
			"spec": specFlat,
			"type": types.StringValue(string(in.Type)),
		},
	)
	diags.Append(d...)
	return rv, diags
}

func ExpandQuerybuildertypesv5QueryEnvelopePromQLList(ctx context.Context, l types.List) (*[]apitypes.Querybuildertypesv5QueryEnvelopePromQL, diag.Diagnostics) {
	var diags diag.Diagnostics
	if l.IsNull() || l.IsUnknown() {
		return nil, diags
	}
	out := make([]apitypes.Querybuildertypesv5QueryEnvelopePromQL, 0, len(l.Elements()))
	for i, el := range l.Elements() {
		sv, ok := el.(customtypes.Querybuildertypesv5QueryEnvelopePromQlValue)
		if !ok {
			diags.AddError("Unexpected list element type",
				fmt.Sprintf("element %d: expected customtypes.Querybuildertypesv5QueryEnvelopePromQlValue, got %T", i, el))
			return nil, diags
		}
		one, d := ExpandQuerybuildertypesv5QueryEnvelopePromQL(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out = append(out, *one)
		}
	}
	return &out, diags
}

func FlattenQuerybuildertypesv5QueryEnvelopePromQLList(ctx context.Context, in *[]apitypes.Querybuildertypesv5QueryEnvelopePromQL) (types.List, diag.Diagnostics) {
	elemType := customtypes.Querybuildertypesv5QueryEnvelopePromQlValue{}.Type(ctx)
	if in == nil {
		return types.ListNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make([]attr.Value, 0, len(*in))
	for i := range *in {
		sv, d := FlattenQuerybuildertypesv5QueryEnvelopePromQL(ctx, &(*in)[i])
		diags.Append(d...)
		if diags.HasError() {
			return types.ListUnknown(elemType), diags
		}
		elems = append(elems, sv)
	}
	listVal, d := types.ListValue(elemType, elems)
	diags.Append(d...)
	return listVal, diags
}

func ExpandQuerybuildertypesv5QueryEnvelopePromQLMap(ctx context.Context, m types.Map) (*map[string]apitypes.Querybuildertypesv5QueryEnvelopePromQL, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m.IsNull() || m.IsUnknown() {
		return nil, diags
	}
	out := make(map[string]apitypes.Querybuildertypesv5QueryEnvelopePromQL, len(m.Elements()))
	for k, el := range m.Elements() {
		sv, ok := el.(customtypes.Querybuildertypesv5QueryEnvelopePromQlValue)
		if !ok {
			diags.AddError("Unexpected map element type",
				fmt.Sprintf("element %q: expected customtypes.Querybuildertypesv5QueryEnvelopePromQlValue, got %T", k, el))
			return nil, diags
		}
		one, d := ExpandQuerybuildertypesv5QueryEnvelopePromQL(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out[k] = *one
		}
	}
	return &out, diags
}

func FlattenQuerybuildertypesv5QueryEnvelopePromQLMap(ctx context.Context, in *map[string]apitypes.Querybuildertypesv5QueryEnvelopePromQL) (types.Map, diag.Diagnostics) {
	elemType := customtypes.Querybuildertypesv5QueryEnvelopePromQlValue{}.Type(ctx)
	if in == nil {
		return types.MapNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make(map[string]attr.Value, len(*in))
	for k := range *in {
		v := (*in)[k]
		sv, d := FlattenQuerybuildertypesv5QueryEnvelopePromQL(ctx, &v)
		diags.Append(d...)
		if diags.HasError() {
			return types.MapUnknown(elemType), diags
		}
		elems[k] = sv
	}
	mapVal, d := types.MapValue(elemType, elems)
	diags.Append(d...)
	return mapVal, diags
}

// querybuildertypesv5QueryEnvelopePromQLValueFromObject lifts the raw basetypes.ObjectValue the
// framework stores for a nested customtype into a typed customtypes.Querybuildertypesv5QueryEnvelopePromQlValue
// (structural cast, no field coercion); package-private, called by parent expanders.
func querybuildertypesv5QueryEnvelopePromQLValueFromObject(ctx context.Context, ov basetypes.ObjectValue) (customtypes.Querybuildertypesv5QueryEnvelopePromQlValue, diag.Diagnostics) {
	if ov.IsNull() {
		return customtypes.NewQuerybuildertypesv5QueryEnvelopePromQlValueNull(), nil
	}
	if ov.IsUnknown() {
		return customtypes.NewQuerybuildertypesv5QueryEnvelopePromQlValueUnknown(), nil
	}
	return customtypes.NewQuerybuildertypesv5QueryEnvelopePromQlValue(
		customtypes.Querybuildertypesv5QueryEnvelopePromQlValue{}.AttributeTypes(ctx),
		ov.Attributes(),
	)
}
