// Code generated by skaff convertors DO NOT EDIT.
package conv

import (
	"context"
	"fmt"

	"github.com/SigNoz/terraform-provider-signoz/internal/apitypes"
	"github.com/SigNoz/terraform-provider-signoz/internal/convtypes"
	"github.com/SigNoz/terraform-provider-signoz/internal/customtypes"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

func ExpandQuerybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregation(ctx context.Context, v customtypes.Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregationValue) (*apitypes.Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregation, diag.Diagnostics) {
	var diags diag.Diagnostics
	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	aggregations, d := ExpandQuerybuildertypesv5LogAggregationList(ctx, v.Aggregations)
	diags.Append(d...)
	filterTyped, d := querybuildertypesv5FilterValueFromObject(ctx, v.Filter)
	diags.Append(d...)
	filter, d := ExpandQuerybuildertypesv5Filter(ctx, filterTyped)
	diags.Append(d...)
	functions, d := ExpandQuerybuildertypesv5FunctionList(ctx, v.Functions)
	diags.Append(d...)
	groupBy, d := ExpandQuerybuildertypesv5GroupByKeyList(ctx, v.GroupBy)
	diags.Append(d...)
	havingTyped, d := querybuildertypesv5HavingValueFromObject(ctx, v.Having)
	diags.Append(d...)
	having, d := ExpandQuerybuildertypesv5Having(ctx, havingTyped)
	diags.Append(d...)
	limitByTyped, d := querybuildertypesv5LimitByValueFromObject(ctx, v.LimitBy)
	diags.Append(d...)
	limitBy, d := ExpandQuerybuildertypesv5LimitBy(ctx, limitByTyped)
	diags.Append(d...)
	order, d := ExpandQuerybuildertypesv5OrderByList(ctx, v.Order)
	diags.Append(d...)
	secondaryAggregations, d := ExpandQuerybuildertypesv5SecondaryAggregationList(ctx, v.SecondaryAggregations)
	diags.Append(d...)
	selectFields, d := ExpandTelemetrytypesTelemetryFieldKeyList(ctx, v.SelectFields)
	diags.Append(d...)
	var source *apitypes.TelemetrytypesSource
	if !v.Source.IsNull() && !v.Source.IsUnknown() {
		x := apitypes.TelemetrytypesSource(v.Source.ValueString())
		source = &x
	}
	stepInterval, d := ExpandQuerybuildertypesv5Step(ctx, v.StepInterval)
	diags.Append(d...)
	if diags.HasError() {
		return nil, diags
	}
	return &apitypes.Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregation{
		Aggregations:          aggregations,
		Cursor:                convtypes.StringPointer(v.Cursor),
		Disabled:              convtypes.BoolPointer(v.Disabled),
		Filter:                filter,
		Functions:             functions,
		GroupBy:               groupBy,
		Having:                having,
		Legend:                convtypes.StringPointer(v.Legend),
		Limit:                 convtypes.IntPointer(v.Limit),
		LimitBy:               limitBy,
		Name:                  convtypes.StringPointer(v.Name),
		Offset:                convtypes.IntPointer(v.Offset),
		Order:                 order,
		SecondaryAggregations: secondaryAggregations,
		SelectFields:          selectFields,
		Signal:                apitypes.Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregationSignal(v.Signal.ValueString()),
		Source:                source,
		StepInterval:          stepInterval,
	}, diags
}

func FlattenQuerybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregation(ctx context.Context, in *apitypes.Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregation) (customtypes.Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregationValue, diag.Diagnostics) {
	var diags diag.Diagnostics
	if in == nil {
		return customtypes.NewQuerybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregationValueNull(), diags
	}

	aggregationsFlat, d := FlattenQuerybuildertypesv5LogAggregationList(ctx, in.Aggregations)
	diags.Append(d...)
	filterFlatTyped, d := FlattenQuerybuildertypesv5Filter(ctx, in.Filter)
	diags.Append(d...)
	filterFlat, d := filterFlatTyped.ToObjectValue(ctx)
	diags.Append(d...)
	functionsFlat, d := FlattenQuerybuildertypesv5FunctionList(ctx, in.Functions)
	diags.Append(d...)
	groupByFlat, d := FlattenQuerybuildertypesv5GroupByKeyList(ctx, in.GroupBy)
	diags.Append(d...)
	havingFlatTyped, d := FlattenQuerybuildertypesv5Having(ctx, in.Having)
	diags.Append(d...)
	havingFlat, d := havingFlatTyped.ToObjectValue(ctx)
	diags.Append(d...)
	limitByFlatTyped, d := FlattenQuerybuildertypesv5LimitBy(ctx, in.LimitBy)
	diags.Append(d...)
	limitByFlat, d := limitByFlatTyped.ToObjectValue(ctx)
	diags.Append(d...)
	orderFlat, d := FlattenQuerybuildertypesv5OrderByList(ctx, in.Order)
	diags.Append(d...)
	secondaryAggregationsFlat, d := FlattenQuerybuildertypesv5SecondaryAggregationList(ctx, in.SecondaryAggregations)
	diags.Append(d...)
	selectFieldsFlat, d := FlattenTelemetrytypesTelemetryFieldKeyList(ctx, in.SelectFields)
	diags.Append(d...)
	var sourceFlat types.String
	if in.Source != nil {
		sourceFlat = types.StringValue(string(*in.Source))
	} else {
		sourceFlat = types.StringNull()
	}
	stepIntervalFlat, d := FlattenQuerybuildertypesv5Step(ctx, in.StepInterval)
	diags.Append(d...)
	if diags.HasError() {
		return customtypes.NewQuerybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregationValueUnknown(), diags
	}

	rv, d := customtypes.NewQuerybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregationValue(
		customtypes.Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregationValue{}.AttributeTypes(ctx),
		map[string]attr.Value{
			"aggregations":           aggregationsFlat,
			"cursor":                 convtypes.StringFromPointer(in.Cursor),
			"disabled":               convtypes.BoolFromPointer(in.Disabled),
			"filter":                 filterFlat,
			"functions":              functionsFlat,
			"group_by":               groupByFlat,
			"having":                 havingFlat,
			"legend":                 convtypes.StringFromPointer(in.Legend),
			"limit":                  convtypes.IntFromPointer(in.Limit),
			"limit_by":               limitByFlat,
			"name":                   convtypes.StringFromPointer(in.Name),
			"offset":                 convtypes.IntFromPointer(in.Offset),
			"order":                  orderFlat,
			"secondary_aggregations": secondaryAggregationsFlat,
			"select_fields":          selectFieldsFlat,
			"signal":                 types.StringValue(string(in.Signal)),
			"source":                 sourceFlat,
			"step_interval":          stepIntervalFlat,
		},
	)
	diags.Append(d...)
	return rv, diags
}

func ExpandQuerybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregationList(ctx context.Context, l types.List) (*[]apitypes.Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregation, diag.Diagnostics) {
	var diags diag.Diagnostics
	if l.IsNull() || l.IsUnknown() {
		return nil, diags
	}
	out := make([]apitypes.Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregation, 0, len(l.Elements()))
	for i, el := range l.Elements() {
		sv, ok := el.(customtypes.Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregationValue)
		if !ok {
			diags.AddError("Unexpected list element type",
				fmt.Sprintf("element %d: expected customtypes.Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregationValue, got %T", i, el))
			return nil, diags
		}
		one, d := ExpandQuerybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregation(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out = append(out, *one)
		}
	}
	return &out, diags
}

func FlattenQuerybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregationList(ctx context.Context, in *[]apitypes.Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregation) (types.List, diag.Diagnostics) {
	elemType := customtypes.Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregationValue{}.Type(ctx)
	if in == nil {
		return types.ListNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make([]attr.Value, 0, len(*in))
	for i := range *in {
		sv, d := FlattenQuerybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregation(ctx, &(*in)[i])
		diags.Append(d...)
		if diags.HasError() {
			return types.ListUnknown(elemType), diags
		}
		elems = append(elems, sv)
	}
	listVal, d := types.ListValue(elemType, elems)
	diags.Append(d...)
	return listVal, diags
}

func ExpandQuerybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregationMap(ctx context.Context, m types.Map) (*map[string]apitypes.Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregation, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m.IsNull() || m.IsUnknown() {
		return nil, diags
	}
	out := make(map[string]apitypes.Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregation, len(m.Elements()))
	for k, el := range m.Elements() {
		sv, ok := el.(customtypes.Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregationValue)
		if !ok {
			diags.AddError("Unexpected map element type",
				fmt.Sprintf("element %q: expected customtypes.Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregationValue, got %T", k, el))
			return nil, diags
		}
		one, d := ExpandQuerybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregation(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out[k] = *one
		}
	}
	return &out, diags
}

func FlattenQuerybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregationMap(ctx context.Context, in *map[string]apitypes.Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregation) (types.Map, diag.Diagnostics) {
	elemType := customtypes.Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregationValue{}.Type(ctx)
	if in == nil {
		return types.MapNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make(map[string]attr.Value, len(*in))
	for k := range *in {
		v := (*in)[k]
		sv, d := FlattenQuerybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregation(ctx, &v)
		diags.Append(d...)
		if diags.HasError() {
			return types.MapUnknown(elemType), diags
		}
		elems[k] = sv
	}
	mapVal, d := types.MapValue(elemType, elems)
	diags.Append(d...)
	return mapVal, diags
}

// querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregationValueFromObject lifts the raw basetypes.ObjectValue the
// framework stores for a nested customtype into a typed customtypes.Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregationValue
// (structural cast, no field coercion); package-private, called by parent expanders.
func querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregationValueFromObject(ctx context.Context, ov basetypes.ObjectValue) (customtypes.Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregationValue, diag.Diagnostics) {
	if ov.IsNull() {
		return customtypes.NewQuerybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregationValueNull(), nil
	}
	if ov.IsUnknown() {
		return customtypes.NewQuerybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregationValueUnknown(), nil
	}
	return customtypes.NewQuerybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregationValue(
		customtypes.Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregationValue{}.AttributeTypes(ctx),
		ov.Attributes(),
	)
}
