// Code generated by skaff convertors DO NOT EDIT.
package conv

import (
	"context"
	"fmt"

	"github.com/SigNoz/terraform-provider-signoz/internal/apitypes"
	"github.com/SigNoz/terraform-provider-signoz/internal/customtypes"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

func ExpandDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpec(ctx context.Context, v customtypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValue) (*apitypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpec, diag.Diagnostics) {
	var diags diag.Diagnostics
	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	specTyped, d := dashboardtypesHistogramPanelSpecValueFromObject(ctx, v.Spec)
	diags.Append(d...)
	spec, d := ExpandDashboardtypesHistogramPanelSpec(ctx, specTyped)
	diags.Append(d...)
	if diags.HasError() {
		return nil, diags
	}
	out := &apitypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpec{
		Kind: apitypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecKind(v.Kind.ValueString()),
	}
	if spec != nil {
		out.Spec = *spec
	}
	return out, diags
}

func FlattenDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpec(ctx context.Context, in *apitypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpec) (customtypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValue, diag.Diagnostics) {
	var diags diag.Diagnostics
	if in == nil {
		return customtypes.NewDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValueNull(), diags
	}

	specFlatTyped, d := FlattenDashboardtypesHistogramPanelSpec(ctx, &in.Spec)
	diags.Append(d...)
	specFlat, d := specFlatTyped.ToObjectValue(ctx)
	diags.Append(d...)
	if diags.HasError() {
		return customtypes.NewDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValueUnknown(), diags
	}

	rv, d := customtypes.NewDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValue(
		customtypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValue{}.AttributeTypes(ctx),
		map[string]attr.Value{
			"kind": types.StringValue(string(in.Kind)),
			"spec": specFlat,
		},
	)
	diags.Append(d...)
	return rv, diags
}

func ExpandDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecList(ctx context.Context, l types.List) (*[]apitypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpec, diag.Diagnostics) {
	var diags diag.Diagnostics
	if l.IsNull() || l.IsUnknown() {
		return nil, diags
	}
	out := make([]apitypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpec, 0, len(l.Elements()))
	for i, el := range l.Elements() {
		sv, ok := el.(customtypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValue)
		if !ok {
			diags.AddError("Unexpected list element type",
				fmt.Sprintf("element %d: expected customtypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValue, got %T", i, el))
			return nil, diags
		}
		one, d := ExpandDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpec(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out = append(out, *one)
		}
	}
	return &out, diags
}

func FlattenDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecList(ctx context.Context, in *[]apitypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpec) (types.List, diag.Diagnostics) {
	elemType := customtypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValue{}.Type(ctx)
	if in == nil {
		return types.ListNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make([]attr.Value, 0, len(*in))
	for i := range *in {
		sv, d := FlattenDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpec(ctx, &(*in)[i])
		diags.Append(d...)
		if diags.HasError() {
			return types.ListUnknown(elemType), diags
		}
		elems = append(elems, sv)
	}
	listVal, d := types.ListValue(elemType, elems)
	diags.Append(d...)
	return listVal, diags
}

func ExpandDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecMap(ctx context.Context, m types.Map) (*map[string]apitypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpec, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m.IsNull() || m.IsUnknown() {
		return nil, diags
	}
	out := make(map[string]apitypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpec, len(m.Elements()))
	for k, el := range m.Elements() {
		sv, ok := el.(customtypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValue)
		if !ok {
			diags.AddError("Unexpected map element type",
				fmt.Sprintf("element %q: expected customtypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValue, got %T", k, el))
			return nil, diags
		}
		one, d := ExpandDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpec(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out[k] = *one
		}
	}
	return &out, diags
}

func FlattenDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecMap(ctx context.Context, in *map[string]apitypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpec) (types.Map, diag.Diagnostics) {
	elemType := customtypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValue{}.Type(ctx)
	if in == nil {
		return types.MapNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make(map[string]attr.Value, len(*in))
	for k := range *in {
		v := (*in)[k]
		sv, d := FlattenDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpec(ctx, &v)
		diags.Append(d...)
		if diags.HasError() {
			return types.MapUnknown(elemType), diags
		}
		elems[k] = sv
	}
	mapVal, d := types.MapValue(elemType, elems)
	diags.Append(d...)
	return mapVal, diags
}

// dashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValueFromObject lifts the raw basetypes.ObjectValue the
// framework stores for a nested customtype into a typed customtypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValue
// (structural cast, no field coercion); package-private, called by parent expanders.
func dashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValueFromObject(ctx context.Context, ov basetypes.ObjectValue) (customtypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValue, diag.Diagnostics) {
	if ov.IsNull() {
		return customtypes.NewDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValueNull(), nil
	}
	if ov.IsUnknown() {
		return customtypes.NewDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValueUnknown(), nil
	}
	return customtypes.NewDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValue(
		customtypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValue{}.AttributeTypes(ctx),
		ov.Attributes(),
	)
}
