// Code generated by skaff convertors DO NOT EDIT.
package conv

import (
	"context"
	"fmt"

	"github.com/SigNoz/terraform-provider-signoz/internal/apitypes"
	"github.com/SigNoz/terraform-provider-signoz/internal/customtypes"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

func ExpandDashboardtypesTablePanelSpec(ctx context.Context, v customtypes.DashboardtypesTablePanelSpecValue) (*apitypes.DashboardtypesTablePanelSpec, diag.Diagnostics) {
	var diags diag.Diagnostics
	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	formattingTyped, d := dashboardtypesTableFormattingValueFromObject(ctx, v.Formatting)
	diags.Append(d...)
	formatting, d := ExpandDashboardtypesTableFormatting(ctx, formattingTyped)
	diags.Append(d...)
	thresholds, d := ExpandDashboardtypesTableThresholdList(ctx, v.Thresholds)
	diags.Append(d...)
	visualizationTyped, d := dashboardtypesBasicVisualizationValueFromObject(ctx, v.Visualization)
	diags.Append(d...)
	visualization, d := ExpandDashboardtypesBasicVisualization(ctx, visualizationTyped)
	diags.Append(d...)
	if diags.HasError() {
		return nil, diags
	}
	return &apitypes.DashboardtypesTablePanelSpec{
		Formatting:    formatting,
		Thresholds:    thresholds,
		Visualization: visualization,
	}, diags
}

func FlattenDashboardtypesTablePanelSpec(ctx context.Context, in *apitypes.DashboardtypesTablePanelSpec) (customtypes.DashboardtypesTablePanelSpecValue, diag.Diagnostics) {
	var diags diag.Diagnostics
	if in == nil {
		return customtypes.NewDashboardtypesTablePanelSpecValueNull(), diags
	}

	formattingFlatTyped, d := FlattenDashboardtypesTableFormatting(ctx, in.Formatting)
	diags.Append(d...)
	formattingFlat, d := formattingFlatTyped.ToObjectValue(ctx)
	diags.Append(d...)
	thresholdsFlat, d := FlattenDashboardtypesTableThresholdList(ctx, in.Thresholds)
	diags.Append(d...)
	visualizationFlatTyped, d := FlattenDashboardtypesBasicVisualization(ctx, in.Visualization)
	diags.Append(d...)
	visualizationFlat, d := visualizationFlatTyped.ToObjectValue(ctx)
	diags.Append(d...)
	if diags.HasError() {
		return customtypes.NewDashboardtypesTablePanelSpecValueUnknown(), diags
	}

	rv, d := customtypes.NewDashboardtypesTablePanelSpecValue(
		customtypes.DashboardtypesTablePanelSpecValue{}.AttributeTypes(ctx),
		map[string]attr.Value{
			"formatting":    formattingFlat,
			"thresholds":    thresholdsFlat,
			"visualization": visualizationFlat,
		},
	)
	diags.Append(d...)
	return rv, diags
}

func ExpandDashboardtypesTablePanelSpecList(ctx context.Context, l types.List) (*[]apitypes.DashboardtypesTablePanelSpec, diag.Diagnostics) {
	var diags diag.Diagnostics
	if l.IsNull() || l.IsUnknown() {
		return nil, diags
	}
	out := make([]apitypes.DashboardtypesTablePanelSpec, 0, len(l.Elements()))
	for i, el := range l.Elements() {
		sv, ok := el.(customtypes.DashboardtypesTablePanelSpecValue)
		if !ok {
			diags.AddError("Unexpected list element type",
				fmt.Sprintf("element %d: expected customtypes.DashboardtypesTablePanelSpecValue, got %T", i, el))
			return nil, diags
		}
		one, d := ExpandDashboardtypesTablePanelSpec(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out = append(out, *one)
		}
	}
	return &out, diags
}

func FlattenDashboardtypesTablePanelSpecList(ctx context.Context, in *[]apitypes.DashboardtypesTablePanelSpec) (types.List, diag.Diagnostics) {
	elemType := customtypes.DashboardtypesTablePanelSpecValue{}.Type(ctx)
	if in == nil {
		return types.ListNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make([]attr.Value, 0, len(*in))
	for i := range *in {
		sv, d := FlattenDashboardtypesTablePanelSpec(ctx, &(*in)[i])
		diags.Append(d...)
		if diags.HasError() {
			return types.ListUnknown(elemType), diags
		}
		elems = append(elems, sv)
	}
	listVal, d := types.ListValue(elemType, elems)
	diags.Append(d...)
	return listVal, diags
}

func ExpandDashboardtypesTablePanelSpecMap(ctx context.Context, m types.Map) (*map[string]apitypes.DashboardtypesTablePanelSpec, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m.IsNull() || m.IsUnknown() {
		return nil, diags
	}
	out := make(map[string]apitypes.DashboardtypesTablePanelSpec, len(m.Elements()))
	for k, el := range m.Elements() {
		sv, ok := el.(customtypes.DashboardtypesTablePanelSpecValue)
		if !ok {
			diags.AddError("Unexpected map element type",
				fmt.Sprintf("element %q: expected customtypes.DashboardtypesTablePanelSpecValue, got %T", k, el))
			return nil, diags
		}
		one, d := ExpandDashboardtypesTablePanelSpec(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out[k] = *one
		}
	}
	return &out, diags
}

func FlattenDashboardtypesTablePanelSpecMap(ctx context.Context, in *map[string]apitypes.DashboardtypesTablePanelSpec) (types.Map, diag.Diagnostics) {
	elemType := customtypes.DashboardtypesTablePanelSpecValue{}.Type(ctx)
	if in == nil {
		return types.MapNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make(map[string]attr.Value, len(*in))
	for k := range *in {
		v := (*in)[k]
		sv, d := FlattenDashboardtypesTablePanelSpec(ctx, &v)
		diags.Append(d...)
		if diags.HasError() {
			return types.MapUnknown(elemType), diags
		}
		elems[k] = sv
	}
	mapVal, d := types.MapValue(elemType, elems)
	diags.Append(d...)
	return mapVal, diags
}

// dashboardtypesTablePanelSpecValueFromObject lifts the raw basetypes.ObjectValue the
// framework stores for a nested customtype into a typed customtypes.DashboardtypesTablePanelSpecValue
// (structural cast, no field coercion); package-private, called by parent expanders.
func dashboardtypesTablePanelSpecValueFromObject(ctx context.Context, ov basetypes.ObjectValue) (customtypes.DashboardtypesTablePanelSpecValue, diag.Diagnostics) {
	if ov.IsNull() {
		return customtypes.NewDashboardtypesTablePanelSpecValueNull(), nil
	}
	if ov.IsUnknown() {
		return customtypes.NewDashboardtypesTablePanelSpecValueUnknown(), nil
	}
	return customtypes.NewDashboardtypesTablePanelSpecValue(
		customtypes.DashboardtypesTablePanelSpecValue{}.AttributeTypes(ctx),
		ov.Attributes(),
	)
}
