// Code generated by skaff convertors DO NOT EDIT.
package conv

import (
	"context"
	"fmt"

	"github.com/SigNoz/terraform-provider-signoz/internal/apitypes"
	"github.com/SigNoz/terraform-provider-signoz/internal/customtypes"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

func ExpandDashboardtypesPanelPlugin(ctx context.Context, v customtypes.DashboardtypesPanelPluginValue) (*apitypes.DashboardtypesPanelPlugin, diag.Diagnostics) {
	var diags diag.Diagnostics
	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}
	var out apitypes.DashboardtypesPanelPlugin

	if !v.BarChartPanel.IsNull() && !v.BarChartPanel.IsUnknown() {
		typed, d := dashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesBarChartPanelSpecValueFromObject(ctx, v.BarChartPanel)
		diags.Append(d...)
		member, d := ExpandDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesBarChartPanelSpec(ctx, typed)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if member != nil {
			if err := out.FromDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesBarChartPanelSpec(*member); err != nil {
				diags.AddError("Failed to encode bar_chart_panel union variant", err.Error())
				return nil, diags
			}
		}
		return &out, diags
	}

	if !v.HistogramPanel.IsNull() && !v.HistogramPanel.IsUnknown() {
		typed, d := dashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValueFromObject(ctx, v.HistogramPanel)
		diags.Append(d...)
		member, d := ExpandDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpec(ctx, typed)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if member != nil {
			if err := out.FromDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpec(*member); err != nil {
				diags.AddError("Failed to encode histogram_panel union variant", err.Error())
				return nil, diags
			}
		}
		return &out, diags
	}

	if !v.ListPanel.IsNull() && !v.ListPanel.IsUnknown() {
		typed, d := dashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesListPanelSpecValueFromObject(ctx, v.ListPanel)
		diags.Append(d...)
		member, d := ExpandDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesListPanelSpec(ctx, typed)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if member != nil {
			if err := out.FromDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesListPanelSpec(*member); err != nil {
				diags.AddError("Failed to encode list_panel union variant", err.Error())
				return nil, diags
			}
		}
		return &out, diags
	}

	if !v.NumberPanel.IsNull() && !v.NumberPanel.IsUnknown() {
		typed, d := dashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesNumberPanelSpecValueFromObject(ctx, v.NumberPanel)
		diags.Append(d...)
		member, d := ExpandDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesNumberPanelSpec(ctx, typed)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if member != nil {
			if err := out.FromDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesNumberPanelSpec(*member); err != nil {
				diags.AddError("Failed to encode number_panel union variant", err.Error())
				return nil, diags
			}
		}
		return &out, diags
	}

	if !v.PieChartPanel.IsNull() && !v.PieChartPanel.IsUnknown() {
		typed, d := dashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesPieChartPanelSpecValueFromObject(ctx, v.PieChartPanel)
		diags.Append(d...)
		member, d := ExpandDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesPieChartPanelSpec(ctx, typed)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if member != nil {
			if err := out.FromDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesPieChartPanelSpec(*member); err != nil {
				diags.AddError("Failed to encode pie_chart_panel union variant", err.Error())
				return nil, diags
			}
		}
		return &out, diags
	}

	if !v.TablePanel.IsNull() && !v.TablePanel.IsUnknown() {
		typed, d := dashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesTablePanelSpecValueFromObject(ctx, v.TablePanel)
		diags.Append(d...)
		member, d := ExpandDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesTablePanelSpec(ctx, typed)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if member != nil {
			if err := out.FromDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesTablePanelSpec(*member); err != nil {
				diags.AddError("Failed to encode table_panel union variant", err.Error())
				return nil, diags
			}
		}
		return &out, diags
	}

	if !v.TimeSeriesPanel.IsNull() && !v.TimeSeriesPanel.IsUnknown() {
		typed, d := dashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesTimeSeriesPanelSpecValueFromObject(ctx, v.TimeSeriesPanel)
		diags.Append(d...)
		member, d := ExpandDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesTimeSeriesPanelSpec(ctx, typed)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if member != nil {
			if err := out.FromDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesTimeSeriesPanelSpec(*member); err != nil {
				diags.AddError("Failed to encode time_series_panel union variant", err.Error())
				return nil, diags
			}
		}
		return &out, diags
	}

	return &out, diags
}

func FlattenDashboardtypesPanelPlugin(ctx context.Context, in *apitypes.DashboardtypesPanelPlugin) (customtypes.DashboardtypesPanelPluginValue, diag.Diagnostics) {
	var diags diag.Diagnostics
	if in == nil {
		return customtypes.NewDashboardtypesPanelPluginValueNull(), diags
	}
	attrs := map[string]attr.Value{
		"bar_chart_panel":   basetypes.NewObjectNull(customtypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesBarChartPanelSpecValue{}.AttributeTypes(ctx)),
		"histogram_panel":   basetypes.NewObjectNull(customtypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValue{}.AttributeTypes(ctx)),
		"list_panel":        basetypes.NewObjectNull(customtypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesListPanelSpecValue{}.AttributeTypes(ctx)),
		"number_panel":      basetypes.NewObjectNull(customtypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesNumberPanelSpecValue{}.AttributeTypes(ctx)),
		"pie_chart_panel":   basetypes.NewObjectNull(customtypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesPieChartPanelSpecValue{}.AttributeTypes(ctx)),
		"table_panel":       basetypes.NewObjectNull(customtypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesTablePanelSpecValue{}.AttributeTypes(ctx)),
		"time_series_panel": basetypes.NewObjectNull(customtypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesTimeSeriesPanelSpecValue{}.AttributeTypes(ctx)),
	}
	disc, err := in.ValueByDiscriminator()
	if err != nil {
		diags.AddError("Failed to decode DashboardtypesPanelPlugin union", err.Error())
		return customtypes.NewDashboardtypesPanelPluginValueUnknown(), diags
	}
	switch member := disc.(type) {
	case apitypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesBarChartPanelSpec:
		fv, d := FlattenDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesBarChartPanelSpec(ctx, &member)
		diags.Append(d...)
		ov, d := fv.ToObjectValue(ctx)
		diags.Append(d...)
		attrs["bar_chart_panel"] = ov
	case apitypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpec:
		fv, d := FlattenDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpec(ctx, &member)
		diags.Append(d...)
		ov, d := fv.ToObjectValue(ctx)
		diags.Append(d...)
		attrs["histogram_panel"] = ov
	case apitypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesListPanelSpec:
		fv, d := FlattenDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesListPanelSpec(ctx, &member)
		diags.Append(d...)
		ov, d := fv.ToObjectValue(ctx)
		diags.Append(d...)
		attrs["list_panel"] = ov
	case apitypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesNumberPanelSpec:
		fv, d := FlattenDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesNumberPanelSpec(ctx, &member)
		diags.Append(d...)
		ov, d := fv.ToObjectValue(ctx)
		diags.Append(d...)
		attrs["number_panel"] = ov
	case apitypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesPieChartPanelSpec:
		fv, d := FlattenDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesPieChartPanelSpec(ctx, &member)
		diags.Append(d...)
		ov, d := fv.ToObjectValue(ctx)
		diags.Append(d...)
		attrs["pie_chart_panel"] = ov
	case apitypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesTablePanelSpec:
		fv, d := FlattenDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesTablePanelSpec(ctx, &member)
		diags.Append(d...)
		ov, d := fv.ToObjectValue(ctx)
		diags.Append(d...)
		attrs["table_panel"] = ov
	case apitypes.DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesTimeSeriesPanelSpec:
		fv, d := FlattenDashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesTimeSeriesPanelSpec(ctx, &member)
		diags.Append(d...)
		ov, d := fv.ToObjectValue(ctx)
		diags.Append(d...)
		attrs["time_series_panel"] = ov
	}
	if diags.HasError() {
		return customtypes.NewDashboardtypesPanelPluginValueUnknown(), diags
	}
	rv, d := customtypes.NewDashboardtypesPanelPluginValue(customtypes.DashboardtypesPanelPluginValue{}.AttributeTypes(ctx), attrs)
	diags.Append(d...)
	return rv, diags
}

func ExpandDashboardtypesPanelPluginList(ctx context.Context, l types.List) (*[]apitypes.DashboardtypesPanelPlugin, diag.Diagnostics) {
	var diags diag.Diagnostics
	if l.IsNull() || l.IsUnknown() {
		return nil, diags
	}
	out := make([]apitypes.DashboardtypesPanelPlugin, 0, len(l.Elements()))
	for i, el := range l.Elements() {
		sv, ok := el.(customtypes.DashboardtypesPanelPluginValue)
		if !ok {
			diags.AddError("Unexpected list element type",
				fmt.Sprintf("element %d: expected customtypes.DashboardtypesPanelPluginValue, got %T", i, el))
			return nil, diags
		}
		one, d := ExpandDashboardtypesPanelPlugin(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out = append(out, *one)
		}
	}
	return &out, diags
}

func FlattenDashboardtypesPanelPluginList(ctx context.Context, in *[]apitypes.DashboardtypesPanelPlugin) (types.List, diag.Diagnostics) {
	elemType := customtypes.DashboardtypesPanelPluginValue{}.Type(ctx)
	if in == nil {
		return types.ListNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make([]attr.Value, 0, len(*in))
	for i := range *in {
		sv, d := FlattenDashboardtypesPanelPlugin(ctx, &(*in)[i])
		diags.Append(d...)
		if diags.HasError() {
			return types.ListUnknown(elemType), diags
		}
		elems = append(elems, sv)
	}
	listVal, d := types.ListValue(elemType, elems)
	diags.Append(d...)
	return listVal, diags
}

func ExpandDashboardtypesPanelPluginMap(ctx context.Context, m types.Map) (*map[string]apitypes.DashboardtypesPanelPlugin, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m.IsNull() || m.IsUnknown() {
		return nil, diags
	}
	out := make(map[string]apitypes.DashboardtypesPanelPlugin, len(m.Elements()))
	for k, el := range m.Elements() {
		sv, ok := el.(customtypes.DashboardtypesPanelPluginValue)
		if !ok {
			diags.AddError("Unexpected map element type",
				fmt.Sprintf("element %q: expected customtypes.DashboardtypesPanelPluginValue, got %T", k, el))
			return nil, diags
		}
		one, d := ExpandDashboardtypesPanelPlugin(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out[k] = *one
		}
	}
	return &out, diags
}

func FlattenDashboardtypesPanelPluginMap(ctx context.Context, in *map[string]apitypes.DashboardtypesPanelPlugin) (types.Map, diag.Diagnostics) {
	elemType := customtypes.DashboardtypesPanelPluginValue{}.Type(ctx)
	if in == nil {
		return types.MapNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make(map[string]attr.Value, len(*in))
	for k := range *in {
		v := (*in)[k]
		sv, d := FlattenDashboardtypesPanelPlugin(ctx, &v)
		diags.Append(d...)
		if diags.HasError() {
			return types.MapUnknown(elemType), diags
		}
		elems[k] = sv
	}
	mapVal, d := types.MapValue(elemType, elems)
	diags.Append(d...)
	return mapVal, diags
}

// dashboardtypesPanelPluginValueFromObject lifts the raw basetypes.ObjectValue the
// framework stores for a nested customtype into a typed customtypes.DashboardtypesPanelPluginValue
// (structural cast, no field coercion); package-private, called by parent expanders.
func dashboardtypesPanelPluginValueFromObject(ctx context.Context, ov basetypes.ObjectValue) (customtypes.DashboardtypesPanelPluginValue, diag.Diagnostics) {
	if ov.IsNull() {
		return customtypes.NewDashboardtypesPanelPluginValueNull(), nil
	}
	if ov.IsUnknown() {
		return customtypes.NewDashboardtypesPanelPluginValueUnknown(), nil
	}
	return customtypes.NewDashboardtypesPanelPluginValue(
		customtypes.DashboardtypesPanelPluginValue{}.AttributeTypes(ctx),
		ov.Attributes(),
	)
}
