// Code generated by skaff convertors DO NOT EDIT.
package conv

import (
	"context"
	"fmt"

	"github.com/SigNoz/terraform-provider-signoz/internal/apitypes"
	"github.com/SigNoz/terraform-provider-signoz/internal/customtypes"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

func ExpandQuerybuildertypesv5OrderBy(ctx context.Context, v customtypes.Querybuildertypesv5OrderByValue) (*apitypes.Querybuildertypesv5OrderBy, diag.Diagnostics) {
	var diags diag.Diagnostics
	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	var direction *apitypes.Querybuildertypesv5OrderDirection
	if !v.Direction.IsNull() && !v.Direction.IsUnknown() {
		x := apitypes.Querybuildertypesv5OrderDirection(v.Direction.ValueString())
		direction = &x
	}
	keyTyped, d := querybuildertypesv5OrderByKeyValueFromObject(ctx, v.Key)
	diags.Append(d...)
	key, d := ExpandQuerybuildertypesv5OrderByKey(ctx, keyTyped)
	diags.Append(d...)
	if diags.HasError() {
		return nil, diags
	}
	return &apitypes.Querybuildertypesv5OrderBy{
		Direction: direction,
		Key:       key,
	}, diags
}

func FlattenQuerybuildertypesv5OrderBy(ctx context.Context, in *apitypes.Querybuildertypesv5OrderBy) (customtypes.Querybuildertypesv5OrderByValue, diag.Diagnostics) {
	var diags diag.Diagnostics
	if in == nil {
		return customtypes.NewQuerybuildertypesv5OrderByValueNull(), diags
	}

	var directionFlat types.String
	if in.Direction != nil {
		directionFlat = types.StringValue(string(*in.Direction))
	} else {
		directionFlat = types.StringNull()
	}
	keyFlatTyped, d := FlattenQuerybuildertypesv5OrderByKey(ctx, in.Key)
	diags.Append(d...)
	keyFlat, d := keyFlatTyped.ToObjectValue(ctx)
	diags.Append(d...)
	if diags.HasError() {
		return customtypes.NewQuerybuildertypesv5OrderByValueUnknown(), diags
	}

	rv, d := customtypes.NewQuerybuildertypesv5OrderByValue(
		customtypes.Querybuildertypesv5OrderByValue{}.AttributeTypes(ctx),
		map[string]attr.Value{
			"direction": directionFlat,
			"key":       keyFlat,
		},
	)
	diags.Append(d...)
	return rv, diags
}

func ExpandQuerybuildertypesv5OrderByList(ctx context.Context, l types.List) (*[]apitypes.Querybuildertypesv5OrderBy, diag.Diagnostics) {
	var diags diag.Diagnostics
	if l.IsNull() || l.IsUnknown() {
		return nil, diags
	}
	out := make([]apitypes.Querybuildertypesv5OrderBy, 0, len(l.Elements()))
	for i, el := range l.Elements() {
		sv, ok := el.(customtypes.Querybuildertypesv5OrderByValue)
		if !ok {
			diags.AddError("Unexpected list element type",
				fmt.Sprintf("element %d: expected customtypes.Querybuildertypesv5OrderByValue, got %T", i, el))
			return nil, diags
		}
		one, d := ExpandQuerybuildertypesv5OrderBy(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out = append(out, *one)
		}
	}
	return &out, diags
}

func FlattenQuerybuildertypesv5OrderByList(ctx context.Context, in *[]apitypes.Querybuildertypesv5OrderBy) (types.List, diag.Diagnostics) {
	elemType := customtypes.Querybuildertypesv5OrderByValue{}.Type(ctx)
	if in == nil {
		return types.ListNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make([]attr.Value, 0, len(*in))
	for i := range *in {
		sv, d := FlattenQuerybuildertypesv5OrderBy(ctx, &(*in)[i])
		diags.Append(d...)
		if diags.HasError() {
			return types.ListUnknown(elemType), diags
		}
		elems = append(elems, sv)
	}
	listVal, d := types.ListValue(elemType, elems)
	diags.Append(d...)
	return listVal, diags
}

func ExpandQuerybuildertypesv5OrderByMap(ctx context.Context, m types.Map) (*map[string]apitypes.Querybuildertypesv5OrderBy, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m.IsNull() || m.IsUnknown() {
		return nil, diags
	}
	out := make(map[string]apitypes.Querybuildertypesv5OrderBy, len(m.Elements()))
	for k, el := range m.Elements() {
		sv, ok := el.(customtypes.Querybuildertypesv5OrderByValue)
		if !ok {
			diags.AddError("Unexpected map element type",
				fmt.Sprintf("element %q: expected customtypes.Querybuildertypesv5OrderByValue, got %T", k, el))
			return nil, diags
		}
		one, d := ExpandQuerybuildertypesv5OrderBy(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out[k] = *one
		}
	}
	return &out, diags
}

func FlattenQuerybuildertypesv5OrderByMap(ctx context.Context, in *map[string]apitypes.Querybuildertypesv5OrderBy) (types.Map, diag.Diagnostics) {
	elemType := customtypes.Querybuildertypesv5OrderByValue{}.Type(ctx)
	if in == nil {
		return types.MapNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make(map[string]attr.Value, len(*in))
	for k := range *in {
		v := (*in)[k]
		sv, d := FlattenQuerybuildertypesv5OrderBy(ctx, &v)
		diags.Append(d...)
		if diags.HasError() {
			return types.MapUnknown(elemType), diags
		}
		elems[k] = sv
	}
	mapVal, d := types.MapValue(elemType, elems)
	diags.Append(d...)
	return mapVal, diags
}

// querybuildertypesv5OrderByValueFromObject lifts the raw basetypes.ObjectValue the
// framework stores for a nested customtype into a typed customtypes.Querybuildertypesv5OrderByValue
// (structural cast, no field coercion); package-private, called by parent expanders.
func querybuildertypesv5OrderByValueFromObject(ctx context.Context, ov basetypes.ObjectValue) (customtypes.Querybuildertypesv5OrderByValue, diag.Diagnostics) {
	if ov.IsNull() {
		return customtypes.NewQuerybuildertypesv5OrderByValueNull(), nil
	}
	if ov.IsUnknown() {
		return customtypes.NewQuerybuildertypesv5OrderByValueUnknown(), nil
	}
	return customtypes.NewQuerybuildertypesv5OrderByValue(
		customtypes.Querybuildertypesv5OrderByValue{}.AttributeTypes(ctx),
		ov.Attributes(),
	)
}
