// Code generated by skaff convertors DO NOT EDIT.
package conv

import (
	"context"
	"fmt"

	"github.com/SigNoz/terraform-provider-signoz/internal/apitypes"
	"github.com/SigNoz/terraform-provider-signoz/internal/convtypes"
	"github.com/SigNoz/terraform-provider-signoz/internal/customtypes"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

func ExpandRuletypesAlertCompositeQuery(ctx context.Context, v customtypes.RuletypesAlertCompositeQueryValue) (*apitypes.RuletypesAlertCompositeQuery, diag.Diagnostics) {
	var diags diag.Diagnostics
	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	queries, d := ExpandQuerybuildertypesv5QueryEnvelopeList(ctx, v.Queries)
	diags.Append(d...)
	if diags.HasError() {
		return nil, diags
	}
	return &apitypes.RuletypesAlertCompositeQuery{
		PanelType: apitypes.RuletypesPanelType(v.PanelType.ValueString()),
		Queries:   queries,
		QueryType: apitypes.RuletypesQueryType(v.QueryType.ValueString()),
		Unit:      convtypes.StringPointer(v.Unit),
	}, diags
}

func FlattenRuletypesAlertCompositeQuery(ctx context.Context, in *apitypes.RuletypesAlertCompositeQuery) (customtypes.RuletypesAlertCompositeQueryValue, diag.Diagnostics) {
	var diags diag.Diagnostics
	if in == nil {
		return customtypes.NewRuletypesAlertCompositeQueryValueNull(), diags
	}

	queriesFlat, d := FlattenQuerybuildertypesv5QueryEnvelopeList(ctx, in.Queries)
	diags.Append(d...)
	if diags.HasError() {
		return customtypes.NewRuletypesAlertCompositeQueryValueUnknown(), diags
	}

	rv, d := customtypes.NewRuletypesAlertCompositeQueryValue(
		customtypes.RuletypesAlertCompositeQueryValue{}.AttributeTypes(ctx),
		map[string]attr.Value{
			"panel_type": types.StringValue(string(in.PanelType)),
			"queries":    queriesFlat,
			"query_type": types.StringValue(string(in.QueryType)),
			"unit":       convtypes.StringFromPointer(in.Unit),
		},
	)
	diags.Append(d...)
	return rv, diags
}

func ExpandRuletypesAlertCompositeQueryList(ctx context.Context, l types.List) (*[]apitypes.RuletypesAlertCompositeQuery, diag.Diagnostics) {
	var diags diag.Diagnostics
	if l.IsNull() || l.IsUnknown() {
		return nil, diags
	}
	out := make([]apitypes.RuletypesAlertCompositeQuery, 0, len(l.Elements()))
	for i, el := range l.Elements() {
		sv, ok := el.(customtypes.RuletypesAlertCompositeQueryValue)
		if !ok {
			diags.AddError("Unexpected list element type",
				fmt.Sprintf("element %d: expected customtypes.RuletypesAlertCompositeQueryValue, got %T", i, el))
			return nil, diags
		}
		one, d := ExpandRuletypesAlertCompositeQuery(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out = append(out, *one)
		}
	}
	return &out, diags
}

func FlattenRuletypesAlertCompositeQueryList(ctx context.Context, in *[]apitypes.RuletypesAlertCompositeQuery) (types.List, diag.Diagnostics) {
	elemType := customtypes.RuletypesAlertCompositeQueryValue{}.Type(ctx)
	if in == nil {
		return types.ListNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make([]attr.Value, 0, len(*in))
	for i := range *in {
		sv, d := FlattenRuletypesAlertCompositeQuery(ctx, &(*in)[i])
		diags.Append(d...)
		if diags.HasError() {
			return types.ListUnknown(elemType), diags
		}
		elems = append(elems, sv)
	}
	listVal, d := types.ListValue(elemType, elems)
	diags.Append(d...)
	return listVal, diags
}

func ExpandRuletypesAlertCompositeQueryMap(ctx context.Context, m types.Map) (*map[string]apitypes.RuletypesAlertCompositeQuery, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m.IsNull() || m.IsUnknown() {
		return nil, diags
	}
	out := make(map[string]apitypes.RuletypesAlertCompositeQuery, len(m.Elements()))
	for k, el := range m.Elements() {
		sv, ok := el.(customtypes.RuletypesAlertCompositeQueryValue)
		if !ok {
			diags.AddError("Unexpected map element type",
				fmt.Sprintf("element %q: expected customtypes.RuletypesAlertCompositeQueryValue, got %T", k, el))
			return nil, diags
		}
		one, d := ExpandRuletypesAlertCompositeQuery(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out[k] = *one
		}
	}
	return &out, diags
}

func FlattenRuletypesAlertCompositeQueryMap(ctx context.Context, in *map[string]apitypes.RuletypesAlertCompositeQuery) (types.Map, diag.Diagnostics) {
	elemType := customtypes.RuletypesAlertCompositeQueryValue{}.Type(ctx)
	if in == nil {
		return types.MapNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make(map[string]attr.Value, len(*in))
	for k := range *in {
		v := (*in)[k]
		sv, d := FlattenRuletypesAlertCompositeQuery(ctx, &v)
		diags.Append(d...)
		if diags.HasError() {
			return types.MapUnknown(elemType), diags
		}
		elems[k] = sv
	}
	mapVal, d := types.MapValue(elemType, elems)
	diags.Append(d...)
	return mapVal, diags
}

// ruletypesAlertCompositeQueryValueFromObject lifts the raw basetypes.ObjectValue the
// framework stores for a nested customtype into a typed customtypes.RuletypesAlertCompositeQueryValue
// (structural cast, no field coercion); package-private, called by parent expanders.
func ruletypesAlertCompositeQueryValueFromObject(ctx context.Context, ov basetypes.ObjectValue) (customtypes.RuletypesAlertCompositeQueryValue, diag.Diagnostics) {
	if ov.IsNull() {
		return customtypes.NewRuletypesAlertCompositeQueryValueNull(), nil
	}
	if ov.IsUnknown() {
		return customtypes.NewRuletypesAlertCompositeQueryValueUnknown(), nil
	}
	return customtypes.NewRuletypesAlertCompositeQueryValue(
		customtypes.RuletypesAlertCompositeQueryValue{}.AttributeTypes(ctx),
		ov.Attributes(),
	)
}
