// Code generated by skaff convertors DO NOT EDIT.
package conv

import (
	"context"
	"fmt"

	"github.com/SigNoz/terraform-provider-signoz/internal/apitypes"
	customtypes "github.com/SigNoz/terraform-provider-signoz/internal/types"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// ExpandAuthtypesRole converts a framework-side
// `customtypes.AuthtypesRoleValue` into the wire-format
// `*apitypes.AuthtypesRole`. Null/unknown framework value → nil
// pointer; the caller (parent expander) decides how to handle that.
func ExpandAuthtypesRole(ctx context.Context, v customtypes.AuthtypesRoleValue) (*apitypes.AuthtypesRole, diag.Diagnostics) {
	var diags diag.Diagnostics
	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	createdAt, d := TimePointerFromString(v.CreatedAt)
	diags.Append(d...)
	updatedAt, d := TimePointerFromString(v.UpdatedAt)
	diags.Append(d...)
	if diags.HasError() {
		return nil, diags
	}
	return &apitypes.AuthtypesRole{
		CreatedAt:   createdAt,
		Description: v.Description.ValueString(),
		Id:          v.Id.ValueString(),
		Name:        v.Name.ValueString(),
		OrgId:       v.OrgId.ValueString(),
		Type:        v.Type_.ValueString(),
		UpdatedAt:   updatedAt,
	}, diags
}

// FlattenAuthtypesRole is the inverse of ExpandAuthtypesRole.
// nil DTO → null framework value.
func FlattenAuthtypesRole(ctx context.Context, in *apitypes.AuthtypesRole) (customtypes.AuthtypesRoleValue, diag.Diagnostics) {
	var diags diag.Diagnostics
	if in == nil {
		return customtypes.NewAuthtypesRoleValueNull(), diags
	}

	if diags.HasError() {
		return customtypes.NewAuthtypesRoleValueUnknown(), diags
	}

	rv, d := customtypes.NewAuthtypesRoleValue(
		customtypes.AuthtypesRoleValue{}.AttributeTypes(ctx),
		map[string]attr.Value{
			"created_at":  TimeStringFromPointer(in.CreatedAt),
			"description": types.StringValue(in.Description),
			"id":          types.StringValue(in.Id),
			"name":        types.StringValue(in.Name),
			"org_id":      types.StringValue(in.OrgId),
			"type_":       types.StringValue(in.Type),
			"updated_at":  TimeStringFromPointer(in.UpdatedAt),
		},
	)
	diags.Append(d...)
	return rv, diags
}

// authtypesRoleValueFromObject lifts a `basetypes.ObjectValue`
// (the framework stores nested customtypes as raw ObjectValue on the
// parent at code-gen time) into a typed `customtypes.AuthtypesRoleValue`.
// Pure structural cast; no field-level coercion. Used by parent
// expanders that recurse into this schema; package-private since all
// callers live in package `conv`.
func authtypesRoleValueFromObject(ctx context.Context, ov basetypes.ObjectValue) (customtypes.AuthtypesRoleValue, diag.Diagnostics) {
	if ov.IsNull() {
		return customtypes.NewAuthtypesRoleValueNull(), nil
	}
	if ov.IsUnknown() {
		return customtypes.NewAuthtypesRoleValueUnknown(), nil
	}
	return customtypes.NewAuthtypesRoleValue(
		customtypes.AuthtypesRoleValue{}.AttributeTypes(ctx),
		ov.Attributes(),
	)
}

// ExpandAuthtypesRoleList walks a List<AuthtypesRoleValue> and
// returns the wire-format `*[]apitypes.AuthtypesRole`. Null/unknown
// list → nil pointer; known list → pointer to a slice with one entry
// per non-nil element. Used by parent expanders for fields shaped
// `*[]apitypes.AuthtypesRole`.
func ExpandAuthtypesRoleList(ctx context.Context, l types.List) (*[]apitypes.AuthtypesRole, diag.Diagnostics) {
	var diags diag.Diagnostics
	if l.IsNull() || l.IsUnknown() {
		return nil, diags
	}
	out := make([]apitypes.AuthtypesRole, 0, len(l.Elements()))
	for i, el := range l.Elements() {
		sv, ok := el.(customtypes.AuthtypesRoleValue)
		if !ok {
			diags.AddError("Unexpected list element type",
				fmt.Sprintf("element %d: expected customtypes.AuthtypesRoleValue, got %T", i, el))
			return nil, diags
		}
		one, d := ExpandAuthtypesRole(ctx, sv)
		diags.Append(d...)
		if diags.HasError() {
			return nil, diags
		}
		if one != nil {
			out = append(out, *one)
		}
	}
	return &out, diags
}

// FlattenAuthtypesRoleList is the inverse of ExpandAuthtypesRoleList.
// nil pointer → null List; otherwise one framework value per slice entry.
func FlattenAuthtypesRoleList(ctx context.Context, in *[]apitypes.AuthtypesRole) (types.List, diag.Diagnostics) {
	elemType := customtypes.AuthtypesRoleValue{}.Type(ctx)
	if in == nil {
		return types.ListNull(elemType), nil
	}
	var diags diag.Diagnostics
	elems := make([]attr.Value, 0, len(*in))
	for i := range *in {
		sv, d := FlattenAuthtypesRole(ctx, &(*in)[i])
		diags.Append(d...)
		if diags.HasError() {
			return types.ListUnknown(elemType), diags
		}
		elems = append(elems, sv)
	}
	listVal, d := types.ListValue(elemType, elems)
	diags.Append(d...)
	return listVal, diags
}
