// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

// CommonDisplay defines model for CommonDisplay.
type CommonDisplay struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}
