// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

// Querybuildertypesv5CompositeQuery Composite query containing one or more query envelopes. Each query envelope specifies its type and corresponding spec.
type Querybuildertypesv5CompositeQuery struct {
	Queries *[]Querybuildertypesv5QueryEnvelope `json:"queries,omitempty"`
}
