// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

// DashboardtypesTimeSeriesChartAppearance defines model for DashboardtypesTimeSeriesChartAppearance.
type DashboardtypesTimeSeriesChartAppearance struct {
	FillMode          *DashboardtypesFillMode          `json:"fillMode,omitempty"`
	LineInterpolation *DashboardtypesLineInterpolation `json:"lineInterpolation,omitempty"`
	LineStyle         *DashboardtypesLineStyle         `json:"lineStyle,omitempty"`
	ShowPoints        *bool                            `json:"showPoints,omitempty"`
	SpanGaps          *DashboardtypesSpanGaps          `json:"spanGaps,omitempty"`
}
