// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
)

// Querybuildertypesv5FunctionArg defines model for Querybuildertypesv5FunctionArg.
type Querybuildertypesv5FunctionArg struct {
	Name  *string                               `json:"name,omitempty"`
	Value *Querybuildertypesv5FunctionArg_Value `json:"value,omitempty"`
}

// Querybuildertypesv5FunctionArgValue0 defines model for .
type Querybuildertypesv5FunctionArgValue0 = float32

// Querybuildertypesv5FunctionArgValue1 defines model for .
type Querybuildertypesv5FunctionArgValue1 = string

// Querybuildertypesv5FunctionArg_Value defines model for Querybuildertypesv5FunctionArg.Value.
type Querybuildertypesv5FunctionArg_Value struct {
	union json.RawMessage
}

// AsQuerybuildertypesv5FunctionArgValue0 returns the union data inside the Querybuildertypesv5FunctionArg_Value as a Querybuildertypesv5FunctionArgValue0
func (t Querybuildertypesv5FunctionArg_Value) AsQuerybuildertypesv5FunctionArgValue0() (Querybuildertypesv5FunctionArgValue0, error) {
	var body Querybuildertypesv5FunctionArgValue0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5FunctionArgValue0 overwrites any union data inside the Querybuildertypesv5FunctionArg_Value as the provided Querybuildertypesv5FunctionArgValue0
func (t *Querybuildertypesv5FunctionArg_Value) FromQuerybuildertypesv5FunctionArgValue0(v Querybuildertypesv5FunctionArgValue0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5FunctionArgValue0 performs a merge with any union data inside the Querybuildertypesv5FunctionArg_Value, using the provided Querybuildertypesv5FunctionArgValue0
func (t *Querybuildertypesv5FunctionArg_Value) MergeQuerybuildertypesv5FunctionArgValue0(v Querybuildertypesv5FunctionArgValue0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQuerybuildertypesv5FunctionArgValue1 returns the union data inside the Querybuildertypesv5FunctionArg_Value as a Querybuildertypesv5FunctionArgValue1
func (t Querybuildertypesv5FunctionArg_Value) AsQuerybuildertypesv5FunctionArgValue1() (Querybuildertypesv5FunctionArgValue1, error) {
	var body Querybuildertypesv5FunctionArgValue1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5FunctionArgValue1 overwrites any union data inside the Querybuildertypesv5FunctionArg_Value as the provided Querybuildertypesv5FunctionArgValue1
func (t *Querybuildertypesv5FunctionArg_Value) FromQuerybuildertypesv5FunctionArgValue1(v Querybuildertypesv5FunctionArgValue1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5FunctionArgValue1 performs a merge with any union data inside the Querybuildertypesv5FunctionArg_Value, using the provided Querybuildertypesv5FunctionArgValue1
func (t *Querybuildertypesv5FunctionArg_Value) MergeQuerybuildertypesv5FunctionArgValue1(v Querybuildertypesv5FunctionArgValue1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Querybuildertypesv5FunctionArg_Value) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Querybuildertypesv5FunctionArg_Value) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
