// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

import (
	"encoding/json"
	"fmt"

	"github.com/oapi-codegen/runtime"
)

// Querybuildertypesv5QueryEnvelope defines model for Querybuildertypesv5QueryEnvelope.
type Querybuildertypesv5QueryEnvelope struct {
	Spec  interface{}                   `json:"spec,omitempty"`
	Type  *Querybuildertypesv5QueryType `json:"type,omitempty"`
	union json.RawMessage
}

// AsQuerybuildertypesv5QueryEnvelopeBuilderTrace returns the union data inside the Querybuildertypesv5QueryEnvelope as a Querybuildertypesv5QueryEnvelopeBuilderTrace
func (t Querybuildertypesv5QueryEnvelope) AsQuerybuildertypesv5QueryEnvelopeBuilderTrace() (Querybuildertypesv5QueryEnvelopeBuilderTrace, error) {
	var body Querybuildertypesv5QueryEnvelopeBuilderTrace
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5QueryEnvelopeBuilderTrace overwrites any union data inside the Querybuildertypesv5QueryEnvelope as the provided Querybuildertypesv5QueryEnvelopeBuilderTrace
func (t *Querybuildertypesv5QueryEnvelope) FromQuerybuildertypesv5QueryEnvelopeBuilderTrace(v Querybuildertypesv5QueryEnvelopeBuilderTrace) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5QueryEnvelopeBuilderTrace performs a merge with any union data inside the Querybuildertypesv5QueryEnvelope, using the provided Querybuildertypesv5QueryEnvelopeBuilderTrace
func (t *Querybuildertypesv5QueryEnvelope) MergeQuerybuildertypesv5QueryEnvelopeBuilderTrace(v Querybuildertypesv5QueryEnvelopeBuilderTrace) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQuerybuildertypesv5QueryEnvelopeBuilderLog returns the union data inside the Querybuildertypesv5QueryEnvelope as a Querybuildertypesv5QueryEnvelopeBuilderLog
func (t Querybuildertypesv5QueryEnvelope) AsQuerybuildertypesv5QueryEnvelopeBuilderLog() (Querybuildertypesv5QueryEnvelopeBuilderLog, error) {
	var body Querybuildertypesv5QueryEnvelopeBuilderLog
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5QueryEnvelopeBuilderLog overwrites any union data inside the Querybuildertypesv5QueryEnvelope as the provided Querybuildertypesv5QueryEnvelopeBuilderLog
func (t *Querybuildertypesv5QueryEnvelope) FromQuerybuildertypesv5QueryEnvelopeBuilderLog(v Querybuildertypesv5QueryEnvelopeBuilderLog) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5QueryEnvelopeBuilderLog performs a merge with any union data inside the Querybuildertypesv5QueryEnvelope, using the provided Querybuildertypesv5QueryEnvelopeBuilderLog
func (t *Querybuildertypesv5QueryEnvelope) MergeQuerybuildertypesv5QueryEnvelopeBuilderLog(v Querybuildertypesv5QueryEnvelopeBuilderLog) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQuerybuildertypesv5QueryEnvelopeBuilderMetric returns the union data inside the Querybuildertypesv5QueryEnvelope as a Querybuildertypesv5QueryEnvelopeBuilderMetric
func (t Querybuildertypesv5QueryEnvelope) AsQuerybuildertypesv5QueryEnvelopeBuilderMetric() (Querybuildertypesv5QueryEnvelopeBuilderMetric, error) {
	var body Querybuildertypesv5QueryEnvelopeBuilderMetric
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5QueryEnvelopeBuilderMetric overwrites any union data inside the Querybuildertypesv5QueryEnvelope as the provided Querybuildertypesv5QueryEnvelopeBuilderMetric
func (t *Querybuildertypesv5QueryEnvelope) FromQuerybuildertypesv5QueryEnvelopeBuilderMetric(v Querybuildertypesv5QueryEnvelopeBuilderMetric) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5QueryEnvelopeBuilderMetric performs a merge with any union data inside the Querybuildertypesv5QueryEnvelope, using the provided Querybuildertypesv5QueryEnvelopeBuilderMetric
func (t *Querybuildertypesv5QueryEnvelope) MergeQuerybuildertypesv5QueryEnvelopeBuilderMetric(v Querybuildertypesv5QueryEnvelopeBuilderMetric) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQuerybuildertypesv5QueryEnvelopeFormula returns the union data inside the Querybuildertypesv5QueryEnvelope as a Querybuildertypesv5QueryEnvelopeFormula
func (t Querybuildertypesv5QueryEnvelope) AsQuerybuildertypesv5QueryEnvelopeFormula() (Querybuildertypesv5QueryEnvelopeFormula, error) {
	var body Querybuildertypesv5QueryEnvelopeFormula
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5QueryEnvelopeFormula overwrites any union data inside the Querybuildertypesv5QueryEnvelope as the provided Querybuildertypesv5QueryEnvelopeFormula
func (t *Querybuildertypesv5QueryEnvelope) FromQuerybuildertypesv5QueryEnvelopeFormula(v Querybuildertypesv5QueryEnvelopeFormula) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5QueryEnvelopeFormula performs a merge with any union data inside the Querybuildertypesv5QueryEnvelope, using the provided Querybuildertypesv5QueryEnvelopeFormula
func (t *Querybuildertypesv5QueryEnvelope) MergeQuerybuildertypesv5QueryEnvelopeFormula(v Querybuildertypesv5QueryEnvelopeFormula) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQuerybuildertypesv5QueryEnvelopeTraceOperator returns the union data inside the Querybuildertypesv5QueryEnvelope as a Querybuildertypesv5QueryEnvelopeTraceOperator
func (t Querybuildertypesv5QueryEnvelope) AsQuerybuildertypesv5QueryEnvelopeTraceOperator() (Querybuildertypesv5QueryEnvelopeTraceOperator, error) {
	var body Querybuildertypesv5QueryEnvelopeTraceOperator
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5QueryEnvelopeTraceOperator overwrites any union data inside the Querybuildertypesv5QueryEnvelope as the provided Querybuildertypesv5QueryEnvelopeTraceOperator
func (t *Querybuildertypesv5QueryEnvelope) FromQuerybuildertypesv5QueryEnvelopeTraceOperator(v Querybuildertypesv5QueryEnvelopeTraceOperator) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5QueryEnvelopeTraceOperator performs a merge with any union data inside the Querybuildertypesv5QueryEnvelope, using the provided Querybuildertypesv5QueryEnvelopeTraceOperator
func (t *Querybuildertypesv5QueryEnvelope) MergeQuerybuildertypesv5QueryEnvelopeTraceOperator(v Querybuildertypesv5QueryEnvelopeTraceOperator) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQuerybuildertypesv5QueryEnvelopePromQL returns the union data inside the Querybuildertypesv5QueryEnvelope as a Querybuildertypesv5QueryEnvelopePromQL
func (t Querybuildertypesv5QueryEnvelope) AsQuerybuildertypesv5QueryEnvelopePromQL() (Querybuildertypesv5QueryEnvelopePromQL, error) {
	var body Querybuildertypesv5QueryEnvelopePromQL
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5QueryEnvelopePromQL overwrites any union data inside the Querybuildertypesv5QueryEnvelope as the provided Querybuildertypesv5QueryEnvelopePromQL
func (t *Querybuildertypesv5QueryEnvelope) FromQuerybuildertypesv5QueryEnvelopePromQL(v Querybuildertypesv5QueryEnvelopePromQL) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5QueryEnvelopePromQL performs a merge with any union data inside the Querybuildertypesv5QueryEnvelope, using the provided Querybuildertypesv5QueryEnvelopePromQL
func (t *Querybuildertypesv5QueryEnvelope) MergeQuerybuildertypesv5QueryEnvelopePromQL(v Querybuildertypesv5QueryEnvelopePromQL) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsQuerybuildertypesv5QueryEnvelopeClickHouseSQL returns the union data inside the Querybuildertypesv5QueryEnvelope as a Querybuildertypesv5QueryEnvelopeClickHouseSQL
func (t Querybuildertypesv5QueryEnvelope) AsQuerybuildertypesv5QueryEnvelopeClickHouseSQL() (Querybuildertypesv5QueryEnvelopeClickHouseSQL, error) {
	var body Querybuildertypesv5QueryEnvelopeClickHouseSQL
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromQuerybuildertypesv5QueryEnvelopeClickHouseSQL overwrites any union data inside the Querybuildertypesv5QueryEnvelope as the provided Querybuildertypesv5QueryEnvelopeClickHouseSQL
func (t *Querybuildertypesv5QueryEnvelope) FromQuerybuildertypesv5QueryEnvelopeClickHouseSQL(v Querybuildertypesv5QueryEnvelopeClickHouseSQL) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeQuerybuildertypesv5QueryEnvelopeClickHouseSQL performs a merge with any union data inside the Querybuildertypesv5QueryEnvelope, using the provided Querybuildertypesv5QueryEnvelopeClickHouseSQL
func (t *Querybuildertypesv5QueryEnvelope) MergeQuerybuildertypesv5QueryEnvelopeClickHouseSQL(v Querybuildertypesv5QueryEnvelopeClickHouseSQL) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Querybuildertypesv5QueryEnvelope) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	object["spec"], err = json.Marshal(t.Spec)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'spec': %w", err)
	}

	if t.Type != nil {
		object["type"], err = json.Marshal(t.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *Querybuildertypesv5QueryEnvelope) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["spec"]; found {
		err = json.Unmarshal(raw, &t.Spec)
		if err != nil {
			return fmt.Errorf("error reading 'spec': %w", err)
		}
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &t.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
	}

	return err
}
