// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

// DashboardtypesTablePanelSpec defines model for DashboardtypesTablePanelSpec.
type DashboardtypesTablePanelSpec struct {
	Formatting    *DashboardtypesTableFormatting    `json:"formatting,omitempty"`
	Thresholds    *[]DashboardtypesTableThreshold   `json:"thresholds,omitempty"`
	Visualization *DashboardtypesBasicVisualization `json:"visualization,omitempty"`
}
