// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

// SavedviewtypesUpdatableSavedView defines model for SavedviewtypesUpdatableSavedView.
type SavedviewtypesUpdatableSavedView struct {
	Data   SavedviewtypesSavedViewData `json:"data"`
	Source SavedviewtypesSource        `json:"source"`
}
