// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

// RuletypesRenotify defines model for RuletypesRenotify.
type RuletypesRenotify struct {
	AlertStates *[]RuletypesAlertState `json:"alertStates,omitempty"`
	Enabled     *bool                  `json:"enabled,omitempty"`
	Interval    *string                `json:"interval,omitempty"`
}
