// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

// Defines values for DashboardtypesThresholdFormat.
const (
	DashboardtypesThresholdFormatBackground DashboardtypesThresholdFormat = "background"
	DashboardtypesThresholdFormatText       DashboardtypesThresholdFormat = "text"
)

// Valid indicates whether the value is a known member of the DashboardtypesThresholdFormat enum.
func (e DashboardtypesThresholdFormat) Valid() bool {
	switch e {
	case DashboardtypesThresholdFormatBackground:
		return true
	case DashboardtypesThresholdFormatText:
		return true
	default:
		return false
	}
}

// DashboardtypesThresholdFormat defines model for DashboardtypesThresholdFormat.
type DashboardtypesThresholdFormat string
