// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

// AlertmanagertypesPostableNotificationChannel defines model for AlertmanagertypesPostableNotificationChannel.
type AlertmanagertypesPostableNotificationChannel struct {
	Config       AlertmanagertypesChannelConfig `json:"config"`
	DisplayName  *string                        `json:"displayName,omitempty"`
	GenerateName *bool                          `json:"generateName,omitempty"`
	Name         *string                        `json:"name,omitempty"`
}
