// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

// DashboardtypesDashboardSpec defines model for DashboardtypesDashboardSpec.
type DashboardtypesDashboardSpec struct {
	Datasources     *map[string]DashboardtypesDatasourceSpec `json:"datasources,omitempty"`
	Display         DashboardtypesDisplay                    `json:"display"`
	Duration        *string                                  `json:"duration,omitempty"`
	Layouts         []DashboardtypesLayout                   `json:"layouts"`
	Links           *[]DashboardtypesLink                    `json:"links,omitempty"`
	Panels          map[string]DashboardtypesPanel           `json:"panels"`
	RefreshInterval *string                                  `json:"refreshInterval,omitempty"`
	Variables       []DashboardtypesVariable                 `json:"variables"`
}
