// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

// Querybuildertypesv5LinearBucketsSpec defines model for Querybuildertypesv5LinearBucketsSpec.
type Querybuildertypesv5LinearBucketsSpec struct {
	MaxValue   float64 `json:"maxValue"`
	NumBuckets *int    `json:"numBuckets,omitempty"`
}
