// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

// Querybuildertypesv5QueryEnvelopeBuilderLog defines model for Querybuildertypesv5QueryEnvelopeBuilderLog.
type Querybuildertypesv5QueryEnvelopeBuilderLog struct {
	Spec *Querybuildertypesv5QueryBuilderQueryGithubComSigNozSignozPkgTypesQuerybuildertypesQuerybuildertypesv5LogAggregation `json:"spec,omitempty"`
	Type *Querybuildertypesv5QueryType                                                                                        `json:"type,omitempty"`
}
