// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

// RuletypesCumulativeWindow defines model for RuletypesCumulativeWindow.
type RuletypesCumulativeWindow struct {
	Frequency string                      `json:"frequency"`
	Schedule  RuletypesCumulativeSchedule `json:"schedule"`
	Timezone  string                      `json:"timezone"`
}
