// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

// ErrorsJSON defines model for ErrorsJSON.
type ErrorsJSON struct {
	Code    string                           `json:"code"`
	Errors  *[]ErrorsResponseerroradditional `json:"errors,omitempty"`
	Message string                           `json:"message"`
	Url     *string                          `json:"url,omitempty"`
}
