// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

// Defines values for AlertmanagertypesExpressionKind.
const (
	AlertmanagertypesExpressionKindPolicy AlertmanagertypesExpressionKind = "policy"
	AlertmanagertypesExpressionKindRule   AlertmanagertypesExpressionKind = "rule"
)

// Valid indicates whether the value is a known member of the AlertmanagertypesExpressionKind enum.
func (e AlertmanagertypesExpressionKind) Valid() bool {
	switch e {
	case AlertmanagertypesExpressionKindPolicy:
		return true
	case AlertmanagertypesExpressionKindRule:
		return true
	default:
		return false
	}
}

// AlertmanagertypesExpressionKind defines model for AlertmanagertypesExpressionKind.
type AlertmanagertypesExpressionKind string
