// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

// Defines values for DashboardtypesPrecisionOption.
const (
	DashboardtypesPrecisionOptionFull DashboardtypesPrecisionOption = "full"
	DashboardtypesPrecisionOptionN0   DashboardtypesPrecisionOption = "0"
	DashboardtypesPrecisionOptionN1   DashboardtypesPrecisionOption = "1"
	DashboardtypesPrecisionOptionN2   DashboardtypesPrecisionOption = "2"
	DashboardtypesPrecisionOptionN3   DashboardtypesPrecisionOption = "3"
	DashboardtypesPrecisionOptionN4   DashboardtypesPrecisionOption = "4"
)

// Valid indicates whether the value is a known member of the DashboardtypesPrecisionOption enum.
func (e DashboardtypesPrecisionOption) Valid() bool {
	switch e {
	case DashboardtypesPrecisionOptionFull:
		return true
	case DashboardtypesPrecisionOptionN0:
		return true
	case DashboardtypesPrecisionOptionN1:
		return true
	case DashboardtypesPrecisionOptionN2:
		return true
	case DashboardtypesPrecisionOptionN3:
		return true
	case DashboardtypesPrecisionOptionN4:
		return true
	default:
		return false
	}
}

// DashboardtypesPrecisionOption defines model for DashboardtypesPrecisionOption.
type DashboardtypesPrecisionOption string
