// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

// ConfigPushoverConfig defines model for ConfigPushoverConfig.
type ConfigPushoverConfig struct {
	Device       *string                 `json:"device,omitempty"`
	Expire       *ConfigDuration         `json:"expire,omitempty"`
	Html         *bool                   `json:"html,omitempty"`
	HttpConfig   *ConfigHTTPClientConfig `json:"http_config,omitempty"`
	Message      *string                 `json:"message,omitempty"`
	Monospace    *bool                   `json:"monospace,omitempty"`
	Priority     *string                 `json:"priority,omitempty"`
	Retry        *ConfigDuration         `json:"retry,omitempty"`
	SendResolved *bool                   `json:"send_resolved,omitempty"`
	Sound        *string                 `json:"sound,omitempty"`
	Title        *string                 `json:"title,omitempty"`
	Token        *string                 `json:"token,omitempty"`
	TokenFile    *string                 `json:"token_file,omitempty"`
	Ttl          *ConfigDuration         `json:"ttl,omitempty"`
	Url          *string                 `json:"url,omitempty"`
	UrlTitle     *string                 `json:"url_title,omitempty"`
	UserKey      *string                 `json:"user_key,omitempty"`
	UserKeyFile  *string                 `json:"user_key_file,omitempty"`
}
