// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

// ConfigHeaders defines model for ConfigHeaders.
type ConfigHeaders = map[string]interface{}
