// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

import (
	"time"
)

// RuletypesPlannedMaintenance defines model for RuletypesPlannedMaintenance.
type RuletypesPlannedMaintenance struct {
	AlertIds    *[]string                  `json:"alertIds,omitempty"`
	CreatedAt   *time.Time                 `json:"createdAt,omitempty"`
	CreatedBy   *string                    `json:"createdBy,omitempty"`
	Description *string                    `json:"description,omitempty"`
	Id          string                     `json:"id"`
	Kind        RuletypesMaintenanceKind   `json:"kind"`
	Name        string                     `json:"name"`
	Schedule    RuletypesSchedule          `json:"schedule"`
	Status      RuletypesMaintenanceStatus `json:"status"`
	UpdatedAt   *time.Time                 `json:"updatedAt,omitempty"`
	UpdatedBy   *string                    `json:"updatedBy,omitempty"`
}
