// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

// ConfigMattermostAttachment defines model for ConfigMattermostAttachment.
type ConfigMattermostAttachment struct {
	AuthorIcon *string                  `json:"author_icon,omitempty"`
	AuthorLink *string                  `json:"author_link,omitempty"`
	AuthorName *string                  `json:"author_name,omitempty"`
	Color      *string                  `json:"color,omitempty"`
	Fallback   *string                  `json:"fallback,omitempty"`
	Fields     *[]ConfigMattermostField `json:"fields,omitempty"`
	Footer     *string                  `json:"footer,omitempty"`
	FooterIcon *string                  `json:"footer_icon,omitempty"`
	ImageUrl   *string                  `json:"image_url,omitempty"`
	Pretext    *string                  `json:"pretext,omitempty"`
	Text       *string                  `json:"text,omitempty"`
	ThumbUrl   *string                  `json:"thumb_url,omitempty"`
	Title      *string                  `json:"title,omitempty"`
	TitleLink  *string                  `json:"title_link,omitempty"`
}
