// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apitypes

// DashboardtypesLegend defines model for DashboardtypesLegend.
type DashboardtypesLegend struct {
	CustomColors *map[string]string            `json:"customColors,omitempty"`
	Mode         *DashboardtypesLegendMode     `json:"mode,omitempty"`
	Position     *DashboardtypesLegendPosition `json:"position,omitempty"`
}
