package attr

const (
	// Dashboard = "dashboard"
	// UUID      = "uuid"
	// Title     = "title"
	// Tags      = "tags"
	// Variables = "variables"
	// Layout    = "layout"
	// Widgets   = "widgets"
	// CreatedAt = "created_at"
	// CreatedBy = "created_by"
	// UpdatedAt = "updated_at"
	// UpdatedBy = "updated_by"

	// Description             = "description"
	// Version                 = "version"
	CollapsableRowsMigrated = "collapsable_rows_migrated"
	Layout                  = "layout"
	Name                    = "name"
	PanelMap                = "panel_map"
	Tags                    = "tags"
	Title                   = "title"
	UploadedGrafana         = "uploaded_grafana"
	Variables               = "variables"
	Widgets                 = "widgets"
	CreatedAt               = "created_at"
	CreatedBy               = "created_by"
	UpdatedAt               = "updated_at"
	UpdatedBy               = "updated_by"
	UUID                    = "uuid"
	// ID                      = "id"
)
