// Code generated by skaff types DO NOT EDIT.

package customtypes

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
)

var _ basetypes.ObjectTypable = AlertmanagertypesChannelGoogleChatConfigType{}

type AlertmanagertypesChannelGoogleChatConfigType struct {
	basetypes.ObjectType
}

func (t AlertmanagertypesChannelGoogleChatConfigType) Equal(o attr.Type) bool {
	other, ok := o.(AlertmanagertypesChannelGoogleChatConfigType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AlertmanagertypesChannelGoogleChatConfigType) String() string {
	return "AlertmanagertypesChannelGoogleChatConfigType"
}

func (t AlertmanagertypesChannelGoogleChatConfigType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	sendResolvedAttribute, ok := attributes["send_resolved"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`send_resolved is missing from object`)

		return nil, diags
	}

	sendResolvedVal, ok := sendResolvedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`send_resolved expected to be basetypes.BoolValue, was: %T`, sendResolvedAttribute))
	}

	textAttribute, ok := attributes["text"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`text is missing from object`)

		return nil, diags
	}

	textVal, ok := textAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`text expected to be basetypes.StringValue, was: %T`, textAttribute))
	}

	titleAttribute, ok := attributes["title"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`title is missing from object`)

		return nil, diags
	}

	titleVal, ok := titleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`title expected to be basetypes.StringValue, was: %T`, titleAttribute))
	}

	webhookUrlAttribute, ok := attributes["webhook_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`webhook_url is missing from object`)

		return nil, diags
	}

	webhookUrlVal, ok := webhookUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`webhook_url expected to be basetypes.StringValue, was: %T`, webhookUrlAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AlertmanagertypesChannelGoogleChatConfigValue{
		SendResolved: sendResolvedVal,
		Text:         textVal,
		Title:        titleVal,
		WebhookUrl:   webhookUrlVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewAlertmanagertypesChannelGoogleChatConfigValueNull() AlertmanagertypesChannelGoogleChatConfigValue {
	return AlertmanagertypesChannelGoogleChatConfigValue{
		state: attr.ValueStateNull,
	}
}

func NewAlertmanagertypesChannelGoogleChatConfigValueUnknown() AlertmanagertypesChannelGoogleChatConfigValue {
	return AlertmanagertypesChannelGoogleChatConfigValue{
		state: attr.ValueStateUnknown,
	}
}

func NewAlertmanagertypesChannelGoogleChatConfigValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AlertmanagertypesChannelGoogleChatConfigValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AlertmanagertypesChannelGoogleChatConfigValue Attribute Value",
				"While creating a AlertmanagertypesChannelGoogleChatConfigValue value, a missing attribute value was detected. "+
					"A AlertmanagertypesChannelGoogleChatConfigValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AlertmanagertypesChannelGoogleChatConfigValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AlertmanagertypesChannelGoogleChatConfigValue Attribute Type",
				"While creating a AlertmanagertypesChannelGoogleChatConfigValue value, an invalid attribute value was detected. "+
					"A AlertmanagertypesChannelGoogleChatConfigValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AlertmanagertypesChannelGoogleChatConfigValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AlertmanagertypesChannelGoogleChatConfigValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AlertmanagertypesChannelGoogleChatConfigValue Attribute Value",
				"While creating a AlertmanagertypesChannelGoogleChatConfigValue value, an extra attribute value was detected. "+
					"A AlertmanagertypesChannelGoogleChatConfigValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AlertmanagertypesChannelGoogleChatConfigValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewAlertmanagertypesChannelGoogleChatConfigValueUnknown(), diags
	}

	sendResolvedAttribute, ok := attributes["send_resolved"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`send_resolved is missing from object`)

		return NewAlertmanagertypesChannelGoogleChatConfigValueUnknown(), diags
	}

	sendResolvedVal, ok := sendResolvedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`send_resolved expected to be basetypes.BoolValue, was: %T`, sendResolvedAttribute))
	}

	textAttribute, ok := attributes["text"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`text is missing from object`)

		return NewAlertmanagertypesChannelGoogleChatConfigValueUnknown(), diags
	}

	textVal, ok := textAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`text expected to be basetypes.StringValue, was: %T`, textAttribute))
	}

	titleAttribute, ok := attributes["title"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`title is missing from object`)

		return NewAlertmanagertypesChannelGoogleChatConfigValueUnknown(), diags
	}

	titleVal, ok := titleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`title expected to be basetypes.StringValue, was: %T`, titleAttribute))
	}

	webhookUrlAttribute, ok := attributes["webhook_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`webhook_url is missing from object`)

		return NewAlertmanagertypesChannelGoogleChatConfigValueUnknown(), diags
	}

	webhookUrlVal, ok := webhookUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`webhook_url expected to be basetypes.StringValue, was: %T`, webhookUrlAttribute))
	}

	if diags.HasError() {
		return NewAlertmanagertypesChannelGoogleChatConfigValueUnknown(), diags
	}

	return AlertmanagertypesChannelGoogleChatConfigValue{
		SendResolved: sendResolvedVal,
		Text:         textVal,
		Title:        titleVal,
		WebhookUrl:   webhookUrlVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewAlertmanagertypesChannelGoogleChatConfigValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AlertmanagertypesChannelGoogleChatConfigValue {
	object, diags := NewAlertmanagertypesChannelGoogleChatConfigValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewAlertmanagertypesChannelGoogleChatConfigValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AlertmanagertypesChannelGoogleChatConfigType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewAlertmanagertypesChannelGoogleChatConfigValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewAlertmanagertypesChannelGoogleChatConfigValueUnknown(), nil
	}

	if in.IsNull() {
		return NewAlertmanagertypesChannelGoogleChatConfigValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewAlertmanagertypesChannelGoogleChatConfigValueMust(AlertmanagertypesChannelGoogleChatConfigValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AlertmanagertypesChannelGoogleChatConfigType) ValueType(ctx context.Context) attr.Value {
	return AlertmanagertypesChannelGoogleChatConfigValue{}
}

var _ basetypes.ObjectValuable = AlertmanagertypesChannelGoogleChatConfigValue{}

type AlertmanagertypesChannelGoogleChatConfigValue struct {
	SendResolved basetypes.BoolValue   `tfsdk:"send_resolved"`
	Text         basetypes.StringValue `tfsdk:"text"`
	Title        basetypes.StringValue `tfsdk:"title"`
	WebhookUrl   basetypes.StringValue `tfsdk:"webhook_url"`
	state        attr.ValueState
}

func (v AlertmanagertypesChannelGoogleChatConfigValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["send_resolved"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["text"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["title"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["webhook_url"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.SendResolved.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["send_resolved"] = val

		val, err = v.Text.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["text"] = val

		val, err = v.Title.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["title"] = val

		val, err = v.WebhookUrl.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["webhook_url"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AlertmanagertypesChannelGoogleChatConfigValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AlertmanagertypesChannelGoogleChatConfigValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AlertmanagertypesChannelGoogleChatConfigValue) String() string {
	return "AlertmanagertypesChannelGoogleChatConfigValue"
}

func (v AlertmanagertypesChannelGoogleChatConfigValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"send_resolved": basetypes.BoolType{},
		"text":          basetypes.StringType{},
		"title":         basetypes.StringType{},
		"webhook_url":   basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"send_resolved": v.SendResolved,
			"text":          v.Text,
			"title":         v.Title,
			"webhook_url":   v.WebhookUrl,
		})

	return objVal, diags
}

func (v AlertmanagertypesChannelGoogleChatConfigValue) Equal(o attr.Value) bool {
	other, ok := o.(AlertmanagertypesChannelGoogleChatConfigValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.SendResolved.Equal(other.SendResolved) {
		return false
	}

	if !v.Text.Equal(other.Text) {
		return false
	}

	if !v.Title.Equal(other.Title) {
		return false
	}

	if !v.WebhookUrl.Equal(other.WebhookUrl) {
		return false
	}

	return true
}

func (v AlertmanagertypesChannelGoogleChatConfigValue) Type(ctx context.Context) attr.Type {
	return AlertmanagertypesChannelGoogleChatConfigType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AlertmanagertypesChannelGoogleChatConfigValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"send_resolved": basetypes.BoolType{},
		"text":          basetypes.StringType{},
		"title":         basetypes.StringType{},
		"webhook_url":   basetypes.StringType{},
	}
}
