// Code generated by skaff types DO NOT EDIT.

package customtypes

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
)

var _ basetypes.ObjectTypable = DashboardtypesDynamicVariableSpecType{}

type DashboardtypesDynamicVariableSpecType struct {
	basetypes.ObjectType
}

func (t DashboardtypesDynamicVariableSpecType) Equal(o attr.Type) bool {
	other, ok := o.(DashboardtypesDynamicVariableSpecType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DashboardtypesDynamicVariableSpecType) String() string {
	return "DashboardtypesDynamicVariableSpecType"
}

func (t DashboardtypesDynamicVariableSpecType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	signalAttribute, ok := attributes["signal"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`signal is missing from object`)

		return nil, diags
	}

	signalVal, ok := signalAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`signal expected to be basetypes.StringValue, was: %T`, signalAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DashboardtypesDynamicVariableSpecValue{
		Name:   nameVal,
		Signal: signalVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewDashboardtypesDynamicVariableSpecValueNull() DashboardtypesDynamicVariableSpecValue {
	return DashboardtypesDynamicVariableSpecValue{
		state: attr.ValueStateNull,
	}
}

func NewDashboardtypesDynamicVariableSpecValueUnknown() DashboardtypesDynamicVariableSpecValue {
	return DashboardtypesDynamicVariableSpecValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDashboardtypesDynamicVariableSpecValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DashboardtypesDynamicVariableSpecValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DashboardtypesDynamicVariableSpecValue Attribute Value",
				"While creating a DashboardtypesDynamicVariableSpecValue value, a missing attribute value was detected. "+
					"A DashboardtypesDynamicVariableSpecValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DashboardtypesDynamicVariableSpecValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DashboardtypesDynamicVariableSpecValue Attribute Type",
				"While creating a DashboardtypesDynamicVariableSpecValue value, an invalid attribute value was detected. "+
					"A DashboardtypesDynamicVariableSpecValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DashboardtypesDynamicVariableSpecValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DashboardtypesDynamicVariableSpecValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DashboardtypesDynamicVariableSpecValue Attribute Value",
				"While creating a DashboardtypesDynamicVariableSpecValue value, an extra attribute value was detected. "+
					"A DashboardtypesDynamicVariableSpecValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DashboardtypesDynamicVariableSpecValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDashboardtypesDynamicVariableSpecValueUnknown(), diags
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewDashboardtypesDynamicVariableSpecValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	signalAttribute, ok := attributes["signal"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`signal is missing from object`)

		return NewDashboardtypesDynamicVariableSpecValueUnknown(), diags
	}

	signalVal, ok := signalAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`signal expected to be basetypes.StringValue, was: %T`, signalAttribute))
	}

	if diags.HasError() {
		return NewDashboardtypesDynamicVariableSpecValueUnknown(), diags
	}

	return DashboardtypesDynamicVariableSpecValue{
		Name:   nameVal,
		Signal: signalVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewDashboardtypesDynamicVariableSpecValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DashboardtypesDynamicVariableSpecValue {
	object, diags := NewDashboardtypesDynamicVariableSpecValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDashboardtypesDynamicVariableSpecValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DashboardtypesDynamicVariableSpecType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDashboardtypesDynamicVariableSpecValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDashboardtypesDynamicVariableSpecValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDashboardtypesDynamicVariableSpecValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDashboardtypesDynamicVariableSpecValueMust(DashboardtypesDynamicVariableSpecValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DashboardtypesDynamicVariableSpecType) ValueType(ctx context.Context) attr.Value {
	return DashboardtypesDynamicVariableSpecValue{}
}

var _ basetypes.ObjectValuable = DashboardtypesDynamicVariableSpecValue{}

type DashboardtypesDynamicVariableSpecValue struct {
	Name   basetypes.StringValue `tfsdk:"name"`
	Signal basetypes.StringValue `tfsdk:"signal"`
	state  attr.ValueState
}

func (v DashboardtypesDynamicVariableSpecValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["signal"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Signal.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["signal"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DashboardtypesDynamicVariableSpecValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DashboardtypesDynamicVariableSpecValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DashboardtypesDynamicVariableSpecValue) String() string {
	return "DashboardtypesDynamicVariableSpecValue"
}

func (v DashboardtypesDynamicVariableSpecValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"name":   basetypes.StringType{},
		"signal": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"name":   v.Name,
			"signal": v.Signal,
		})

	return objVal, diags
}

func (v DashboardtypesDynamicVariableSpecValue) Equal(o attr.Value) bool {
	other, ok := o.(DashboardtypesDynamicVariableSpecValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Signal.Equal(other.Signal) {
		return false
	}

	return true
}

func (v DashboardtypesDynamicVariableSpecValue) Type(ctx context.Context) attr.Type {
	return DashboardtypesDynamicVariableSpecType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DashboardtypesDynamicVariableSpecValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"name":   basetypes.StringType{},
		"signal": basetypes.StringType{},
	}
}
