// Code generated by skaff types DO NOT EDIT.

package customtypes

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
)

var _ basetypes.ObjectTypable = DashboardtypesPanelPluginType{}

type DashboardtypesPanelPluginType struct {
	basetypes.ObjectType
}

func (t DashboardtypesPanelPluginType) Equal(o attr.Type) bool {
	other, ok := o.(DashboardtypesPanelPluginType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DashboardtypesPanelPluginType) String() string {
	return "DashboardtypesPanelPluginType"
}

func (t DashboardtypesPanelPluginType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	barChartPanelAttribute, ok := attributes["bar_chart_panel"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`bar_chart_panel is missing from object`)

		return nil, diags
	}

	barChartPanelVal, ok := barChartPanelAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`bar_chart_panel expected to be basetypes.ObjectValue, was: %T`, barChartPanelAttribute))
	}

	histogramPanelAttribute, ok := attributes["histogram_panel"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`histogram_panel is missing from object`)

		return nil, diags
	}

	histogramPanelVal, ok := histogramPanelAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`histogram_panel expected to be basetypes.ObjectValue, was: %T`, histogramPanelAttribute))
	}

	listPanelAttribute, ok := attributes["list_panel"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`list_panel is missing from object`)

		return nil, diags
	}

	listPanelVal, ok := listPanelAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`list_panel expected to be basetypes.ObjectValue, was: %T`, listPanelAttribute))
	}

	numberPanelAttribute, ok := attributes["number_panel"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`number_panel is missing from object`)

		return nil, diags
	}

	numberPanelVal, ok := numberPanelAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`number_panel expected to be basetypes.ObjectValue, was: %T`, numberPanelAttribute))
	}

	pieChartPanelAttribute, ok := attributes["pie_chart_panel"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`pie_chart_panel is missing from object`)

		return nil, diags
	}

	pieChartPanelVal, ok := pieChartPanelAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`pie_chart_panel expected to be basetypes.ObjectValue, was: %T`, pieChartPanelAttribute))
	}

	tablePanelAttribute, ok := attributes["table_panel"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`table_panel is missing from object`)

		return nil, diags
	}

	tablePanelVal, ok := tablePanelAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`table_panel expected to be basetypes.ObjectValue, was: %T`, tablePanelAttribute))
	}

	timeSeriesPanelAttribute, ok := attributes["time_series_panel"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`time_series_panel is missing from object`)

		return nil, diags
	}

	timeSeriesPanelVal, ok := timeSeriesPanelAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`time_series_panel expected to be basetypes.ObjectValue, was: %T`, timeSeriesPanelAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DashboardtypesPanelPluginValue{
		BarChartPanel:   barChartPanelVal,
		HistogramPanel:  histogramPanelVal,
		ListPanel:       listPanelVal,
		NumberPanel:     numberPanelVal,
		PieChartPanel:   pieChartPanelVal,
		TablePanel:      tablePanelVal,
		TimeSeriesPanel: timeSeriesPanelVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewDashboardtypesPanelPluginValueNull() DashboardtypesPanelPluginValue {
	return DashboardtypesPanelPluginValue{
		state: attr.ValueStateNull,
	}
}

func NewDashboardtypesPanelPluginValueUnknown() DashboardtypesPanelPluginValue {
	return DashboardtypesPanelPluginValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDashboardtypesPanelPluginValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DashboardtypesPanelPluginValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DashboardtypesPanelPluginValue Attribute Value",
				"While creating a DashboardtypesPanelPluginValue value, a missing attribute value was detected. "+
					"A DashboardtypesPanelPluginValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DashboardtypesPanelPluginValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DashboardtypesPanelPluginValue Attribute Type",
				"While creating a DashboardtypesPanelPluginValue value, an invalid attribute value was detected. "+
					"A DashboardtypesPanelPluginValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DashboardtypesPanelPluginValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DashboardtypesPanelPluginValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DashboardtypesPanelPluginValue Attribute Value",
				"While creating a DashboardtypesPanelPluginValue value, an extra attribute value was detected. "+
					"A DashboardtypesPanelPluginValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DashboardtypesPanelPluginValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDashboardtypesPanelPluginValueUnknown(), diags
	}

	barChartPanelAttribute, ok := attributes["bar_chart_panel"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`bar_chart_panel is missing from object`)

		return NewDashboardtypesPanelPluginValueUnknown(), diags
	}

	barChartPanelVal, ok := barChartPanelAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`bar_chart_panel expected to be basetypes.ObjectValue, was: %T`, barChartPanelAttribute))
	}

	histogramPanelAttribute, ok := attributes["histogram_panel"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`histogram_panel is missing from object`)

		return NewDashboardtypesPanelPluginValueUnknown(), diags
	}

	histogramPanelVal, ok := histogramPanelAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`histogram_panel expected to be basetypes.ObjectValue, was: %T`, histogramPanelAttribute))
	}

	listPanelAttribute, ok := attributes["list_panel"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`list_panel is missing from object`)

		return NewDashboardtypesPanelPluginValueUnknown(), diags
	}

	listPanelVal, ok := listPanelAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`list_panel expected to be basetypes.ObjectValue, was: %T`, listPanelAttribute))
	}

	numberPanelAttribute, ok := attributes["number_panel"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`number_panel is missing from object`)

		return NewDashboardtypesPanelPluginValueUnknown(), diags
	}

	numberPanelVal, ok := numberPanelAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`number_panel expected to be basetypes.ObjectValue, was: %T`, numberPanelAttribute))
	}

	pieChartPanelAttribute, ok := attributes["pie_chart_panel"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`pie_chart_panel is missing from object`)

		return NewDashboardtypesPanelPluginValueUnknown(), diags
	}

	pieChartPanelVal, ok := pieChartPanelAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`pie_chart_panel expected to be basetypes.ObjectValue, was: %T`, pieChartPanelAttribute))
	}

	tablePanelAttribute, ok := attributes["table_panel"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`table_panel is missing from object`)

		return NewDashboardtypesPanelPluginValueUnknown(), diags
	}

	tablePanelVal, ok := tablePanelAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`table_panel expected to be basetypes.ObjectValue, was: %T`, tablePanelAttribute))
	}

	timeSeriesPanelAttribute, ok := attributes["time_series_panel"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`time_series_panel is missing from object`)

		return NewDashboardtypesPanelPluginValueUnknown(), diags
	}

	timeSeriesPanelVal, ok := timeSeriesPanelAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`time_series_panel expected to be basetypes.ObjectValue, was: %T`, timeSeriesPanelAttribute))
	}

	if diags.HasError() {
		return NewDashboardtypesPanelPluginValueUnknown(), diags
	}

	return DashboardtypesPanelPluginValue{
		BarChartPanel:   barChartPanelVal,
		HistogramPanel:  histogramPanelVal,
		ListPanel:       listPanelVal,
		NumberPanel:     numberPanelVal,
		PieChartPanel:   pieChartPanelVal,
		TablePanel:      tablePanelVal,
		TimeSeriesPanel: timeSeriesPanelVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewDashboardtypesPanelPluginValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DashboardtypesPanelPluginValue {
	object, diags := NewDashboardtypesPanelPluginValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDashboardtypesPanelPluginValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DashboardtypesPanelPluginType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDashboardtypesPanelPluginValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDashboardtypesPanelPluginValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDashboardtypesPanelPluginValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDashboardtypesPanelPluginValueMust(DashboardtypesPanelPluginValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DashboardtypesPanelPluginType) ValueType(ctx context.Context) attr.Value {
	return DashboardtypesPanelPluginValue{}
}

var _ basetypes.ObjectValuable = DashboardtypesPanelPluginValue{}

type DashboardtypesPanelPluginValue struct {
	BarChartPanel   basetypes.ObjectValue `tfsdk:"bar_chart_panel"`
	HistogramPanel  basetypes.ObjectValue `tfsdk:"histogram_panel"`
	ListPanel       basetypes.ObjectValue `tfsdk:"list_panel"`
	NumberPanel     basetypes.ObjectValue `tfsdk:"number_panel"`
	PieChartPanel   basetypes.ObjectValue `tfsdk:"pie_chart_panel"`
	TablePanel      basetypes.ObjectValue `tfsdk:"table_panel"`
	TimeSeriesPanel basetypes.ObjectValue `tfsdk:"time_series_panel"`
	state           attr.ValueState
}

func (v DashboardtypesPanelPluginValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 7)

	var val tftypes.Value
	var err error

	attrTypes["bar_chart_panel"] = basetypes.ObjectType{
		AttrTypes: DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesBarChartPanelSpecValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["histogram_panel"] = basetypes.ObjectType{
		AttrTypes: DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["list_panel"] = basetypes.ObjectType{
		AttrTypes: DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesListPanelSpecValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["number_panel"] = basetypes.ObjectType{
		AttrTypes: DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesNumberPanelSpecValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["pie_chart_panel"] = basetypes.ObjectType{
		AttrTypes: DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesPieChartPanelSpecValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["table_panel"] = basetypes.ObjectType{
		AttrTypes: DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesTablePanelSpecValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["time_series_panel"] = basetypes.ObjectType{
		AttrTypes: DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesTimeSeriesPanelSpecValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 7)

		val, err = v.BarChartPanel.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["bar_chart_panel"] = val

		val, err = v.HistogramPanel.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["histogram_panel"] = val

		val, err = v.ListPanel.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["list_panel"] = val

		val, err = v.NumberPanel.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["number_panel"] = val

		val, err = v.PieChartPanel.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["pie_chart_panel"] = val

		val, err = v.TablePanel.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["table_panel"] = val

		val, err = v.TimeSeriesPanel.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["time_series_panel"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DashboardtypesPanelPluginValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DashboardtypesPanelPluginValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DashboardtypesPanelPluginValue) String() string {
	return "DashboardtypesPanelPluginValue"
}

func (v DashboardtypesPanelPluginValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var barChartPanel basetypes.ObjectValue

	if v.BarChartPanel.IsNull() {
		barChartPanel = types.ObjectNull(
			DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesBarChartPanelSpecValue{}.AttributeTypes(ctx),
		)
	}

	if v.BarChartPanel.IsUnknown() {
		barChartPanel = types.ObjectUnknown(
			DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesBarChartPanelSpecValue{}.AttributeTypes(ctx),
		)
	}

	if !v.BarChartPanel.IsNull() && !v.BarChartPanel.IsUnknown() {
		barChartPanel = types.ObjectValueMust(
			DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesBarChartPanelSpecValue{}.AttributeTypes(ctx),
			v.BarChartPanel.Attributes(),
		)
	}

	var histogramPanel basetypes.ObjectValue

	if v.HistogramPanel.IsNull() {
		histogramPanel = types.ObjectNull(
			DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValue{}.AttributeTypes(ctx),
		)
	}

	if v.HistogramPanel.IsUnknown() {
		histogramPanel = types.ObjectUnknown(
			DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValue{}.AttributeTypes(ctx),
		)
	}

	if !v.HistogramPanel.IsNull() && !v.HistogramPanel.IsUnknown() {
		histogramPanel = types.ObjectValueMust(
			DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValue{}.AttributeTypes(ctx),
			v.HistogramPanel.Attributes(),
		)
	}

	var listPanel basetypes.ObjectValue

	if v.ListPanel.IsNull() {
		listPanel = types.ObjectNull(
			DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesListPanelSpecValue{}.AttributeTypes(ctx),
		)
	}

	if v.ListPanel.IsUnknown() {
		listPanel = types.ObjectUnknown(
			DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesListPanelSpecValue{}.AttributeTypes(ctx),
		)
	}

	if !v.ListPanel.IsNull() && !v.ListPanel.IsUnknown() {
		listPanel = types.ObjectValueMust(
			DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesListPanelSpecValue{}.AttributeTypes(ctx),
			v.ListPanel.Attributes(),
		)
	}

	var numberPanel basetypes.ObjectValue

	if v.NumberPanel.IsNull() {
		numberPanel = types.ObjectNull(
			DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesNumberPanelSpecValue{}.AttributeTypes(ctx),
		)
	}

	if v.NumberPanel.IsUnknown() {
		numberPanel = types.ObjectUnknown(
			DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesNumberPanelSpecValue{}.AttributeTypes(ctx),
		)
	}

	if !v.NumberPanel.IsNull() && !v.NumberPanel.IsUnknown() {
		numberPanel = types.ObjectValueMust(
			DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesNumberPanelSpecValue{}.AttributeTypes(ctx),
			v.NumberPanel.Attributes(),
		)
	}

	var pieChartPanel basetypes.ObjectValue

	if v.PieChartPanel.IsNull() {
		pieChartPanel = types.ObjectNull(
			DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesPieChartPanelSpecValue{}.AttributeTypes(ctx),
		)
	}

	if v.PieChartPanel.IsUnknown() {
		pieChartPanel = types.ObjectUnknown(
			DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesPieChartPanelSpecValue{}.AttributeTypes(ctx),
		)
	}

	if !v.PieChartPanel.IsNull() && !v.PieChartPanel.IsUnknown() {
		pieChartPanel = types.ObjectValueMust(
			DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesPieChartPanelSpecValue{}.AttributeTypes(ctx),
			v.PieChartPanel.Attributes(),
		)
	}

	var tablePanel basetypes.ObjectValue

	if v.TablePanel.IsNull() {
		tablePanel = types.ObjectNull(
			DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesTablePanelSpecValue{}.AttributeTypes(ctx),
		)
	}

	if v.TablePanel.IsUnknown() {
		tablePanel = types.ObjectUnknown(
			DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesTablePanelSpecValue{}.AttributeTypes(ctx),
		)
	}

	if !v.TablePanel.IsNull() && !v.TablePanel.IsUnknown() {
		tablePanel = types.ObjectValueMust(
			DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesTablePanelSpecValue{}.AttributeTypes(ctx),
			v.TablePanel.Attributes(),
		)
	}

	var timeSeriesPanel basetypes.ObjectValue

	if v.TimeSeriesPanel.IsNull() {
		timeSeriesPanel = types.ObjectNull(
			DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesTimeSeriesPanelSpecValue{}.AttributeTypes(ctx),
		)
	}

	if v.TimeSeriesPanel.IsUnknown() {
		timeSeriesPanel = types.ObjectUnknown(
			DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesTimeSeriesPanelSpecValue{}.AttributeTypes(ctx),
		)
	}

	if !v.TimeSeriesPanel.IsNull() && !v.TimeSeriesPanel.IsUnknown() {
		timeSeriesPanel = types.ObjectValueMust(
			DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesTimeSeriesPanelSpecValue{}.AttributeTypes(ctx),
			v.TimeSeriesPanel.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"bar_chart_panel": basetypes.ObjectType{
			AttrTypes: DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesBarChartPanelSpecValue{}.AttributeTypes(ctx),
		},
		"histogram_panel": basetypes.ObjectType{
			AttrTypes: DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValue{}.AttributeTypes(ctx),
		},
		"list_panel": basetypes.ObjectType{
			AttrTypes: DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesListPanelSpecValue{}.AttributeTypes(ctx),
		},
		"number_panel": basetypes.ObjectType{
			AttrTypes: DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesNumberPanelSpecValue{}.AttributeTypes(ctx),
		},
		"pie_chart_panel": basetypes.ObjectType{
			AttrTypes: DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesPieChartPanelSpecValue{}.AttributeTypes(ctx),
		},
		"table_panel": basetypes.ObjectType{
			AttrTypes: DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesTablePanelSpecValue{}.AttributeTypes(ctx),
		},
		"time_series_panel": basetypes.ObjectType{
			AttrTypes: DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesTimeSeriesPanelSpecValue{}.AttributeTypes(ctx),
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"bar_chart_panel":   barChartPanel,
			"histogram_panel":   histogramPanel,
			"list_panel":        listPanel,
			"number_panel":      numberPanel,
			"pie_chart_panel":   pieChartPanel,
			"table_panel":       tablePanel,
			"time_series_panel": timeSeriesPanel,
		})

	return objVal, diags
}

func (v DashboardtypesPanelPluginValue) Equal(o attr.Value) bool {
	other, ok := o.(DashboardtypesPanelPluginValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.BarChartPanel.Equal(other.BarChartPanel) {
		return false
	}

	if !v.HistogramPanel.Equal(other.HistogramPanel) {
		return false
	}

	if !v.ListPanel.Equal(other.ListPanel) {
		return false
	}

	if !v.NumberPanel.Equal(other.NumberPanel) {
		return false
	}

	if !v.PieChartPanel.Equal(other.PieChartPanel) {
		return false
	}

	if !v.TablePanel.Equal(other.TablePanel) {
		return false
	}

	if !v.TimeSeriesPanel.Equal(other.TimeSeriesPanel) {
		return false
	}

	return true
}

func (v DashboardtypesPanelPluginValue) Type(ctx context.Context) attr.Type {
	return DashboardtypesPanelPluginType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DashboardtypesPanelPluginValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"bar_chart_panel": basetypes.ObjectType{
			AttrTypes: DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesBarChartPanelSpecValue{}.AttributeTypes(ctx),
		},
		"histogram_panel": basetypes.ObjectType{
			AttrTypes: DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesHistogramPanelSpecValue{}.AttributeTypes(ctx),
		},
		"list_panel": basetypes.ObjectType{
			AttrTypes: DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesListPanelSpecValue{}.AttributeTypes(ctx),
		},
		"number_panel": basetypes.ObjectType{
			AttrTypes: DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesNumberPanelSpecValue{}.AttributeTypes(ctx),
		},
		"pie_chart_panel": basetypes.ObjectType{
			AttrTypes: DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesPieChartPanelSpecValue{}.AttributeTypes(ctx),
		},
		"table_panel": basetypes.ObjectType{
			AttrTypes: DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesTablePanelSpecValue{}.AttributeTypes(ctx),
		},
		"time_series_panel": basetypes.ObjectType{
			AttrTypes: DashboardtypesPanelPluginVariantGithubComSigNozSignozPkgTypesDashboardtypesTimeSeriesPanelSpecValue{}.AttributeTypes(ctx),
		},
	}
}
