// Code generated by skaff types DO NOT EDIT.

package customtypes

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
)

var _ basetypes.ObjectTypable = DashboardtypesQuerySpecType{}

type DashboardtypesQuerySpecType struct {
	basetypes.ObjectType
}

func (t DashboardtypesQuerySpecType) Equal(o attr.Type) bool {
	other, ok := o.(DashboardtypesQuerySpecType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DashboardtypesQuerySpecType) String() string {
	return "DashboardtypesQuerySpecType"
}

func (t DashboardtypesQuerySpecType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	pluginAttribute, ok := attributes["plugin"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`plugin is missing from object`)

		return nil, diags
	}

	pluginVal, ok := pluginAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`plugin expected to be basetypes.ObjectValue, was: %T`, pluginAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DashboardtypesQuerySpecValue{
		Name:   nameVal,
		Plugin: pluginVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewDashboardtypesQuerySpecValueNull() DashboardtypesQuerySpecValue {
	return DashboardtypesQuerySpecValue{
		state: attr.ValueStateNull,
	}
}

func NewDashboardtypesQuerySpecValueUnknown() DashboardtypesQuerySpecValue {
	return DashboardtypesQuerySpecValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDashboardtypesQuerySpecValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DashboardtypesQuerySpecValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DashboardtypesQuerySpecValue Attribute Value",
				"While creating a DashboardtypesQuerySpecValue value, a missing attribute value was detected. "+
					"A DashboardtypesQuerySpecValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DashboardtypesQuerySpecValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DashboardtypesQuerySpecValue Attribute Type",
				"While creating a DashboardtypesQuerySpecValue value, an invalid attribute value was detected. "+
					"A DashboardtypesQuerySpecValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DashboardtypesQuerySpecValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DashboardtypesQuerySpecValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DashboardtypesQuerySpecValue Attribute Value",
				"While creating a DashboardtypesQuerySpecValue value, an extra attribute value was detected. "+
					"A DashboardtypesQuerySpecValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DashboardtypesQuerySpecValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDashboardtypesQuerySpecValueUnknown(), diags
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewDashboardtypesQuerySpecValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	pluginAttribute, ok := attributes["plugin"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`plugin is missing from object`)

		return NewDashboardtypesQuerySpecValueUnknown(), diags
	}

	pluginVal, ok := pluginAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`plugin expected to be basetypes.ObjectValue, was: %T`, pluginAttribute))
	}

	if diags.HasError() {
		return NewDashboardtypesQuerySpecValueUnknown(), diags
	}

	return DashboardtypesQuerySpecValue{
		Name:   nameVal,
		Plugin: pluginVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewDashboardtypesQuerySpecValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DashboardtypesQuerySpecValue {
	object, diags := NewDashboardtypesQuerySpecValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDashboardtypesQuerySpecValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DashboardtypesQuerySpecType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDashboardtypesQuerySpecValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDashboardtypesQuerySpecValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDashboardtypesQuerySpecValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDashboardtypesQuerySpecValueMust(DashboardtypesQuerySpecValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DashboardtypesQuerySpecType) ValueType(ctx context.Context) attr.Value {
	return DashboardtypesQuerySpecValue{}
}

var _ basetypes.ObjectValuable = DashboardtypesQuerySpecValue{}

type DashboardtypesQuerySpecValue struct {
	Name   basetypes.StringValue `tfsdk:"name"`
	Plugin basetypes.ObjectValue `tfsdk:"plugin"`
	state  attr.ValueState
}

func (v DashboardtypesQuerySpecValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["plugin"] = basetypes.ObjectType{
		AttrTypes: DashboardtypesQueryPluginValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Plugin.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["plugin"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DashboardtypesQuerySpecValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DashboardtypesQuerySpecValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DashboardtypesQuerySpecValue) String() string {
	return "DashboardtypesQuerySpecValue"
}

func (v DashboardtypesQuerySpecValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var plugin basetypes.ObjectValue

	if v.Plugin.IsNull() {
		plugin = types.ObjectNull(
			DashboardtypesQueryPluginValue{}.AttributeTypes(ctx),
		)
	}

	if v.Plugin.IsUnknown() {
		plugin = types.ObjectUnknown(
			DashboardtypesQueryPluginValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Plugin.IsNull() && !v.Plugin.IsUnknown() {
		plugin = types.ObjectValueMust(
			DashboardtypesQueryPluginValue{}.AttributeTypes(ctx),
			v.Plugin.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"name": basetypes.StringType{},
		"plugin": basetypes.ObjectType{
			AttrTypes: DashboardtypesQueryPluginValue{}.AttributeTypes(ctx),
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"name":   v.Name,
			"plugin": plugin,
		})

	return objVal, diags
}

func (v DashboardtypesQuerySpecValue) Equal(o attr.Value) bool {
	other, ok := o.(DashboardtypesQuerySpecValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Plugin.Equal(other.Plugin) {
		return false
	}

	return true
}

func (v DashboardtypesQuerySpecValue) Type(ctx context.Context) attr.Type {
	return DashboardtypesQuerySpecType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DashboardtypesQuerySpecValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"name": basetypes.StringType{},
		"plugin": basetypes.ObjectType{
			AttrTypes: DashboardtypesQueryPluginValue{}.AttributeTypes(ctx),
		},
	}
}
