// Code generated by skaff types DO NOT EDIT.

package customtypes

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
)

var _ basetypes.ObjectTypable = DashboardtypesTablePanelSpecType{}

type DashboardtypesTablePanelSpecType struct {
	basetypes.ObjectType
}

func (t DashboardtypesTablePanelSpecType) Equal(o attr.Type) bool {
	other, ok := o.(DashboardtypesTablePanelSpecType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DashboardtypesTablePanelSpecType) String() string {
	return "DashboardtypesTablePanelSpecType"
}

func (t DashboardtypesTablePanelSpecType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	formattingAttribute, ok := attributes["formatting"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`formatting is missing from object`)

		return nil, diags
	}

	formattingVal, ok := formattingAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`formatting expected to be basetypes.ObjectValue, was: %T`, formattingAttribute))
	}

	thresholdsAttribute, ok := attributes["thresholds"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`thresholds is missing from object`)

		return nil, diags
	}

	thresholdsVal, ok := thresholdsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`thresholds expected to be basetypes.ListValue, was: %T`, thresholdsAttribute))
	}

	visualizationAttribute, ok := attributes["visualization"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`visualization is missing from object`)

		return nil, diags
	}

	visualizationVal, ok := visualizationAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`visualization expected to be basetypes.ObjectValue, was: %T`, visualizationAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DashboardtypesTablePanelSpecValue{
		Formatting:    formattingVal,
		Thresholds:    thresholdsVal,
		Visualization: visualizationVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewDashboardtypesTablePanelSpecValueNull() DashboardtypesTablePanelSpecValue {
	return DashboardtypesTablePanelSpecValue{
		state: attr.ValueStateNull,
	}
}

func NewDashboardtypesTablePanelSpecValueUnknown() DashboardtypesTablePanelSpecValue {
	return DashboardtypesTablePanelSpecValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDashboardtypesTablePanelSpecValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DashboardtypesTablePanelSpecValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DashboardtypesTablePanelSpecValue Attribute Value",
				"While creating a DashboardtypesTablePanelSpecValue value, a missing attribute value was detected. "+
					"A DashboardtypesTablePanelSpecValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DashboardtypesTablePanelSpecValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DashboardtypesTablePanelSpecValue Attribute Type",
				"While creating a DashboardtypesTablePanelSpecValue value, an invalid attribute value was detected. "+
					"A DashboardtypesTablePanelSpecValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DashboardtypesTablePanelSpecValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DashboardtypesTablePanelSpecValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DashboardtypesTablePanelSpecValue Attribute Value",
				"While creating a DashboardtypesTablePanelSpecValue value, an extra attribute value was detected. "+
					"A DashboardtypesTablePanelSpecValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DashboardtypesTablePanelSpecValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDashboardtypesTablePanelSpecValueUnknown(), diags
	}

	formattingAttribute, ok := attributes["formatting"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`formatting is missing from object`)

		return NewDashboardtypesTablePanelSpecValueUnknown(), diags
	}

	formattingVal, ok := formattingAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`formatting expected to be basetypes.ObjectValue, was: %T`, formattingAttribute))
	}

	thresholdsAttribute, ok := attributes["thresholds"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`thresholds is missing from object`)

		return NewDashboardtypesTablePanelSpecValueUnknown(), diags
	}

	thresholdsVal, ok := thresholdsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`thresholds expected to be basetypes.ListValue, was: %T`, thresholdsAttribute))
	}

	visualizationAttribute, ok := attributes["visualization"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`visualization is missing from object`)

		return NewDashboardtypesTablePanelSpecValueUnknown(), diags
	}

	visualizationVal, ok := visualizationAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`visualization expected to be basetypes.ObjectValue, was: %T`, visualizationAttribute))
	}

	if diags.HasError() {
		return NewDashboardtypesTablePanelSpecValueUnknown(), diags
	}

	return DashboardtypesTablePanelSpecValue{
		Formatting:    formattingVal,
		Thresholds:    thresholdsVal,
		Visualization: visualizationVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewDashboardtypesTablePanelSpecValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DashboardtypesTablePanelSpecValue {
	object, diags := NewDashboardtypesTablePanelSpecValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDashboardtypesTablePanelSpecValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DashboardtypesTablePanelSpecType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDashboardtypesTablePanelSpecValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDashboardtypesTablePanelSpecValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDashboardtypesTablePanelSpecValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDashboardtypesTablePanelSpecValueMust(DashboardtypesTablePanelSpecValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DashboardtypesTablePanelSpecType) ValueType(ctx context.Context) attr.Value {
	return DashboardtypesTablePanelSpecValue{}
}

var _ basetypes.ObjectValuable = DashboardtypesTablePanelSpecValue{}

type DashboardtypesTablePanelSpecValue struct {
	Formatting    basetypes.ObjectValue `tfsdk:"formatting"`
	Thresholds    basetypes.ListValue   `tfsdk:"thresholds"`
	Visualization basetypes.ObjectValue `tfsdk:"visualization"`
	state         attr.ValueState
}

func (v DashboardtypesTablePanelSpecValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["formatting"] = basetypes.ObjectType{
		AttrTypes: DashboardtypesTableFormattingValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["thresholds"] = basetypes.ListType{
		ElemType: DashboardtypesTableThresholdValue{}.Type(ctx),
	}.TerraformType(ctx)
	attrTypes["visualization"] = basetypes.ObjectType{
		AttrTypes: DashboardtypesBasicVisualizationValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Formatting.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["formatting"] = val

		val, err = v.Thresholds.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["thresholds"] = val

		val, err = v.Visualization.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["visualization"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DashboardtypesTablePanelSpecValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DashboardtypesTablePanelSpecValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DashboardtypesTablePanelSpecValue) String() string {
	return "DashboardtypesTablePanelSpecValue"
}

func (v DashboardtypesTablePanelSpecValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var formatting basetypes.ObjectValue

	if v.Formatting.IsNull() {
		formatting = types.ObjectNull(
			DashboardtypesTableFormattingValue{}.AttributeTypes(ctx),
		)
	}

	if v.Formatting.IsUnknown() {
		formatting = types.ObjectUnknown(
			DashboardtypesTableFormattingValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Formatting.IsNull() && !v.Formatting.IsUnknown() {
		formatting = types.ObjectValueMust(
			DashboardtypesTableFormattingValue{}.AttributeTypes(ctx),
			v.Formatting.Attributes(),
		)
	}

	thresholds := types.ListValueMust(
		DashboardtypesTableThresholdType{
			basetypes.ObjectType{
				AttrTypes: DashboardtypesTableThresholdValue{}.AttributeTypes(ctx),
			},
		},
		v.Thresholds.Elements(),
	)

	if v.Thresholds.IsNull() {
		thresholds = types.ListNull(
			DashboardtypesTableThresholdType{
				basetypes.ObjectType{
					AttrTypes: DashboardtypesTableThresholdValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.Thresholds.IsUnknown() {
		thresholds = types.ListUnknown(
			DashboardtypesTableThresholdType{
				basetypes.ObjectType{
					AttrTypes: DashboardtypesTableThresholdValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	var visualization basetypes.ObjectValue

	if v.Visualization.IsNull() {
		visualization = types.ObjectNull(
			DashboardtypesBasicVisualizationValue{}.AttributeTypes(ctx),
		)
	}

	if v.Visualization.IsUnknown() {
		visualization = types.ObjectUnknown(
			DashboardtypesBasicVisualizationValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Visualization.IsNull() && !v.Visualization.IsUnknown() {
		visualization = types.ObjectValueMust(
			DashboardtypesBasicVisualizationValue{}.AttributeTypes(ctx),
			v.Visualization.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"formatting": basetypes.ObjectType{
			AttrTypes: DashboardtypesTableFormattingValue{}.AttributeTypes(ctx),
		},
		"thresholds": basetypes.ListType{
			ElemType: DashboardtypesTableThresholdValue{}.Type(ctx),
		},
		"visualization": basetypes.ObjectType{
			AttrTypes: DashboardtypesBasicVisualizationValue{}.AttributeTypes(ctx),
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"formatting":    formatting,
			"thresholds":    thresholds,
			"visualization": visualization,
		})

	return objVal, diags
}

func (v DashboardtypesTablePanelSpecValue) Equal(o attr.Value) bool {
	other, ok := o.(DashboardtypesTablePanelSpecValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Formatting.Equal(other.Formatting) {
		return false
	}

	if !v.Thresholds.Equal(other.Thresholds) {
		return false
	}

	if !v.Visualization.Equal(other.Visualization) {
		return false
	}

	return true
}

func (v DashboardtypesTablePanelSpecValue) Type(ctx context.Context) attr.Type {
	return DashboardtypesTablePanelSpecType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DashboardtypesTablePanelSpecValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"formatting": basetypes.ObjectType{
			AttrTypes: DashboardtypesTableFormattingValue{}.AttributeTypes(ctx),
		},
		"thresholds": basetypes.ListType{
			ElemType: DashboardtypesTableThresholdValue{}.Type(ctx),
		},
		"visualization": basetypes.ObjectType{
			AttrTypes: DashboardtypesBasicVisualizationValue{}.AttributeTypes(ctx),
		},
	}
}
