// Code generated by skaff types DO NOT EDIT.

package customtypes

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
)

var _ basetypes.ObjectTypable = AlertmanagertypesChannelSlackConfigType{}

type AlertmanagertypesChannelSlackConfigType struct {
	basetypes.ObjectType
}

func (t AlertmanagertypesChannelSlackConfigType) Equal(o attr.Type) bool {
	other, ok := o.(AlertmanagertypesChannelSlackConfigType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AlertmanagertypesChannelSlackConfigType) String() string {
	return "AlertmanagertypesChannelSlackConfigType"
}

func (t AlertmanagertypesChannelSlackConfigType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	apiUrlAttribute, ok := attributes["api_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`api_url is missing from object`)

		return nil, diags
	}

	apiUrlVal, ok := apiUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`api_url expected to be basetypes.StringValue, was: %T`, apiUrlAttribute))
	}

	channelAttribute, ok := attributes["channel"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`channel is missing from object`)

		return nil, diags
	}

	channelVal, ok := channelAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`channel expected to be basetypes.StringValue, was: %T`, channelAttribute))
	}

	sendResolvedAttribute, ok := attributes["send_resolved"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`send_resolved is missing from object`)

		return nil, diags
	}

	sendResolvedVal, ok := sendResolvedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`send_resolved expected to be basetypes.BoolValue, was: %T`, sendResolvedAttribute))
	}

	textAttribute, ok := attributes["text"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`text is missing from object`)

		return nil, diags
	}

	textVal, ok := textAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`text expected to be basetypes.StringValue, was: %T`, textAttribute))
	}

	titleAttribute, ok := attributes["title"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`title is missing from object`)

		return nil, diags
	}

	titleVal, ok := titleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`title expected to be basetypes.StringValue, was: %T`, titleAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AlertmanagertypesChannelSlackConfigValue{
		ApiUrl:       apiUrlVal,
		Channel:      channelVal,
		SendResolved: sendResolvedVal,
		Text:         textVal,
		Title:        titleVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewAlertmanagertypesChannelSlackConfigValueNull() AlertmanagertypesChannelSlackConfigValue {
	return AlertmanagertypesChannelSlackConfigValue{
		state: attr.ValueStateNull,
	}
}

func NewAlertmanagertypesChannelSlackConfigValueUnknown() AlertmanagertypesChannelSlackConfigValue {
	return AlertmanagertypesChannelSlackConfigValue{
		state: attr.ValueStateUnknown,
	}
}

func NewAlertmanagertypesChannelSlackConfigValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AlertmanagertypesChannelSlackConfigValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AlertmanagertypesChannelSlackConfigValue Attribute Value",
				"While creating a AlertmanagertypesChannelSlackConfigValue value, a missing attribute value was detected. "+
					"A AlertmanagertypesChannelSlackConfigValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AlertmanagertypesChannelSlackConfigValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AlertmanagertypesChannelSlackConfigValue Attribute Type",
				"While creating a AlertmanagertypesChannelSlackConfigValue value, an invalid attribute value was detected. "+
					"A AlertmanagertypesChannelSlackConfigValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AlertmanagertypesChannelSlackConfigValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AlertmanagertypesChannelSlackConfigValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AlertmanagertypesChannelSlackConfigValue Attribute Value",
				"While creating a AlertmanagertypesChannelSlackConfigValue value, an extra attribute value was detected. "+
					"A AlertmanagertypesChannelSlackConfigValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AlertmanagertypesChannelSlackConfigValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewAlertmanagertypesChannelSlackConfigValueUnknown(), diags
	}

	apiUrlAttribute, ok := attributes["api_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`api_url is missing from object`)

		return NewAlertmanagertypesChannelSlackConfigValueUnknown(), diags
	}

	apiUrlVal, ok := apiUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`api_url expected to be basetypes.StringValue, was: %T`, apiUrlAttribute))
	}

	channelAttribute, ok := attributes["channel"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`channel is missing from object`)

		return NewAlertmanagertypesChannelSlackConfigValueUnknown(), diags
	}

	channelVal, ok := channelAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`channel expected to be basetypes.StringValue, was: %T`, channelAttribute))
	}

	sendResolvedAttribute, ok := attributes["send_resolved"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`send_resolved is missing from object`)

		return NewAlertmanagertypesChannelSlackConfigValueUnknown(), diags
	}

	sendResolvedVal, ok := sendResolvedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`send_resolved expected to be basetypes.BoolValue, was: %T`, sendResolvedAttribute))
	}

	textAttribute, ok := attributes["text"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`text is missing from object`)

		return NewAlertmanagertypesChannelSlackConfigValueUnknown(), diags
	}

	textVal, ok := textAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`text expected to be basetypes.StringValue, was: %T`, textAttribute))
	}

	titleAttribute, ok := attributes["title"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`title is missing from object`)

		return NewAlertmanagertypesChannelSlackConfigValueUnknown(), diags
	}

	titleVal, ok := titleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`title expected to be basetypes.StringValue, was: %T`, titleAttribute))
	}

	if diags.HasError() {
		return NewAlertmanagertypesChannelSlackConfigValueUnknown(), diags
	}

	return AlertmanagertypesChannelSlackConfigValue{
		ApiUrl:       apiUrlVal,
		Channel:      channelVal,
		SendResolved: sendResolvedVal,
		Text:         textVal,
		Title:        titleVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewAlertmanagertypesChannelSlackConfigValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AlertmanagertypesChannelSlackConfigValue {
	object, diags := NewAlertmanagertypesChannelSlackConfigValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewAlertmanagertypesChannelSlackConfigValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AlertmanagertypesChannelSlackConfigType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewAlertmanagertypesChannelSlackConfigValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewAlertmanagertypesChannelSlackConfigValueUnknown(), nil
	}

	if in.IsNull() {
		return NewAlertmanagertypesChannelSlackConfigValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewAlertmanagertypesChannelSlackConfigValueMust(AlertmanagertypesChannelSlackConfigValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AlertmanagertypesChannelSlackConfigType) ValueType(ctx context.Context) attr.Value {
	return AlertmanagertypesChannelSlackConfigValue{}
}

var _ basetypes.ObjectValuable = AlertmanagertypesChannelSlackConfigValue{}

type AlertmanagertypesChannelSlackConfigValue struct {
	ApiUrl       basetypes.StringValue `tfsdk:"api_url"`
	Channel      basetypes.StringValue `tfsdk:"channel"`
	SendResolved basetypes.BoolValue   `tfsdk:"send_resolved"`
	Text         basetypes.StringValue `tfsdk:"text"`
	Title        basetypes.StringValue `tfsdk:"title"`
	state        attr.ValueState
}

func (v AlertmanagertypesChannelSlackConfigValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["api_url"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["channel"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["send_resolved"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["text"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["title"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.ApiUrl.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["api_url"] = val

		val, err = v.Channel.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["channel"] = val

		val, err = v.SendResolved.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["send_resolved"] = val

		val, err = v.Text.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["text"] = val

		val, err = v.Title.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["title"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AlertmanagertypesChannelSlackConfigValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AlertmanagertypesChannelSlackConfigValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AlertmanagertypesChannelSlackConfigValue) String() string {
	return "AlertmanagertypesChannelSlackConfigValue"
}

func (v AlertmanagertypesChannelSlackConfigValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"api_url":       basetypes.StringType{},
		"channel":       basetypes.StringType{},
		"send_resolved": basetypes.BoolType{},
		"text":          basetypes.StringType{},
		"title":         basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"api_url":       v.ApiUrl,
			"channel":       v.Channel,
			"send_resolved": v.SendResolved,
			"text":          v.Text,
			"title":         v.Title,
		})

	return objVal, diags
}

func (v AlertmanagertypesChannelSlackConfigValue) Equal(o attr.Value) bool {
	other, ok := o.(AlertmanagertypesChannelSlackConfigValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ApiUrl.Equal(other.ApiUrl) {
		return false
	}

	if !v.Channel.Equal(other.Channel) {
		return false
	}

	if !v.SendResolved.Equal(other.SendResolved) {
		return false
	}

	if !v.Text.Equal(other.Text) {
		return false
	}

	if !v.Title.Equal(other.Title) {
		return false
	}

	return true
}

func (v AlertmanagertypesChannelSlackConfigValue) Type(ctx context.Context) attr.Type {
	return AlertmanagertypesChannelSlackConfigType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AlertmanagertypesChannelSlackConfigValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"api_url":       basetypes.StringType{},
		"channel":       basetypes.StringType{},
		"send_resolved": basetypes.BoolType{},
		"text":          basetypes.StringType{},
		"title":         basetypes.StringType{},
	}
}
