name: docsci

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  docs:
    name: generate and validate docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: generate
        run: go generate ./...
      - name: drift
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Docs are out of date. Run 'go generate ./...' and commit the result."; exit 1)
      - name: validate
        run: go run github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs validate -provider-name signoz
